/**
 * Textos del paquete «account-help» (ajustes, ayuda, legal, derechos sobre los datos y estado del servicio).
 * Español de España, tuteo. Los literales de las láminas 34 (Ajustes), 35 (Centro de ayuda) y 36 (Si algo no va bien)
 * van tal cual; el resto sigue su voz: frases cortas, sin tecnicismos, sin promesas que el servidor no confirme.
 */
import type { SupportCategory, SupportTicketStatus, DataExportStatus, FontScale } from "@/api/types";

export const helpStrings = {
  common: {
    retry: "Reintentar",
    cancel: "Cancelar",
    close: "Cerrar",
    continue: "Continuar",
    done: "Listo",
    accept: "Aceptar",
    offlineTitle: "Sin conexión",
    offlineDetail: "Mostramos lo último que teníamos",
    offlineMessage: "No tenemos Internet en este momento. Comprueba tu conexión e inténtalo de nuevo.",
    offlineAction: "Esta acción necesita Internet. Inténtalo de nuevo cuando vuelvas a tener conexión.",
    loadErrorTitle: "No hemos podido cargar esta pantalla",
    loadErrorMessage: "Comprueba tu conexión e inténtalo de nuevo.",
    guestTitle: "Necesitas una cuenta",
    guestMessage: "Crea una cuenta o entra con tu móvil para usar esta función.",
    guestAction: "Crear cuenta o entrar",
    updatedAt: (when: string) => `Actualizado ${when}`,
  },

  // ── 34 · Ajustes ───────────────────────────────────────────────────────────────────────────────────────────────
  settings: {
    title: "Ajustes",
    profileA11y: (name: string, role: string) => `Mi perfil, ${name}, ${role}`,
    defaultName: "Mi perfil",
    roleDriver: "Conductora",
    rolePassenger: "Pasajera",
    roleBoth: "Conductora y pasajera",
    roleStaff: "Equipo de MVC",
    roleNone: "Cuenta de MVC",
    phoneTitle: "Mi móvil",
    phoneUnknown: "Sin número registrado",
    notificationsTitle: "Notificaciones",
    notificationsSubtitle: "Viajes, mensajes y novedades",
    shareLocationTitle: "Compartir ubicación en viaje",
    shareLocationSubtitle: "Solo durante el trayecto activo",
    shareLocationA11y: "Compartir mi ubicación durante el viaje",
    shareLocationSaving: "Guardando…",
    shareLocationError: "No hemos podido guardar este ajuste.",
    fontSizeTitle: "Tamaño de letra",
    privacyTitle: "Privacidad y datos",
    permissionsTitle: "Permisos de la app",
    deleteTitle: "Eliminar cuenta",
    deleteHelperLine1: "Puedes solicitar la eliminación de tu cuenta,",
    deleteHelperLine2: "Se borrarán tus datos y no podrás recuperar el acceso.",
    deletePendingTitle: "Eliminación de la cuenta programada",
    deletePendingMessage: (date: string) => `Se eliminará el ${date}. Hasta entonces puedes cancelarla.`,
    deletePendingAction: "Ver y cancelar",
    logoutTitle: "Cerrar sesión",
    logoutConfirmTitle: "¿Cerrar sesión?",
    logoutConfirmMessage:
      "Dejarás de recibir avisos de MVC en este móvil. Podrás volver a entrar cuando quieras con tu número de móvil.",
    logoutConfirm: "Cerrar sesión",
    logoutWorking: "Cerrando sesión…",
    guestLogoutTitle: "Salir del modo invitado",
    guestLogoutConfirmTitle: "¿Salir del modo invitado?",
    guestLogoutConfirmMessage: "Volverás a la pantalla de bienvenida.",
    guestLogoutConfirm: "Salir",
    guestCardTitle: "Estás explorando sin cuenta",
    guestCardMessage: "Crea una cuenta para guardar tus ajustes, pedir plaza y recibir avisos.",
    footerSection: "Ayuda e información",
    footerVersion: (version: string) => `MVC · Me voy contigo · versión ${version}`,
    retryRow: "Reintentar",
    footerHelp: "Centro de ayuda",
    footerStatus: "Estado del servicio",
    footerLegal: "Información legal",
    footerAbout: "Acerca de MVC",
    loadErrorTitle: "No hemos podido cargar tus ajustes",
    loadErrorMessage: "Puedes seguir viendo las opciones de abajo. Inténtalo de nuevo para cargar los datos de tu cuenta.",
    savedToast: "Ajuste guardado",
    fontSavedLocalOnly: "Tamaño aplicado en este móvil, pero no se ha guardado en tu cuenta.",
  },

  mobileSheet: {
    title: "Mi móvil",
    intro: "Es el número con el que entras en MVC y al que enviamos el código de verificación.",
    changeTitle: "¿Has cambiado de número?",
    changeMessage:
      "El cambio de número lo gestiona nuestro equipo desde el Centro de ayuda («Mi perfil y cuenta»): comprobaremos que la cuenta es tuya antes de actualizarlo.",
    changeAction: "Pedir el cambio de número",
    copy: "Copiar número",
    copied: "Número copiado",
  },

  fontSheet: {
    title: "Tamaño de letra",
    subtitle: "Se aplica a toda la app. Puedes cambiarlo cuando quieras.",
    preview: "Así se verá el texto en MVC.",
    previewBody: "Los títulos, los botones y los mensajes se ajustan a este tamaño.",
    previewTitle: "Vista previa",
    localNote: "Este tamaño se aplica en este móvil. Entra con tu cuenta para guardarlo y verlo también en otros dispositivos.",
    done: "Listo",
    options: {
      small: { label: "Pequeño", description: "Caben más cosas en pantalla" },
      normal: { label: "Normal", description: "El tamaño recomendado" },
      large: { label: "Grande", description: "Más fácil de leer" },
      extra_large: { label: "Muy grande", description: "El máximo tamaño de la app" },
    } satisfies Record<FontScale, { label: string; description: string }>,
  },

  // ── Privacidad y datos ─────────────────────────────────────────────────────────────────────────────────────────
  privacy: {
    title: "Privacidad y datos",
    intro: "Tú decides qué datos tuyos guarda MVC. Aquí puedes pedir una copia, revisar a quién has bloqueado y eliminar tu cuenta.",
    exportTitle: "Descargar mis datos",
    exportSubtitle: "Pide una copia de tus datos en formato JSON",
    blockedTitle: "Personas bloqueadas",
    blockedSubtitle: "Quién no puede escribirte ni viajar contigo",
    legalTitle: "Información legal",
    legalSubtitle: "Términos, privacidad y cancelaciones",
    ticketsTitle: "Mis consultas",
    ticketsSubtitle: "Tus mensajes con el equipo de MVC",
    deleteTitle: "Eliminar cuenta",
    deleteSubtitle: "Se borrarán tus datos personales",
    sectionData: "Tus datos",
    sectionInfo: "Información",
    sectionDanger: "Zona delicada",
  },

  // ── Permisos de la app ─────────────────────────────────────────────────────────────────────────────────────────
  permissions: {
    title: "Permisos de la app",
    intro: "MVC solo usa lo que necesita para que viajes mejor. Aquí ves qué has permitido y puedes cambiarlo en los ajustes del móvil.",
    location: {
      title: "Ubicación",
      reason: "Para centrar el mapa, proponerte puntos de recogida cercanos y, durante un viaje en curso, mostrar tu posición a quien viaja contigo.",
    },
    notifications: {
      title: "Notificaciones",
      reason: "Para avisarte de respuestas a tus solicitudes, cambios en tu viaje y mensajes.",
    },
    camera: {
      title: "Cámara",
      reason: "Para hacerte la foto de perfil, la comprobación privada de tu cuenta y fotografiar documentos.",
    },
    status: {
      granted: "Permitido",
      denied: "Sin permitir",
      blocked: "Bloqueado en el móvil",
      unavailable: "No disponible en este dispositivo",
      undetermined: "Sin decidir",
    },
    actionAllow: "Permitir",
    actionSettings: "Abrir ajustes del móvil",
    settingsHint: "Para cambiarlo, abre los ajustes del móvil: allí puedes permitir o quitar el permiso.",
    settingsFailed: "No hemos podido abrir los ajustes del móvil. Ábrelos a mano y busca MVC.",
    footer: "No usamos tu ubicación en segundo plano ni el micrófono.",
  },

  // ── 35 · Centro de ayuda ───────────────────────────────────────────────────────────────────────────────────────
  help: {
    title: "Centro de ayuda",
    introTitle: "¿En qué podemos ayudarte?",
    introMessage: "Cuéntanos qué ha pasado y te responderemos lo antes posible.",
    categories: {
      trip_issue: "Problema en un viaje",
      payment_issue: "Problema de pago",
      account_profile: "Mi perfil y cuenta",
    } satisfies Record<SupportCategory, string>,
    /** Las láminas parten el nombre en dos líneas dentro de cada baldosa. */
    categoryTiles: {
      trip_issue: "Problema\nen un viaje",
      payment_issue: "Problema\nde pago",
      account_profile: "Mi perfil\ny cuenta",
    } satisfies Record<SupportCategory, string>,
    categoryGroupA11y: "Tipo de consulta",
    moreHelpTitle: "Más ayuda",
    moreHelpStatus: "Estado del servicio",
    moreHelpStatusSubtitle: "Qué podemos comprobar desde tu móvil",
    moreHelpLegal: "Información legal",
    moreHelpLegalSubtitle: "Términos, privacidad y cancelaciones",
    attachHelper: "Fotos de pantallazos, daños o recibos que nos ayuden a entender qué ha pasado.",
    tripLabel: "Selecciona un viaje (opcional)",
    tripPlaceholder: "Sin viaje seleccionado",
    tripSheetTitle: "Selecciona un viaje",
    tripSheetSubtitle: "Viajes en los que has participado, del más reciente al más antiguo.",
    tripNone: "Sin viaje",
    tripNoneDescription: "Mi consulta no es sobre un viaje concreto",
    tripEmptyTitle: "Aún no tienes viajes",
    tripEmptyMessage: "Puedes enviar tu consulta sin elegir ninguno.",
    tripLoadError: "No hemos podido cargar tus viajes. Puedes enviar la consulta sin elegir uno.",
    tripRoleDriver: "Como conductora",
    tripRolePassenger: "Como pasajera",
    tripUnknownPlace: "Sin dato",
    tripUnknownDay: "Sin fecha",
    bodyLabel: "Escribe tu consulta",
    bodyPlaceholder: "Cuéntanos qué ha pasado...",
    attachLabel: "Adjuntar imágenes (opcional)",
    attachButton: "Subir imagen",
    attachCount: (n: number, max: number) => `${n} de ${max} imágenes`,
    attachRemove: (name: string) => `Quitar ${name}`,
    attachSheetTitle: "Subir imagen",
    attachCamera: "Hacer una foto",
    attachGallery: "Elegir de la galería",
    attachLimit: (max: number) => `Puedes adjuntar hasta ${max} imágenes.`,
    attachUploading: "Subiendo…",
    attachFailed: "No se ha podido subir",
    attachRetry: "Reintentar subida",
    attachUnavailableTitle: "Ahora mismo no se pueden adjuntar imágenes",
    attachUnavailableMessage: "Puedes enviar tu consulta igualmente, solo con texto, y te responderemos del mismo modo.",
    attachPermissionTitle: "Necesitamos acceso a la cámara o a tus fotos",
    attachPermissionMessage: "Puedes dar el permiso en los ajustes del móvil o enviar la consulta sin imágenes.",
    attachOpenSettings: "Abrir ajustes",
    attachNoCamera: "No hemos podido abrir la cámara en este dispositivo. Prueba con la galería.",
    attachTooLarge: "Esa imagen pesa más de 10 MB. Elige otra o hazla de nuevo.",
    attachType: "Solo se pueden adjuntar fotos (JPG, PNG, WebP o HEIC).",
    attachImageName: (n: number) => `Imagen ${n}`,
    submit: "Enviar consulta",
    submitting: "Enviando…",
    urgentTitle: "Si es urgente",
    urgentMessage: "Para incidencias durante un viaje en curso, contacta directamente con la otra persona desde el chat del viaje.",
    historyTitle: "Mis consultas",
    historyAll: "Ver todas",
    historyEmpty: "Todavía no has enviado ninguna consulta.",
    historyError: "No hemos podido cargar tus consultas.",
    guestMessage: "Para escribir al equipo de MVC necesitas una cuenta: así podemos responderte.",
    validation: {
      category: "Elige el tipo de consulta.",
      bodyEmpty: "Escribe tu consulta.",
      bodyTooLong: "La consulta no puede tener más de 500 caracteres.",
      attachmentsPending: "Espera a que terminen de subirse las imágenes o quítalas.",
    },
    sentTitle: "Consulta enviada",
    sentMessage: (reference: string) => `Hemos recibido tu consulta. Tu referencia es ${reference}. Te responderemos lo antes posible.`,
    sentViewTicket: "Ver mi consulta",
    sentNew: "Enviar otra consulta",
    sentBack: "Volver",
    sendFailedTitle: "No se ha podido enviar la consulta",
    sendFailedMessage: "No se ha enviado nada. Revisa tu conexión e inténtalo de nuevo.",
    sendOfflineMessage: "Sin conexión: no se ha enviado nada. Tu texto sigue aquí; inténtalo cuando vuelvas a tener Internet.",
  },

  // ── Consultas (historial e hilo) ───────────────────────────────────────────────────────────────────────────────
  tickets: {
    listTitle: "Mis consultas",
    newTitle: "Nueva consulta",
    detailTitle: "Consulta",
    newAction: "Nueva consulta",
    filterAll: "Todas",
    filterOpen: "Abiertas",
    filterAnswered: "Respondidas",
    filterClosed: "Cerradas",
    filterA11y: "Filtrar consultas por estado",
    emptyTitle: "Aún no tienes consultas",
    emptyMessage: "Cuando escribas al equipo de MVC verás aquí tu consulta y sus respuestas.",
    emptyFilteredTitle: "Sin consultas en este estado",
    emptyFilteredMessage: "Prueba con otro filtro para ver el resto de tus consultas.",
    loadErrorTitle: "No hemos podido cargar tus consultas",
    loadMore: "Ver más consultas",
    status: {
      open: "Abierta",
      answered: "Respondida",
      closed: "Cerrada",
    } satisfies Record<SupportTicketStatus, string>,
    statusHint: {
      open: "Estamos revisando tu consulta. Te avisaremos cuando respondamos.",
      answered: "El equipo de MVC te ha respondido. Puedes contestar desde aquí.",
      closed: "Esta consulta está cerrada.",
    } satisfies Record<SupportTicketStatus, string>,
    reference: (ref: string) => `Referencia ${ref}`,
    lastActivity: (when: string) => `Última actividad: ${when}`,
    attachments: (n: number) => (n === 1 ? "1 imagen" : `${n} imágenes`),
    authorUser: "Tú",
    authorStaff: "Equipo MVC",
    relatedTrip: "Viaje relacionado",
    relatedTripUnknown: "Viaje relacionado con esta consulta",
    replyLabel: "Tu respuesta",
    replyPlaceholder: "Escribe tu respuesta...",
    replySubmit: "Enviar respuesta",
    replyEmpty: "Escribe tu respuesta.",
    replyTooLong: "La respuesta no puede tener más de 1.000 caracteres.",
    replyFailedTitle: "No se ha podido enviar la respuesta",
    closeAction: "Cerrar consulta",
    closeConfirmTitle: "¿Cerrar esta consulta?",
    closeConfirmMessage: "Si ya está resuelta puedes cerrarla. Después no podrás añadir más mensajes: tendrías que abrir una consulta nueva.",
    closeConfirm: "Cerrar consulta",
    closedToast: "Consulta cerrada",
    closedNoticeTitle: "Consulta cerrada",
    closedNoticeMessage: (date: string) => `Se cerró el ${date}. Si necesitas algo más, abre una consulta nueva.`,
    closedNoticeNoDate: "Si necesitas algo más, abre una consulta nueva.",
    attachmentOpen: "Ver imagen",
    attachmentOpening: "Abriendo…",
    attachmentFailed: "No hemos podido abrir la imagen. Inténtalo de nuevo.",
    attachmentImage: (n: number) => `Imagen ${n}`,
    notFoundTitle: "No encontramos esta consulta",
    notFoundMessage: "Puede que ya no exista. Mira tu lista de consultas.",
    notFoundAction: "Ver mis consultas",
  },

  // ── Descargar mis datos ────────────────────────────────────────────────────────────────────────────────────────
  exports: {
    title: "Descargar mis datos",
    intro: "Pide una copia de los datos que MVC guarda sobre ti. Recibirás un archivo JSON solo con tus datos, no con los de otras personas.",
    request: "Solicitar mis datos",
    requesting: "Solicitando…",
    historyTitle: "Tus solicitudes",
    historyEmpty: "Todavía no has pedido ninguna copia.",
    loadErrorTitle: "No hemos podido cargar tus solicitudes",
    requestedAt: (date: string) => `Solicitada el ${date}`,
    availableUntil: (date: string) => `Disponible hasta el ${date}`,
    expiredOn: (date: string) => `Caducó el ${date}`,
    sizeLabel: (size: string) => `Tamaño: ${size}`,
    status: {
      queued: "En cola",
      processing: "Preparando",
      ready: "Lista",
      failed: "Ha fallado",
      blocked_storage_disabled: "No disponible",
      expired: "Caducada",
    } satisfies Record<DataExportStatus, string>,
    statusHint: {
      queued: "Tu solicitud está en cola. Te avisaremos cuando esté lista; no hace falta que te quedes en esta pantalla.",
      processing: "Estamos preparando tu archivo. Suele tardar unos minutos.",
      ready: "Tu archivo está listo para descargar.",
      failed: "No hemos podido preparar este archivo. Puedes pedir otra copia.",
      blocked_storage_disabled:
        "Ahora mismo el servicio no puede guardar archivos privados, así que no se ha generado nada. Puedes volver a pedirlo más adelante.",
      expired: "El enlace ha caducado y el archivo se ha borrado. Puedes pedir otra copia.",
    } satisfies Record<DataExportStatus, string>,
    download: "Descargar",
    downloading: "Preparando enlace…",
    downloadNote: "El enlace de descarga caduca a los 5 minutos. Si caduca, vuelve a pulsar «Descargar».",
    downloadOpenFailed: "No hemos podido abrir el enlace. Cópialo y ábrelo en el navegador.",
    downloadCopyLink: "Copiar enlace",
    downloadLinkCopied: "Enlace copiado",
    downloadSheetTitle: "Tu archivo está listo",
    downloadSheetMessage: (time: string) => `El enlace funciona hasta las ${time}. Se abrirá en el navegador del móvil.`,
    downloadOpen: "Abrir enlace",
    privacyNote:
      "El archivo indica al final qué secciones todavía no se incluyen. Solo puedes pedir una copia cada 24 horas.",
    rateLimitedTitle: "Ya has pedido una copia hace poco",
    rateLimitedMessage: "Solo se puede pedir una copia cada 24 horas. Cuando esté lista la verás aquí.",
    requestedToast: "Solicitud enviada",
    pollNote: "Se actualiza sola mientras se prepara.",
  },

  // ── Eliminar cuenta ────────────────────────────────────────────────────────────────────────────────────────────
  deletion: {
    title: "Eliminar cuenta",
    intro: "Vas a pedir la eliminación de tu cuenta de MVC. Léelo con calma: es una decisión que no se puede deshacer una vez ejecutada.",
    graceTitle: (days: number) => `Tienes ${days} días para arrepentirte`,
    graceMessage: (days: number) =>
      `Tu cuenta seguirá activa durante ${days} días tras la solicitud y podrás cancelarla cuando quieras. Pasado ese plazo se elimina automáticamente.`,
    planTitle: "Qué pasará con tus datos",
    planDeleted: "Se borrará",
    planAnonymised: "Se conservará sin identificarte",
    planRetained: "Se conservará por obligación legal",
    retainedFor: (period: string) => `Plazo: ${period}`,
    planLoadError: "No hemos podido cargar el detalle de lo que se borrará.",
    blockersTitle: "Ahora mismo no puedes eliminar tu cuenta",
    blockersMessage: "Resuelve esto primero y vuelve a intentarlo:",
    blockersCount: (n: number) => (n === 1 ? "1 elemento" : `${n} elementos`),
    blockerAction: {
      ACTIVE_TRIP_AS_DRIVER: "Ver mis viajes",
      UPCOMING_BOOKING_AS_PASSENGER: "Ver mis reservas",
      OPEN_RIDE_REQUEST: "Ver mis solicitudes",
      PENDING_PAYMENT_COMPENSATION: "Ver pagos y devoluciones",
    } as Record<string, string>,
    blockerFallbackAction: "Ver mi actividad",
    confirmTitle: "Confirma la eliminación",
    confirmLabel: "Escribe ELIMINAR para confirmar",
    confirmPlaceholder: "ELIMINAR",
    confirmHelper: "Escríbelo en mayúsculas, tal cual.",
    confirmError: "Escribe la palabra ELIMINAR para confirmar.",
    reasonLabel: "¿Por qué te vas? (opcional)",
    reasonPlaceholder: "Tu opinión nos ayuda a mejorar...",
    reasonTooLong: "El motivo no puede tener más de 500 caracteres.",
    submit: "Solicitar eliminación",
    submitting: "Solicitando…",
    finalConfirmTitle: "¿Seguro que quieres eliminar tu cuenta?",
    finalConfirmMessage: (date: string) =>
      `Tu cuenta se eliminará el ${date} si no la cancelas antes. Hasta entonces puedes seguir usando MVC.`,
    finalConfirm: "Sí, eliminar mi cuenta",
    scheduledTitle: "Eliminación programada",
    scheduledMessage: (date: string) => `Tu cuenta se eliminará el ${date}. Hasta entonces puedes usar MVC con normalidad o cancelar la eliminación.`,
    scheduledToast: "Eliminación programada",
    cancel: "Cancelar eliminación",
    cancelling: "Cancelando…",
    cancelledToast: "Eliminación cancelada: tu cuenta sigue como siempre",
    cancelledTitle: "Has cancelado la eliminación",
    cancelledMessage: "Tu cuenta sigue activa. Si cambias de idea, puedes solicitarla de nuevo cuando quieras.",
    blockedRequestTitle: "Tu solicitud está en pausa",
    blockedRequestMessage:
      "Hay algo pendiente que impide eliminar la cuenta. No has perdido tu solicitud: se ejecutará en cuanto lo resuelvas, o puedes cancelarla.",
    processingTitle: "Estamos eliminando tu cuenta",
    processingMessage: "El proceso ya ha empezado y no se puede cancelar. Cerraremos tu sesión cuando termine.",
    inProgressError: "El proceso de eliminación ya ha empezado y no se puede cancelar.",
    loadErrorTitle: "No hemos podido comprobar tu cuenta",
    loadErrorMessage: "Necesitamos comprobar si hay algo pendiente antes de dejarte continuar.",
    guestMessage: "Para eliminar una cuenta hace falta haber entrado en ella.",
  },

  // ── Información legal ──────────────────────────────────────────────────────────────────────────────────────────
  legal: {
    centerTitle: "Información legal",
    centerIntro: "Los textos que rigen el uso de MVC. Aquí ves siempre la versión vigente, con su número y su fecha.",
    documentTitle: "Documento legal",
    kindTitles: {
      terms: "Términos y condiciones de uso",
      privacy: "Política de privacidad",
      cancellation: "Política de cancelación",
      private_check_notice: "Privacidad de la comprobación",
    } as Record<string, string>,
    kindSubtitles: {
      terms: "Las reglas para usar MVC",
      privacy: "Cómo tratamos tus datos",
      cancellation: "Cuándo y cómo se puede cancelar una reserva",
      private_check_notice: "Qué hacemos con tus fotos de comprobación",
    } as Record<string, string>,
    version: (n: number) => `Versión ${n}`,
    pendingPill: "Pendiente de revisión jurídica",
    effectivePill: "Vigente",
    retiredPill: "Retirada",
    pendingBannerTitle: "Texto pendiente de revisión jurídica",
    pendingBannerMessage:
      "Este texto todavía no ha sido revisado por el equipo jurídico de MVC y no tiene validez legal hasta que se publique su versión definitiva.",
    effectiveFrom: (date: string) => `Vigente desde el ${date}`,
    publishedAt: (date: string) => `Publicado el ${date}`,
    noDate: "Sin fecha de publicación",
    emptySectionsTitle: "Este documento aún no tiene contenido",
    emptySectionsMessage: "Cuando se publique el texto lo verás aquí.",
    loadErrorTitle: "No hemos podido cargar el documento",
    listErrorTitle: "No hemos podido cargar los documentos",
    notFoundTitle: "No encontramos este documento",
    notFoundMessage: "Puede que esa versión ya no esté disponible. Mira la lista de documentos vigentes.",
    notFoundAction: "Ver documentos",
    helpLink: "¿Dudas sobre estos textos? Escríbenos desde el Centro de ayuda",
  },

  // ── 36 · Si algo no va bien / Estado del servicio ──────────────────────────────────────────────────────────────
  status: {
    title: "Si algo no va bien",
    kindOffline: {
      title: "Sin conexión",
      message: "No tenemos Internet en este momento. Comprueba tu conexión y vuelve a intentarlo.",
      action: "Reintentar",
    },
    kindServer: {
      title: "Servidor no disponible",
      message: "No podemos comunicarnos con MVC en este momento. Inténtalo de nuevo en unos minutos.",
      action: "Reintentar",
    },
    noSeatsAction: "Buscar otra ruta",
    outOfProvinceAction: "Cambiar destino",
    paymentAction: "Reintentar pago",
    gpsAction: "Ver última actualización",
    serviceSection: "Estado del servicio",
    serviceIntro: "Esto es lo que podemos comprobar desde tu móvil ahora mismo.",
    checking: "Comprobando…",
    recheck: "Comprobar de nuevo",
    lastCheck: (when: string) => `Última comprobación: ${when}`,
    rows: {
      device: "Tu conexión a Internet",
      server: "Servidor de MVC",
      database: "Base de datos",
      location: "Ubicación del móvil",
    },
    device: {
      online: "Conectado",
      offline: "Sin conexión",
      wifi: "Conectado por Wi-Fi",
      cellular: "Conectado por datos móviles",
    },
    serverState: {
      ok: "Responde con normalidad",
      down: "No responde",
      checking: "Comprobando…",
      unknown: "Sin comprobar",
    },
    databaseState: {
      ready: "Preparada",
      notReady: "No está lista",
      checking: "Comprobando…",
      unknown: "Sin comprobar",
    },
    locationState: {
      granted: "Permitida y disponible",
      denied: "Sin permitir",
      blocked: "Bloqueada en el móvil",
      unavailable: "No disponible",
      gpsOff: "Sin señal GPS",
      checking: "Comprobando…",
    },
    summaryOk: "Todo lo que podemos comprobar responde con normalidad.",
    summaryOffline: "Tu móvil no tiene Internet. Es lo primero que hay que arreglar.",
    summaryServer: "El servidor de MVC no responde. No es un problema de tu móvil: vuelve a intentarlo en unos minutos.",
    summaryDatabase: "El servidor responde, pero su base de datos no está lista. Algunas pantallas pueden fallar un rato.",
    limits: "MVC no publica por ahora el estado de cada módulo (pagos, mensajes, mapa…). Solo mostramos lo que se puede comprobar de verdad.",
    stillBroken: "¿Sigue sin funcionar?",
    stillBrokenMessage: "Cuéntanos qué te pasa y lo miramos.",
    stillBrokenAction: "Escribir al equipo de ayuda",
    locationSheetTitle: "Última ubicación conocida",
    locationSheetNone: "Todavía no tenemos ninguna ubicación de este móvil.",
    locationSheetAge: (when: string) => `Última actualización: ${when}`,
    locationSheetAccuracy: (m: number) => `Precisión aproximada: ${m} m`,
    locationSheetRefresh: "Actualizar ahora",
    locationSheetRefreshing: "Buscando señal GPS…",
    locationSheetFresh: "Ubicación actualizada",
    locationSheetFailed: "No hemos podido obtener tu ubicación. Comprueba que el GPS está activado y que estás en un sitio con buena señal.",
    locationSheetDenied: "MVC no tiene permiso para usar tu ubicación.",
    locationSheetBlocked: "El permiso de ubicación está bloqueado. Puedes activarlo en los ajustes del móvil.",
    locationSheetSettings: "Abrir ajustes del móvil",
    locationSheetAllow: "Permitir ubicación",
    guestPayment: "Para revisar tus métodos de pago necesitas una cuenta.",
  },

  // ── Acerca de MVC ──────────────────────────────────────────────────────────────────────────────────────────────
  about: {
    title: "Acerca de MVC",
    name: "MVC · Me voy contigo",
    tagline: "Tu provincia, en movimiento.",
    description: "Comparte coche dentro de tu provincia: viajes recurrentes, plazas, pagos y mensajes en la app.",
    versionLabel: "Versión de la app",
    platformLabel: "Dispositivo",
    serverLabel: "Servidor",
    province: "Disponible por ahora en la provincia de Sevilla.",
    rowLegal: "Información legal",
    rowHelp: "Centro de ayuda",
    rowStatus: "Estado del servicio",
    copyInfo: "Copiar datos para soporte",
    copied: "Datos copiados",
    copyHeader: "MVC · datos para soporte",
    footer: "© MVC · Me voy contigo",
    platformIos: "iPhone / iPad",
    platformAndroid: "Android",
    platformWeb: "Navegador (vista previa)",
    previewNote: "Vista previa de diseño: los datos son de ejemplo y no existen en producción.",
  },
} as const;

export type HelpStrings = typeof helpStrings;
