/**
 * Textos del slice `auth` (es-ES). Los literales de las láminas 01–08 se copian TAL CUAL; los de las páginas sin lámina
 * (entrar, otra forma de verificar, aceptación legal, permisos) siguen la misma voz: frases cortas, tuteo, sin jerga.
 *
 * Regla de producto: nada de promesas que el servidor no confirme (revisión humana, sin biometría facial, «por definir»).
 */

export const authStrings = {
  steps: {
    /** Welcome (1) → ChooseRole (2) → CreateAccount (3) → VerifyPhone (4). */
    total: 4,
    label: (step: number, total: number): string => `Paso ${step} de ${total}`,
  },

  welcome: {
    headlineTop: "Tu provincia,",
    headlineBottom: "en movimiento.",
    subtitle: "Comparte coche para tus trayectos habituales.",
    createAccount: "Crear cuenta",
    signIn: "Entrar",
    explore: "Explorar sin registrarme",
    sessionExpiredTitle: "Sesión caducada",
    sessionExpired: "Tu sesión ha caducado. Vuelve a entrar.",
    inactiveTitle: "Cuenta no activa",
    inactive: "Tu cuenta no está activa. Si crees que es un error, escríbenos desde el Centro de ayuda.",
  },

  role: {
    title: "Elige tu perfil",
    subtitleTop: "Indica cómo quieres usar MVC.",
    subtitleBottom: "Puedes activar ambos más adelante.",
    passengerTitle: "Soy pasajero",
    passengerText: "Encuentra coche para tus trayectos habituales.",
    driverTitle: "Soy conductor",
    driverText: "Ofrece plazas libres en tus trayectos.",
    info: "Puedes activar ambos perfiles en tu cuenta cuando quieras.",
    continue: "Continuar",
    pickOne: "Elige al menos un perfil para continuar.",
    selected: "Seleccionado",
    notSelected: "No seleccionado",
    saving: "Guardando tu perfil…",
    saveFailedTitle: "No hemos podido guardar tu perfil",
    stillIncomplete: "Perfil guardado. Aún falta completar tu alta.",
    offlineSave: "Sin conexión. Conéctate para guardar tu perfil.",
    switchAccount: "Usar otra cuenta",
  },

  create: {
    title: "Tu cuenta",
    subtitle: "Completa tus datos para crear tu cuenta.",
    givenName: "Nombre",
    familyName: "Apellidos",
    phone: "Número de móvil",
    province: "Provincia",
    provincePlaceholder: "Elige tu provincia",
    provinceSheet: "Provincia",
    consentPrefix: "Acepto la ",
    privacyLink: "Política de Privacidad",
    consentMiddle: " y los ",
    termsLink: "Términos de Uso",
    consentSuffix: ".",
    consentA11y: "Acepto la Política de Privacidad y los Términos de Uso",
    submit: "Recibir código",
    photoAdd: "Añadir foto de perfil",
    photoChange: "Cambiar foto de perfil",
    photoSheetTitle: "Foto de perfil",
    photoTake: "Hacer foto",
    photoPick: "Elegir de la galería",
    photoRemove: "Quitar foto",
    photoOptional: "Puedes añadir la foto ahora o en el siguiente paso.",
    errors: {
      givenNameRequired: "Escribe tu nombre.",
      givenNameShort: "El nombre debe tener al menos 2 letras.",
      givenNameLong: "El nombre es demasiado largo (máximo 40 caracteres).",
      familyNameRequired: "Escribe tus apellidos.",
      familyNameShort: "Los apellidos deben tener al menos 2 letras.",
      familyNameLong: "Los apellidos son demasiado largos (máximo 40 caracteres).",
      fullNameLong: "Nombre y apellidos no pueden superar los 80 caracteres.",
      nameChars: "Usa solo letras, espacios, guiones y apóstrofos.",
      phoneRequired: "Escribe tu número de móvil.",
      phoneInvalid: "Introduce un número de móvil válido (por ejemplo, 612 345 678).",
      phoneNotSpanishMobile: "Introduce un móvil español (empieza por 6 o 7).",
      provinceRequired: "Elige tu provincia.",
      consentRequired: "Para crear tu cuenta debes aceptar la Política de Privacidad y los Términos de Uso.",
      photoInvalid: "Esa imagen no se puede usar.",
    },
    provincesLoading: "Cargando provincias…",
    provincesErrorTitle: "No hemos podido cargar las provincias",
    provincesEmpty: "Aún no hay provincias disponibles.",
    sendFailedTitle: "No hemos podido enviar el código",
    smsUnavailableTitle: "SMS no disponible",
    smsUnavailable: "Ahora mismo no podemos enviar SMS. Inténtalo de nuevo más tarde.",
    resendTooSoon: "Ya te hemos enviado un código. Espera un momento antes de pedir otro.",
    openingLegal: "Abriendo documento…",
  },

  verify: {
    title: "Confirma tu móvil",
    sentTo: "Hemos enviado un código de 6 dígitos a",
    codeLabel: "Código de verificación",
    wrongCode: "Código incorrecto: inténtalo de nuevo.",
    expiredCode: "El código ha caducado. Solicita uno nuevo.",
    tooManyAttempts: "Has superado el número de intentos. Solicita un código nuevo.",
    challengeGone: "La verificación ha caducado o ya no es válida. Solicita un código nuevo.",
    attemptsLeft: (left: number): string => (left === 1 ? "Te queda 1 intento." : `Te quedan ${left} intentos.`),
    resendIn: "Puedes reenviar el código en",
    resendReady: "Ya puedes pedir un código nuevo.",
    resend: "Reenviar código",
    resendWait: (clock: string): string => `Podrás pedir otro código en ${clock}.`,
    resentToast: "Te hemos enviado un código nuevo.",
    or: "o",
    changePhone: "Cambiar número de móvil",
    verify: "Verificar",
    verifying: "Comprobando el código…",
    creatingAccount: "Creando tu cuenta…",
    finishing: "Terminando de preparar tu cuenta…",
    followUpFailedTitle: "Tu móvil está verificado",
    followUpFailed: "No hemos podido guardar todos tus datos. Puedes reintentarlo o entrar ahora y completarlos después.",
    retrySave: "Reintentar",
    enterAnyway: "Entrar ahora",
    smsUnavailableTitle: "SMS no disponible",
    sessionRejected: "No hemos podido abrir tu sesión. Inténtalo de nuevo.",
    accountInactive: "Tu cuenta no está activa. Si crees que es un error, escríbenos desde el Centro de ayuda.",
    noChallengeTitle: "Necesitamos tu número de móvil",
    noChallengeMessage: "Esta verificación ya no está activa. Vuelve a pedir un código.",
    noChallengeAction: "Pedir un código",
    simulationNote: "Simulación: el SMS de esta vista previa llega al panel del visor.",
  },

  signIn: {
    title: "Entrar",
    subtitle: "Te enviaremos un código por SMS a tu móvil.",
    phone: "Número de móvil",
    submit: "Recibir código",
    or: "o",
    createAccount: "Crear una cuenta nueva",
    note: "Si este móvil aún no tiene cuenta, te llevaremos a crearla.",
    explore: "Explorar sin registrarme",
    sendFailedTitle: "No hemos podido enviar el código",
  },

  photo: {
    title: "Tu foto de perfil",
    chooseRole: "Elige tu rol (puedes tener ambos)",
    driver: "Conductor",
    passenger: "Pasajero",
    requiredTitle: "Obligatoria para ambos perfiles.",
    required: "Tu foto ayuda a generar confianza en la comunidad.",
    tipsTitle: "Consejos para una buena foto",
    tips: ["Rostro visible y sin gafas de sol", "Buena iluminación", "Solo tú en la imagen"] as readonly string[],
    take: "Hacer foto",
    pick: "Elegir foto",
    save: "Guardar",
    saving: "Subiendo tu foto…",
    change: "Cambiar foto",
    avatarBadge: "Cambiar foto",
    checkStatus: "Comprobar estado",
    continue: "Continuar",
    signOut: "Cerrar sesión",
    inReviewTitle: "Tu foto está en revisión",
    inReview: "Una persona del equipo de MVC la revisa. Te avisaremos cuando esté lista.",
    approvedTitle: "Foto aprobada",
    approved: "Ya es visible para otras personas en los trayectos.",
    rejectedTitle: "No hemos podido aprobar tu foto",
    rejectedFallback: "Elige otra foto e inténtalo de nuevo.",
    stillReviewing: "Seguimos revisando tu foto. Te avisaremos cuando esté lista.",
    uploadUnavailableTitle: "Subida no disponible",
    uploadUnavailable: "Ahora mismo no podemos recibir fotos. Inténtalo de nuevo más tarde.",
    pickedHint: "Foto elegida. Pulsa «Guardar» para enviarla.",
    needPhoto: "Elige o haz una foto para continuar.",
    roleSaveFailed: "No hemos podido guardar tu rol. Inténtalo de nuevo.",
    roleOneRequired: "Necesitas al menos un rol.",
    stateLabel: {
      none: "Sin foto",
      in_review: "En revisión",
      approved: "Aprobada",
      rejected: "No aprobada",
    } as const,
    permission: {
      cameraBlockedTitle: "La cámara está desactivada",
      cameraBlocked: "Actívala en los ajustes del móvil o elige una foto de tu galería.",
      openSettings: "Abrir ajustes",
      cameraUnavailable: "No hemos podido abrir la cámara. Elige una foto de tu galería.",
      galleryUnavailable: "No hemos podido abrir tu galería. Inténtalo de nuevo.",
    },
    loadFailedTitle: "No hemos podido cargar tu foto",
  },

  upload: {
    notAllowed: "Ese formato no está permitido. Usa JPG, PNG, WebP o HEIC.",
    notAllowedDocument: "Ese formato no está permitido. Usa JPG, PNG, WebP o PDF.",
    tooLargePhoto: "La imagen supera el límite de 10 MB.",
    tooLargeDocument: "El archivo supera el límite de 20 MB.",
    empty: "El archivo está vacío.",
    sizeUnknown: "No hemos podido calcular el tamaño del archivo.",
    failed: "No se ha podido subir el archivo. Comprueba tu conexión e inténtalo de nuevo.",
  },

  check: {
    title: "Comprobación privada",
    framePill: "Centra tu rostro",
    steps: [
      "Busca un lugar con buena luz",
      "Sitúa tu rostro dentro del marco",
      "Mantén la mirada al frente",
      "Pulsa para iniciar la captura",
    ] as readonly string[],
    infoTitle: "La selfie no acredita por sí sola tu identidad.",
    infoText: "Se utiliza solo para la comprobación.",
    start: "Iniciar",
    otherWay: "Otra forma de verificar",
    loadFailedTitle: "No hemos podido cargar la comprobación",
    inReviewTitle: "Comprobación en revisión",
    inReview: "Una persona del equipo de MVC la revisa. No hay reconocimiento facial automático.",
    completedTitle: "Comprobación completada",
    completed: "Gracias. Tu captura ya se ha revisado.",
    rejectedTitle: "No hemos podido completar la comprobación",
    rejected: "Puedes verificar tu identidad aportando un documento.",
    maxAttempts: "Has usado los 3 intentos con foto. Puedes verificar tu identidad aportando un documento.",
    retryTitle: "Necesitamos otra captura",
    attempts: (used: number, max: number): string => `Intentos: ${used} de ${max}`,
    uploadUnavailableTitle: "Subida no disponible",
    uploadUnavailable: "Ahora mismo no podemos recibir capturas. Inténtalo de nuevo más tarde.",
    cameraBlockedTitle: "La cámara está desactivada",
    cameraBlocked: "Actívala en los ajustes del móvil o verifica tu identidad con un documento.",
    cameraUnavailable: "No hemos podido abrir la cámara. Puedes verificar tu identidad con un documento.",
    openSettings: "Abrir ajustes",
    alreadyInReview: "Tu comprobación ya está en revisión.",
    alreadyCompleted: "Tu comprobación ya está completada.",
  },

  privacy: {
    title: "Privacidad de la comprobación",
    heading: "Tus fotos, usos y privacidad",
    publicPhotoTitle: "Foto visible en tu perfil",
    publicPhotoText: "La ven otros usuarios para generar confianza en los trayectos.",
    privateCheckTitle: "Comprobación privada",
    privateCheckText: "Solo la ve el equipo de MVC para revisar tu cuenta.",
    usesTitle: "Qué se usa y para qué",
    retentionTitle: "Conservación y proveedor: por definir",
    retentionText: "El tiempo de conservación y el proveedor del servicio se definirán en próximas fases.",
    otherWayTitle: "Otra forma de verificar",
    otherWayText: "Puedes aportar un documento de identidad.",
    consent: "He leído y acepto el uso de mi foto según esta información.",
    continue: "Continuar",
    consentRequired: "Acepta la información para continuar.",
    pendingLegal: "Texto pendiente de revisión jurídica",
    noticeVersion: (version: number): string => `Versión ${version}`,
    loadFailedTitle: "No hemos podido cargar la información",
    sending: "Enviando tu captura…",
    noPhotoTitle: "Falta tu captura",
    noPhotoMessage: "Haz la captura de la comprobación para continuar.",
    noPhotoAction: "Hacer la captura",
    uploadFailedTitle: "No hemos podido enviar tu captura",
  },

  status: {
    title: "Estado de la comprobación",
    steps: { in_review: "En revisión", retry: "Repetir", completed: "Completada" } as const,
    tipsTitle: "Consejos para mejorar la foto",
    tips: [
      "Rostro completo dentro del marco",
      "Buena iluminación",
      "Sin gafas de sol",
      "Solo tú en la imagen",
    ] as readonly string[],
    retry: "Repetir captura",
    help: "Pedir ayuda",
    otherWay: "Otra forma de verificar",
    refresh: "Actualizar estado",
    inReviewTitle: "Tu captura está en revisión",
    inReview: "Una persona del equipo de MVC la revisa. Te avisaremos cuando haya novedades.",
    completedTitle: "Comprobación completada",
    completed: "Gracias. Tu comprobación privada ya está revisada.",
    completedNote: "La selfie no acredita por sí sola tu identidad.",
    rejectedFallbackTitle: "No hemos podido completar la comprobación",
    notStartedTitle: "Aún no has empezado la comprobación",
    notStartedMessage: "Haz tu captura para que el equipo pueda revisarla.",
    notStartedAction: "Empezar",
    loadFailedTitle: "No hemos podido cargar el estado",
    thumbnailA11y: "Tu captura, desenfocada",
    attemptsA11y: (used: number, max: number): string => `Has usado ${used} de ${max} intentos`,
  },

  otherWay: {
    title: "Otra forma de verificar",
    heading: "Verifica tu identidad con un documento",
    intro: "Puedes aportar una foto o un PDF de tu documento de identidad. Una persona del equipo de MVC lo revisa.",
    reasonSelfieFailed: "La selfie no ha podido completarse. Con un documento de identidad puedes seguir adelante.",
    cardTitle: "Documento de identidad",
    cardText: "DNI, NIE o pasaporte. JPG, PNG, WebP o PDF, hasta 20 MB.",
    take: "Hacer foto del documento",
    pick: "Elegir imagen o PDF",
    chosen: "Archivo elegido",
    send: "Enviar documento",
    sending: "Enviando tu documento…",
    replace: "Elegir otro archivo",
    privacyTitle: "Quién lo ve y cuánto se conserva",
    privacyText: "Solo lo ve el equipo de MVC para revisar tu cuenta. No se muestra a otras personas.",
    retention: "Conservación y proveedor: por definir",
    retentionText: "El tiempo de conservación y el proveedor del servicio se definirán en próximas fases.",
    inReviewTitle: "Tu documento está en revisión",
    inReview: "Una persona del equipo de MVC lo revisa. Te avisaremos cuando esté listo.",
    approvedTitle: "Identidad verificada",
    approved: "Un documento de identidad aprobado por el equipo de MVC acredita tu identidad.",
    rejectedTitle: "No hemos podido validar tu documento",
    rejectedFallback: "Prueba con otra foto o archivo más nítido.",
    alreadyVerified: "Tu identidad ya está verificada. No necesitas hacer nada más.",
    documentInReview: "Ya hay un documento tuyo en revisión.",
    storageUnavailableTitle: "Subida no disponible",
    storageUnavailable: "Ahora mismo no podemos recibir documentos. Inténtalo de nuevo más tarde.",
    loadFailedTitle: "No hemos podido cargar tu verificación",
    needFile: "Elige un documento para enviarlo.",
    back: "Volver",
    cameraBlockedTitle: "La cámara está desactivada",
    cameraBlocked: "Actívala en los ajustes del móvil o elige un archivo de tu móvil.",
    openSettings: "Abrir ajustes",
    cameraUnavailable: "No hemos podido abrir la cámara. Elige un archivo de tu móvil.",
    pickerUnavailable: "No hemos podido abrir tus archivos. Inténtalo de nuevo.",
    tooLarge: "El archivo supera el límite de 20 MB.",
    statusLabel: { in_review: "En revisión", approved: "Aprobado", rejected: "No válido" } as const,
  },

  legal: {
    title: "Condiciones y privacidad",
    intro: "Para seguir usando MVC necesitamos que aceptes la versión vigente de estos documentos.",
    pendingReviewTitle: "Pendiente de revisión jurídica",
    pendingReview: "Este texto es un borrador estructural sin validez legal hasta que Legal lo revise y publique.",
    pendingBadge: "Pendiente de revisión jurídica",
    version: (version: number): string => `Versión ${version}`,
    date: (text: string): string => `Vigente desde ${text}`,
    noDate: "Sin fecha de entrada en vigor",
    read: "Leer documento",
    hide: "Ocultar documento",
    consent: "He leído y acepto los documentos indicados en su versión vigente.",
    accept: "Aceptar y continuar",
    accepting: "Guardando tu aceptación…",
    acceptedTitle: "Todo al día",
    acceptedMessage: "Ya has aceptado la versión vigente de los documentos.",
    done: "Continuar",
    consentRequired: "Acepta los documentos para continuar.",
    loadFailedTitle: "No hemos podido cargar los documentos",
    acceptFailedTitle: "No hemos podido guardar tu aceptación",
    outdated: "Ha salido una versión más reciente. Actualizamos los documentos; léelos y acepta de nuevo.",
    retired: "Uno de los documentos ya no está vigente. Actualizamos la lista.",
    emptyTitle: "No falta nada por aceptar",
    emptyMessage: "Ya has aceptado la versión vigente de las condiciones y la política de privacidad.",
    kinds: {
      terms: "Términos y condiciones de uso",
      privacy: "Política de privacidad",
      cancellation: "Política de cancelación",
      private_check_notice: "Privacidad de la comprobación",
    } as const,
    sectionsEmpty: "Este documento aún no tiene contenido.",
    guestTitle: "Necesitas una cuenta",
    guestMessage: "Crea una cuenta o entra para aceptar las condiciones.",
  },

  permission: {
    titles: {
      location: "Usar tu ubicación",
      notifications: "Recibir avisos",
      camera: "Usar la cámara",
      photos: "Elegir una foto",
    } as const,
    messages: {
      location: "Te sugerimos tu municipio y mostramos los coches cercanos. Puedes buscar sin activarla.",
      notifications: "Te avisamos de cambios de hora, recogidas y mensajes. Puedes elegir cuáles en Ajustes.",
      camera: "La necesitamos para hacer tu foto de perfil y la comprobación privada. Si prefieres, puedes elegir una foto de tu galería.",
      photos: "Selecciona una imagen de tu galería. Solo accedemos a la que elijas. Si lo prefieres, puedes hacer una foto.",
    } as const,
    skip: {
      location: "Buscar sin ubicación",
      notifications: "Ahora no",
      camera: "Ahora no",
      photos: "Ahora no",
    } as const,
    allow: "Permitir",
    deniedMessage: {
      location: "Sin tu ubicación no podemos sugerirte municipio ni coches cercanos, pero puedes buscar escribiendo el origen.",
      notifications: "No te avisaremos de cambios de hora ni de mensajes. Puedes activarlos más tarde en los ajustes del móvil.",
      camera: "Sin la cámara puedes elegir una foto de tu galería o verificar tu identidad con un documento.",
      photos: "No hemos podido abrir tus fotos. Inténtalo de nuevo o haz una foto con la cámara.",
    } as const,
    blockedTitle: "Permiso desactivado en el móvil",
    blockedMessage: {
      location: "Actívalo en los ajustes del móvil para ver los coches cercanos. Mientras tanto puedes buscar sin ubicación.",
      notifications: "Actívalos en los ajustes del móvil para recibir cambios de hora, recogidas y mensajes.",
      camera: "Actívala en los ajustes del móvil o elige una foto de tu galería.",
      photos: "Actívalo en los ajustes del móvil o haz una foto con la cámara.",
    } as const,
    grantedTitle: "Permiso concedido",
    grantedMessage: "Ya puedes continuar.",
    unavailableTitle: "No disponible en este dispositivo",
    unavailableMessage: "Este dispositivo no ofrece esta función. Puedes continuar sin ella.",
    continue: "Continuar",
    checking: "Comprobando el permiso…",
    simulationNote: "Simulación: el diálogo del sistema lo muestra el visor.",
  },

  common: {
    retry: "Reintentar",
    back: "Volver",
    close: "Cerrar",
    cancel: "Cancelar",
    offlineTitle: "Sin conexión",
    offlineDetail: "Conéctate para continuar",
    serverDownTitle: "No hemos podido conectar",
    serverDown: "Inténtalo de nuevo en unos minutos.",
    unknown: "Ha ocurrido un error inesperado. Inténtalo de nuevo.",
    loading: "Cargando…",
    guestTitle: "Necesitas una cuenta",
    guestMessage: "Crea una cuenta o entra para continuar.",
    createAccount: "Crear cuenta",
    signIn: "Entrar",
  },
} as const;

export type AuthStrings = typeof authStrings;
