/**
 * Textos del slice `profile` (es-ES): Mi perfil, Mis viajes, Favoritos y rutina, Planes y las pantallas de apoyo
 * (editar perfil, verificación, detalle de reserva y reserva semanal).
 *
 * Los literales de las láminas 29–32 se copian TAL CUAL («Móvil verificado», «Plaza disponible (semanal)»…). Lo demás sigue
 * la voz de las láminas: frases cortas, tuteo, sin tecnicismos. Los importes nunca se escriben aquí: salen del servidor
 * (`Money`) y, mientras la economía no esté definida, se muestran como «Por definir».
 */
import { NBSP, pluralize } from "@/i18n";

export const profileStrings = {
  common: {
    retry: "Reintentar",
    cancel: "Cancelar",
    close: "Cerrar",
    save: "Guardar",
    saving: "Guardando…",
    edit: "Editar",
    done: "Listo",
    delete: "Eliminar",
    back: "Volver",
    seeAll: "Ver todos",
    keep: "Mantener",
    loadMore: "Ver más",
    refreshFailed: "No hemos podido actualizar. Mostramos lo último que teníamos.",
    notFoundTitle: "No encontramos esto",
    unavailable: "No disponible",
    guestTitle: "Necesitas una cuenta",
    guestMessage: "Crea tu cuenta o entra para ver esta pantalla.",
    guestAction: "Crear cuenta",
  },

  // ───────────────────────────── 29 · Mi perfil ─────────────────────────────
  myProfile: {
    title: "Mi perfil",
    unnamed: "Tu perfil",
    openProfileHint: "Abre tu perfil para editarlo",
    ratingCount: (count: number): string => `(${count}${NBSP}${count === 1 ? "valoración" : "valoraciones"})`,
    ratingA11y: (average: string, count: number): string =>
      `Valoración media ${average} sobre 5, ${count} ${count === 1 ? "valoración" : "valoraciones"}`,
    provinceOnly: (province: string): string => province,
    phoneVerifiedTitle: "Móvil verificado",
    phoneVerifiedMessage: "Tu número está confirmado",
    phoneVerifiedHint: "Abre tu estado de verificación",
    verifyAction: {
      photoMissing: { title: "Falta tu foto de perfil", message: "Súbela para que otras personas te reconozcan." },
      photoRejected: { title: "Tu foto necesita un cambio", message: "Sube otra foto para completar tu perfil." },
      checkRetry: { title: "Repite la comprobación privada", message: "Necesitamos otra captura para revisarla." },
      checkRejected: { title: "Comprobación privada rechazada", message: "Puedes verificarte de otra forma." },
      identityRejected: { title: "Documento rechazado", message: "Revisa el motivo y sube otro documento." },
      review: { title: "Estamos revisando tu verificación", message: "Te avisaremos en cuanto haya novedades." },
      open: "Ver detalles",
    },
    rolesHeading: "Mis roles en MVC",
    passenger: { title: "Pasajero", subtitle: "Busco plaza" },
    driver: { title: "Conductor", subtitle: "Ofrezco plazas" },
    roleActive: "Modo activo",
    roleSwitchHint: "Cambia el modo con el que usas MVC",
    roleSwitched: (role: "passenger" | "driver"): string =>
      role === "driver" ? "Ahora usas MVC como conductor." : "Ahora usas MVC como pasajero.",
    activate: {
      driver: {
        title: "¿Quieres ofrecer plazas?",
        message: "Activaremos el modo conductor en tu cuenta. Después podrás añadir tu vehículo y publicar rutas.",
        confirm: "Activar modo conductor",
      },
      passenger: {
        title: "¿Quieres buscar plaza?",
        message: "Activaremos el modo pasajero en tu cuenta para que puedas pedir plaza en los viajes de otras personas.",
        confirm: "Activar modo pasajero",
      },
      vehicle: {
        title: "Para añadir un vehículo necesitas el modo conductor",
        message: "Lo activamos ahora y seguimos con tu vehículo. Podrás volver al modo pasajero cuando quieras.",
        confirm: "Activar y continuar",
      },
      done: (role: "passenger" | "driver"): string => (role === "driver" ? "Modo conductor activado." : "Modo pasajero activado."),
    },
    dataHeading: "Mis datos",
    editProfile: { title: "Editar perfil", subtitle: "Foto, nombre y preferencias" },
    vehicle: { title: "Mi vehículo", subtitle: "Añade o edita tu vehículo" },
    privacy: { title: "Privacidad", subtitle: "Quién puede ver tu información" },
    verification: {
      title: "Verificación y seguridad",
      subtitleLoading: "Foto, comprobación privada y documentos",
      subtitleOk: "Todo en orden",
      subtitleReview: "En revisión",
      subtitleAction: "Hay algo pendiente",
    },
    activityHeading: "Mi actividad",
    trips: { title: "Mis viajes", subtitle: "Próximos, en curso e historial" },
    favorites: { title: "Favoritos y rutina", subtitle: "Tus destinos y tu semana tipo" },
    accountHeading: "Cuenta",
    plans: { title: "Planes MVC", subtitle: "Cuenta gratuita y propuestas" },
    payments: { title: "Pagos y cobros", subtitle: "Importes, recibos y devoluciones" },
    settings: { title: "Ajustes", subtitle: "Notificaciones, tamaño de letra y más" },
    help: { title: "Centro de ayuda", subtitle: "Preguntas frecuentes y contacto" },
    stale: "Mostramos los datos guardados de tu perfil. Se actualizarán al recuperar la conexión.",
    loadErrorTitle: "No hemos podido cargar tu perfil",
    loadErrorMessage: "Comprueba tu conexión e inténtalo de nuevo.",
    noProfileTitle: "Tu perfil aún no está disponible",
    noProfileMessage: "Estamos terminando de preparar tu cuenta. Inténtalo de nuevo en unos segundos.",
  },

  // ───────────────────────────── 30 · Mis viajes ─────────────────────────────
  myTrips: {
    title: "Mis viajes",
    tabsLabel: "Secciones de Mis viajes",
    tabUpcoming: "Próximos",
    tabInProgress: "En curso",
    tabHistory: "Historial",
    asPassenger: "Soy pasajero",
    asDriver: "Soy conductor",
    roleSwitchLabel: "Ver mis viajes como",
    weeklyHeading: (count: number): string => (count === 1 ? "Reserva semanal" : "Reservas semanales"),
    driverSeriesHeading: (count: number): string => (count === 1 ? "Ruta semanal" : "Rutas semanales"),
    nextTripHeading: "Próximo viaje",
    moreTripsHeading: "Más viajes",
    inProgressHeading: (count: number): string => (count === 1 ? "Viaje en curso" : "Viajes en curso"),
    historyHeading: "Viajes anteriores",
    startsIn: (minutes: number): string => {
      if (minutes < 1) return "Ahora";
      if (minutes < 60) return `En ${minutes} min`;
      const hours = Math.floor(minutes / 60);
      const rest = minutes % 60;
      return rest === 0 ? `En ${hours} h` : `En ${hours} h ${rest} min`;
    },
    seats: (occupied: number, total: number): string => `${occupied}/${total} plazas`,
    seatsA11y: (occupied: number, total: number): string => `${occupied} de ${total} plazas ocupadas`,
    cardMenu: "Más opciones del viaje",
    cardRiders: (names: readonly string[]): string => (names.length === 0 ? "" : `Con ${names.join(", ")}`),
    etaHint: "Abre el seguimiento del viaje",
    statusHint: "Abre el detalle",
    emptyUpcoming: {
      title: "Aún no tienes viajes próximos",
      message: "Cuando pidas plaza o publiques una ruta, aparecerá aquí.",
      action: "Buscar un viaje",
      driverMessage: "Cuando publiques una ruta, aparecerá aquí con sus solicitudes.",
      driverAction: "Publicar una ruta",
    },
    emptyInProgress: {
      title: "No tienes ningún viaje en curso",
      message: "Cuando empiece un viaje de los tuyos, podrás seguirlo desde aquí.",
    },
    emptyHistory: {
      title: "Todavía no hay viajes en tu historial",
      message: "Los viajes terminados, cancelados o caducados se guardan aquí.",
    },
    loadErrorTitle: "No hemos podido cargar tus viajes",
    stale: "Mostramos lo último que teníamos. Se actualizará al recuperar la conexión.",
    moreError: "No hemos podido cargar más viajes.",
    menu: {
      detail: "Ver detalle de la reserva",
      weekly: "Ver reserva semanal",
      series: "Ver mi ruta semanal",
      withdraw: "Retirar solicitud",
      pay: "Ir a pagar",
      cancel: "Cancelar reserva",
      follow: "Seguir el viaje",
      manage: "Gestionar viaje",
      requests: "Ver solicitudes",
      operate: "Abrir el viaje en curso",
      finished: "Ver resumen del viaje",
    },
    withdraw: {
      title: "¿Retirar la solicitud?",
      message: "Dejarás de esperar la respuesta del conductor. Podrás volver a pedir plaza cuando quieras.",
      confirm: "Retirar solicitud",
      done: "Solicitud retirada.",
    },
  },

  // ───────────────────────────── 31 · Favoritos y rutina ─────────────────────────────
  favorites: {
    title: "Favoritos y rutina",
    destinationsHeading: "Mis destinos",
    add: "Añadir",
    addA11y: "Añadir un destino favorito",
    kinds: { work: "Trabajo", campus: "Campus", home: "Casa", other: "Otro" },
    kindsLabel: "Tipo de destino",
    rowMenu: "Más opciones del destino",
    emptyTitle: "Aún no tienes destinos guardados",
    emptyMessage: "Guarda tu trabajo, tu campus o tu casa para pedir plaza en dos toques.",
    emptyAction: "Añadir destino",
    routineHeading: "Mi rutina semanal",
    routineEdit: "Editar",
    routineDone: "Listo",
    routineEditA11y: "Editar mi rutina semanal",
    routineAdd: "Añadir a la rutina",
    routineEmptyTitle: "Todavía no tienes rutina",
    routineEmptyMessage: "Crea tu semana tipo: los días, la hora y el trayecto que repites.",
    routineEmptyAction: "Crear rutina",
    routineNeedPlacesTitle: "Primero guarda dos destinos",
    routineNeedPlacesMessage: "Para crear tu rutina necesitas al menos dos destinos favoritos, por ejemplo Casa y Trabajo.",
    routineNeedPlacesAction: "Añadir destino",
    routeText: (from: string, to: string): string => `${from} → ${to}`,
    rowA11y: (weekday: string, time: string, from: string, to: string, enabled: boolean): string =>
      `${weekday} ${time}, de ${from} a ${to}, ${enabled ? "activa" : "desactivada"}`,
    toggleA11y: (weekday: string): string => `Activar o desactivar el ${weekday.toLowerCase()}`,
    rowMenu2: "Más opciones de la fila",
    suspend: {
      title: "Suspender próxima semana",
      resumedTitle: "Próxima semana suspendida",
      resumedMessage: (range: string): string => `Del ${range}`,
      resume: "Reanudar",
      dialogTitle: "¿Suspender la próxima semana?",
      dialogMessage: (range: string): string =>
        `Del ${range} no pediremos plazas con tu rutina. Las solicitudes pendientes de esa semana se retirarán; las reservas ya aceptadas o confirmadas no se tocan.`,
      dialogConfirm: "Suspender semana",
      done: (withdrawn: number, kept: number): string => {
        const first =
          withdrawn === 0
            ? "Semana suspendida."
            : `Semana suspendida. Hemos retirado ${pluralize(withdrawn, "solicitud pendiente", "solicitudes pendientes")}.`;
        return kept > 0 ? `${first} Mantienes ${pluralize(kept, "reserva aceptada o confirmada", "reservas aceptadas o confirmadas")}.` : first;
      },
      keptAction: "Ver mis reservas",
      resumeDone: "Semana reanudada: tu rutina vuelve a estar activa.",
      resumeA11y: "Reanudar la próxima semana",
    },
    offer: {
      title: "Plaza disponible (semanal)",
      line: (seats: number, days: string): string => `Ofrezco ${pluralize(seats, "plaza")} ${days}`,
      lineOff: "No estás ofreciendo plaza semanal",
      conditions: (label: string): string => `Condiciones y precio: ${label}`,
      sheetTitle: "Plaza disponible (semanal)",
      sheetIntro: "Ofrece plazas fijas en tu ruta de lunes a viernes para que otras personas las reserven por semanas.",
      enabled: "Ofrecer mi plaza cada semana",
      seats: "Plazas que ofreces",
      seatsDown: "Quitar una plaza",
      seatsUp: "Añadir una plaza",
      days: (days: string): string => `Días: ${days}`,
      daysHint: "Se toman de los días activos de tu rutina.",
      priceNote: "La cuota y las condiciones están en fase de estudio. Por ahora no se cobra nada por ofrecer plaza.",
      save: "Guardar",
      publish: "Publicar mi ruta",
      saved: "Plaza semanal guardada.",
      activateTitle: "Para ofrecer plazas necesitas el modo conductor",
      activateMessage: "Lo activamos ahora y seguimos con tu plaza semanal.",
      activateConfirm: "Activar y continuar",
      driverRoleRequired: "Para ofrecer plazas necesitas activar el modo conductor.",
    },
    delete: {
      favoriteTitle: "¿Eliminar este destino?",
      favoriteMessage: (name: string): string => `Se quitará «${name}» de tus favoritos.`,
      entryTitle: "¿Eliminar esta fila de la rutina?",
      entryMessage: (weekday: string, time: string): string => `Se quitará el ${weekday.toLowerCase()} a las ${time} de tu rutina.`,
      confirm: "Eliminar",
      favoriteDone: "Destino eliminado.",
      entryDone: "Fila eliminada.",
      inUseTitle: "Este destino se usa en tu rutina",
      inUseMessage: "Quita primero las filas de la rutina que lo usan y vuelve a intentarlo.",
    },
    toggleFailed: "No hemos podido cambiar la fila. Inténtalo de nuevo.",
    loadErrorTitle: "No hemos podido cargar tus favoritos",
    stale: "Mostramos lo último que teníamos guardado.",
  },

  // ───────────────────────────── Formulario de destino favorito ─────────────────────────────
  favoriteForm: {
    titleNew: "Destino favorito",
    titleEdit: "Editar destino",
    kind: "Tipo",
    name: "Nombre",
    namePlaceholder: "Por ejemplo, Casa de mis padres",
    nameHelper: "Hasta 60 caracteres.",
    place: "Dirección",
    placePlaceholder: "Busca la dirección o el lugar",
    placeSearchTitle: "Dirección del destino",
    placeHelper: "Elige un lugar de tu provincia.",
    save: "Guardar destino",
    saveEdit: "Guardar cambios",
    delete: "Eliminar destino",
    saved: "Destino guardado.",
    updated: "Cambios guardados.",
    validation: {
      nameRequired: "Escribe un nombre para el destino.",
      nameTooLong: "El nombre admite hasta 60 caracteres.",
      placeRequired: "Elige la dirección del destino.",
      addressTooLong: "La dirección es demasiado larga. Elige un lugar más concreto.",
    },
    missingTitle: "Este destino ya no existe",
    missingMessage: "Puede que lo hayas eliminado desde otro dispositivo.",
    limit: "Has llegado al máximo de 20 destinos. Elimina alguno para añadir otro.",
  },

  // ───────────────────────────── Formulario de fila de rutina ─────────────────────────────
  routineForm: {
    titleNew: "Fila de rutina",
    titleEdit: "Editar fila",
    days: "Días",
    daysHelper: "Elige los días en que repites este trayecto.",
    day: "Día",
    time: "Hora de salida",
    timePlaceholder: "Elige la hora",
    from: "Desde",
    to: "Hasta",
    placePlaceholder: "Elige un destino",
    enabled: "Rutina activa",
    enabledHelper: "Si la desactivas, la fila se guarda pero no se usa.",
    save: "Guardar rutina",
    saveEdit: "Guardar cambios",
    swap: "Intercambiar origen y destino",
    saved: "Rutina guardada.",
    updated: "Cambios guardados.",
    validation: {
      daysRequired: "Elige al menos un día.",
      timeRequired: "Elige la hora de salida.",
      fromRequired: "Elige el destino de salida.",
      toRequired: "Elige el destino de llegada.",
      samePlace: "El origen y el destino no pueden ser el mismo lugar.",
    },
    clash: (days: string): string => `Ya tienes ese trayecto a esa hora en: ${days}.`,
    needPlacesTitle: "Primero guarda dos destinos",
    needPlacesMessage: "Para crear una fila de rutina necesitas al menos dos destinos favoritos.",
    needPlacesAction: "Añadir destino",
    missingTitle: "Esta fila ya no existe",
    missingMessage: "Puede que la hayas eliminado desde otro dispositivo.",
    timeSheetTitle: "Hora de salida",
    timeHour: "Hora",
    timeMinute: "Minutos",
    timeConfirm: "Elegir hora",
  },

  // ───────────────────────────── 32 · Planes ─────────────────────────────
  plans: {
    title: "Planes MVC",
    currentPlan: "Tu plan actual",
    proposalTag: "Propuesta",
    unavailableSuffix: "(Propuesta)",
    priceFree: "Gratis",
    pricePending: "Por definir",
    loadErrorTitle: "No hemos podido cargar los planes",
    emptyTitle: "Ahora mismo no hay planes que mostrar",
    emptyMessage: "Vuelve a mirar más tarde.",
    noPurchase: "Por ahora no se puede contratar ningún plan de pago desde la app.",
    stale: "Mostramos los últimos planes que habíamos cargado.",
    featureA11y: (feature: string): string => feature,
  },

  // ───────────────────────────── Editar perfil ─────────────────────────────
  editProfile: {
    title: "Editar perfil",
    photoHeading: "Foto de perfil",
    changePhoto: "Cambiar foto",
    addPhoto: "Añadir foto",
    photoState: {
      none: "Aún no tienes foto de perfil.",
      in_review: "Tu foto está en revisión.",
      approved: "Foto aprobada. Es la que ven otras personas.",
      rejected: "Tu última foto no se pudo aprobar. Sube otra.",
    },
    nameLabel: "Nombre y apellidos",
    nameHelper: "Así te verán otras personas en MVC.",
    nameRequired: "Escribe tu nombre.",
    nameTooShort: "El nombre debe tener al menos 2 caracteres.",
    nameTooLong: "El nombre admite hasta 80 caracteres.",
    save: "Guardar cambios",
    saved: "Cambios guardados.",
    phoneHeading: "Móvil",
    phoneHelper: "Tu número está verificado y no se puede cambiar desde la app.",
    phoneSupport: "Necesito cambiarlo",
    provinceHeading: "Provincia",
    provinceHelper: "MVC funciona dentro de una provincia. Por ahora, Sevilla.",
    preferencesHeading: "Preferencias",
    notifications: { title: "Notificaciones", subtitle: "Viajes, mensajes y novedades" },
    livePrivacy: { title: "Privacidad del viaje en vivo", subtitle: "Qué ve quien viaja contigo" },
    fontSize: { title: "Tamaño de letra y más", subtitle: "En Ajustes" },
    loadErrorTitle: "No hemos podido cargar tu perfil",
    unsaved: "Tienes cambios sin guardar.",
    offlineSave: "Sin conexión: podrás guardar los cambios cuando la recuperes.",
    discardTitle: "¿Salir sin guardar?",
    discardMessage: "Perderás los cambios que has hecho en tu nombre.",
    discardConfirm: "Salir sin guardar",
  },

  // ───────────────────────────── Verificación y seguridad ─────────────────────────────
  verification: {
    title: "Verificación y seguridad",
    intro: "Así de completa está tu cuenta. Lo privado solo lo ve nuestro equipo de revisión.",
    phone: { title: "Móvil", verified: "Verificado", message: "Tu número está confirmado." },
    photo: {
      title: "Foto de perfil",
      none: { tag: "Sin foto", message: "Sube una foto en la que se te vea bien la cara. Es obligatoria para viajar." },
      in_review: { tag: "En revisión", message: "Una persona de nuestro equipo la está revisando." },
      approved: { tag: "Aprobada", message: "Es la foto que ven otras personas." },
      rejected: { tag: "Necesita cambios", message: "No hemos podido aprobar tu foto." },
      actionNone: "Subir foto",
      actionRejected: "Subir otra foto",
      actionReview: "Ver estado",
      actionApproved: "Cambiar foto",
    },
    privateCheck: {
      title: "Comprobación privada",
      notice: "Solo la ve nuestro equipo de revisión, nadie más. No usamos reconocimiento facial.",
      not_started: { tag: "Sin empezar", message: "Es una captura rápida para confirmar que eres tú." },
      in_review: { tag: "En revisión", message: "Una persona de nuestro equipo la está revisando." },
      needs_retry: { tag: "Repetir", message: "Necesitamos otra captura." },
      completed: { tag: "Completada", message: "Comprobación superada." },
      rejected: { tag: "No superada", message: "No hemos podido completarla." },
      attempts: (used: number, max: number): string => `Intentos: ${used} de ${max}`,
      actionStart: "Empezar comprobación",
      actionRetry: "Repetir comprobación",
      actionStatus: "Ver estado",
      actionAlternative: "Otra forma de verificar",
    },
    identity: {
      title: "Identidad y documentos",
      unverified: { tag: "Sin verificar", message: "Un documento de identidad aprobado confirma tu identidad. La selfie por sí sola no basta." },
      pending: { tag: "En revisión", message: "Estamos revisando tu documento." },
      verified: { tag: "Verificada", message: "Tu identidad está verificada." },
      rejected: { tag: "Rechazado", message: "No hemos podido aprobar tu documento." },
      documentKinds: { identity_document: "Documento de identidad", driver_license: "Permiso de conducir" },
      documentStates: { in_review: "En revisión", approved: "Aprobado", rejected: "Rechazado" },
      actionUpload: "Subir un documento",
      actionStatus: "Ver estado",
      driverLicense: "Permiso de conducir",
      noDocuments: "Aún no has subido ningún documento.",
    },
    storageOff: "La subida de fotos y documentos no está disponible ahora mismo. Inténtalo más tarde.",
    loadErrorTitle: "No hemos podido cargar tu verificación",
    stale: "Mostramos lo último que teníamos. Se actualizará al recuperar la conexión.",
    reasonLabel: "Motivo",
  },

  // ───────────────────────────── Detalle de la reserva ─────────────────────────────
  booking: {
    title: "Detalle de la reserva",
    statusBanner: {
      pending: { title: "Esperando al conductor", message: "Te avisaremos en cuanto responda a tu solicitud." },
      accepted: { title: "Solicitud aceptada", message: "Confirma tu plaza antes de que termine el tiempo." },
      payment_pending: { title: "Solicitud aceptada", message: "Confirma tu plaza antes de que termine el tiempo." },
      confirmed: { title: "Reserva confirmada", message: "Tu plaza está reservada." },
      rejected: { title: "Solicitud rechazada", message: "El conductor no ha podido aceptar tu solicitud." },
      expired: { title: "Solicitud caducada", message: "El conductor no respondió a tiempo." },
      cancelled: { title: "Solicitud cancelada", message: "Esta solicitud ya no está activa." },
      payment_late: { title: "Plaza no confirmada", message: "El tiempo para confirmar la plaza terminó." },
    },
    countdown: (text: string): string => `Te quedan ${text} para confirmar la plaza.`,
    tripHeading: "Viaje",
    driverHeading: "Conductor",
    vehicleHeading: "Vehículo",
    plateHint: (hint: string): string => `···· ${hint}`,
    routeHeading: "Recorrido",
    pickup: "Recogida",
    dropoff: "Bajada",
    walk: (minutes: number): string => `${minutes} min a pie`,
    messageHeading: "Tu mensaje al conductor",
    amountHeading: "Importe",
    amountPaid: "Importe de la reserva",
    contribution: "Aportación según recorrido",
    management: "Gestión MVC",
    total: "Total",
    quoteNote: "Los importes se confirman antes de pagar.",
    weeklyHeading: "Reserva semanal",
    weeklyLink: "Esta plaza forma parte de tu reserva semanal",
    actionWithdraw: "Retirar solicitud",
    actionPay: "Confirmar y pagar",
    actionChat: "Escribir al conductor",
    actionCancel: "Cancelar reserva",
    actionFollow: "Seguir el viaje",
    actionShare: "Compartir viaje",
    actionPayment: "Ver el pago",
    actionSearchAgain: "Buscar otro viaje",
    chatError: "No hemos podido abrir el chat. Inténtalo de nuevo.",
    withdraw: {
      title: "¿Retirar la solicitud?",
      message: "Dejarás de esperar la respuesta del conductor. Podrás volver a pedir plaza cuando quieras.",
      confirm: "Retirar solicitud",
      done: "Solicitud retirada.",
    },
    loadErrorTitle: "No hemos podido cargar la reserva",
    notFoundTitle: "No encontramos esta reserva",
    notFoundMessage: "Puede que ya no exista o que no sea tuya.",
    stale: "Mostramos lo último que teníamos de esta reserva.",
    steps: { requested: "Solicitud", accepted: "Aceptada", payment: "Pago", confirmed: "Confirmada" },
  },

  // ───────────────────────────── Reserva semanal ─────────────────────────────
  weekly: {
    title: "Reserva semanal",
    statusBanner: {
      pending: { title: "Esperando al conductor", message: "Te avisaremos cuando responda a tu reserva semanal." },
      payment_pending: { title: "Solicitud aceptada", message: "Confirma tus plazas antes de que termine el tiempo." },
      confirmed: { title: "Reserva semanal confirmada", message: "Tus plazas de la semana están reservadas." },
      partially_confirmed: { title: "Confirmada en parte", message: "Algunos días están confirmados y otros siguen pendientes." },
      rejected: { title: "Reserva rechazada", message: "El conductor no ha podido aceptar tu reserva semanal." },
      cancelled: { title: "Reserva cancelada", message: "Esta reserva semanal ya no está activa." },
      expired: { title: "Reserva caducada", message: "El conductor no respondió a tiempo." },
    },
    driverHeading: "Conductor",
    daysHeading: "Días",
    legsHeading: "Trayectos",
    startHeading: "Inicio de la reserva",
    weeks: (count: number): string => pluralize(count, "semana"),
    exceptions: "Fechas con excepciones",
    occurrencesHeading: "Viajes de la reserva",
    occurrenceLeg: { outbound: "Ida", return: "Vuelta" },
    occurrenceTime: (boards: string, arrives: string): string => `${boards} – ${arrives}`,
    occurrenceStates: {
      available: "Disponible",
      requested: "Solicitada",
      skipped_exception: "Excepción",
      skipped_full: "Sin plaza",
      skipped_past: "Pasada",
      skipped_no_occurrence: "Sin viaje",
    },
    requestStates: {
      pending: "Pendiente",
      accepted: "Aceptada",
      payment_pending: "Pago pendiente",
      confirmed: "Confirmada",
      rejected: "Rechazada",
      expired: "Caducada",
      cancelled: "Cancelada",
      payment_late: "Sin confirmar",
    },
    quoteHeading: "Importe semanal",
    contributionPerWeek: "Aportación por semana",
    totalPerWeek: "Total por semana",
    tripsPerWeek: (count: number): string => `${pluralize(count, "viaje")} por semana`,
    countdown: (text: string): string => `Te quedan ${text} para confirmar tus plazas.`,
    actionWithdraw: "Retirar solicitudes pendientes",
    actionPay: "Confirmar y pagar",
    actionSearchAgain: "Buscar otro viaje",
    withdraw: {
      title: "¿Retirar las solicitudes pendientes?",
      message: "Se retirarán los días que aún esperan respuesta. Los días ya aceptados o confirmados no se tocan.",
      confirm: "Retirar pendientes",
      done: "Solicitudes pendientes retiradas.",
    },
    loadErrorTitle: "No hemos podido cargar la reserva semanal",
    notFoundTitle: "No encontramos esta reserva semanal",
    notFoundMessage: "Puede que ya no exista o que no sea tuya.",
    stale: "Mostramos lo último que teníamos de esta reserva.",
    openOccurrence: "Abre el detalle de este día",
  },

  // Mensajes de error propios del slice (se registran en `api.ts`).
  errors: {
    FAVORITES_LIMIT_REACHED: { title: "Máximo de destinos", message: "Has llegado al máximo de 20 destinos. Elimina alguno para añadir otro." },
    FAVORITE_OUTSIDE_PROVINCES: {
      title: "Destino fuera de provincia",
      message: "Este lugar queda fuera de la provincia donde funciona MVC. Elige otro de tu provincia.",
    },
    FAVORITE_IN_USE: {
      title: "Este destino se usa en tu rutina",
      message: "Quita primero las filas de la rutina que lo usan y vuelve a intentarlo.",
    },
    FAVORITE_NOT_FOUND: { title: "Destino no encontrado", message: "Este destino ya no existe. Puede que lo hayas eliminado desde otro dispositivo." },
    EMPTY_UPDATE: { title: "Nada que guardar", message: "No has cambiado nada." },
    INVALID_REQUEST_SHAPE: { title: "Ubicación incompleta", message: "Elige otra vez el lugar para guardar sus coordenadas." },
    ROUTINE_LIMIT_REACHED: { title: "Máximo de filas", message: "Tu rutina admite hasta 40 filas. Elimina alguna para añadir más." },
    ROUTINE_SAME_PLACE: { title: "Mismo lugar", message: "El origen y el destino no pueden ser el mismo lugar." },
    ROUTINE_ENTRY_EXISTS: { title: "Fila repetida", message: "Ya tienes ese trayecto a esa hora en alguno de los días elegidos." },
    ROUTINE_ENTRY_NOT_FOUND: { title: "Fila no encontrada", message: "Esta fila de la rutina ya no existe." },
    INVALID_TIME: { title: "Hora no válida", message: "La hora no es válida. Elige una hora de salida." },
    INVALID_WEEK_START: { title: "Semana no válida", message: "No se puede suspender esa semana." },
    REQUEST_NOT_FOUND: { title: "Solicitud no encontrada", message: "No encontramos esta solicitud. Puede que ya no exista o que no sea tuya." },
    REQUEST_NOT_WITHDRAWABLE: {
      title: "No se puede retirar",
      message: "Esta solicitud ya no está pendiente, así que no se puede retirar desde aquí. Si ya la aceptaron, puedes cancelar la reserva.",
    },
    WEEKLY_RESERVATION_NOT_FOUND: { title: "Reserva semanal no encontrada", message: "No encontramos esta reserva semanal. Puede que ya no exista o que no sea tuya." },
  },
} as const;

export type ProfileStrings = typeof profileStrings;
