/**
 * Textos del slice `live` (pasajero en directo: esperando el coche, cambio de ruta, en el coche, viaje terminado,
 * valoración, incidencias, compartir viaje y privacidad en directo). Español de España. Ningún texto lleva datos de
 * ejemplo: los nombres, horas e importes llegan siempre de la API.
 *
 * Las funciones (`(name) => …`) existen para interpolar y para los plurales; los espacios entre cifra y unidad son
 * espacios de no separación (`NBSP`) para que «8 min» nunca se parta en dos líneas.
 */
import { NBSP } from "@/i18n";

const nb = (value: number, unit: string): string => `${value}${NBSP}${unit}`;

export const liveStrings = {
  common: {
    close: "Cerrar",
    cancel: "Cancelar",
    continue: "Continuar",
    done: "Hecho",
    back: "Volver",
    backToMap: "Volver al mapa",
    help: "Ayuda",
    copied: "Copiado",
    unknownStop: (seq: number) => `Parada ${seq}`,
    loadingTrip: "Cargando tu viaje…",
    bookingNotFoundTitle: "No encontramos esta reserva",
    bookingNotFoundMessage: "Puede que ya no exista o que no sea tuya. Vuelve al mapa para ver tus viajes.",
    staleData: "Mostrando lo último que recibimos",
    refreshFailed: "No hemos podido actualizar",
    guestTitle: "Necesitas una cuenta",
    guestMessage: "Crea una cuenta o entra para ver tu viaje en directo.",
    createAccount: "Crear cuenta",
    withName: (name: string) => `Con ${name}`,
  },

  signal: {
    liveAge: (age: string) => `Última actualización: ${age}`,
    approximateAge: (age: string) => `Zona aproximada · ${age}`,
    staleTitle: "Sin señal",
    staleDetail: (age: string) => `Última posición: ${age}`,
    noneTitle: "Sin señal",
    noneDetail: "Aún no hay posición del coche",
    scheduled: (name: string) => `${name} aún no ha salido`,
    infoTitle: "Seguimiento en directo",
    infoLive: "El coche se actualiza cada pocos segundos mientras el viaje está en marcha. Solo ves su posición tú, que tienes una plaza reservada en este viaje.",
    infoStale: "Si pasa más de un minuto sin recibir la posición, te lo indicamos como «Sin señal» y mostramos la última posición conocida. Nunca la presentamos como «en directo».",
    infoApproximate: "Si la persona que conduce no comparte su ubicación exacta, verás una zona aproximada en lugar del coche. La hora de llegada sigue siendo válida; la distancia exacta no se muestra.",
    infoClose: "Entendido",
    age: {
      now: "ahora mismo",
      seconds: (n: number) => `hace ${n}${NBSP}s`,
      minutes: (n: number) => `hace ${n}${NBSP}min`,
      hours: (n: number) => `hace ${n}${NBSP}h`,
    },
  },

  eta: {
    estimated: "Llegada estimada",
    scheduled: "Hora prevista",
    approxTag: "aprox.",
    scheduledLine: "Según la planificación del viaje",
    calculating: "Calculando la llegada…",
    minutesLine: (minutes: number) => nb(minutes, "min"),
    remaining: (duration: string, distance: string | null) => (distance === null ? `Faltan ${duration}` : `Faltan ${duration} · ${distance}`),
  },

  waiting: {
    title: "Esperando el coche",
    enRouteTitle: (name: string) => `${name} está en camino`,
    enRouteMessage: (minutes: number) => (minutes < 1 ? "Llegada en menos de 1 min" : `Llegada en unos ${nb(minutes, "min")}`),
    enRouteNoEta: "Calculando la llegada…",
    arrivingTitle: (name: string) => `${name} está llegando`,
    arrivingMessage: "Prepárate en tu punto de recogida y ten a mano tu código.",
    atPickupTitle: (name: string) => `${name} ha llegado`,
    atPickupMessage: "Está en tu punto de recogida. Díselo con el código al subir.",
    scheduledTitle: "El viaje aún no ha empezado",
    scheduledMessage: (name: string, time: string | null) =>
      time === null ? `Te avisaremos cuando ${name} se ponga en marcha.` : `Salida prevista a las ${time}. Te avisaremos cuando ${name} se ponga en marcha.`,
    cancelledTitle: "Viaje cancelado",
    cancelledMessage: "El viaje o tu reserva se han cancelado, así que ya no hay coche que esperar.",
    cancelledAction: "Volver al mapa",
    pickupChipTitle: "Tu recogida",
    carChipTitle: (name: string) => name,
    carChipArrives: (minutes: number) => (minutes < 1 ? "llega ya" : `llega en ${nb(minutes, "min")}`),
    carChipStale: (age: string) => age,
    zoneLabel: "Zona aproximada del coche",
    viewRoute: "Ver ruta en el mapa",
    viewRouteA11y: "Ver la ruta del coche en un mapa a pantalla completa",
    contact: (name: string) => `Contactar con ${name}`,
    showCode: "Mostrar código de recogida",
    carPlaceholder: "Foto del coche no disponible",
    mapUnavailableTitle: "Mapa no disponible",
    mapUnavailableMessage: "No hemos podido cargar el mapa. Comprueba tu conexión e inténtalo de nuevo.",
    mapA11y: "Mapa con la posición del coche y tu punto de recogida",
    routeChangeTitle: (name: string) => `${name} propone una nueva parada`,
    routeChangeMessage: (time: string | null) => (time === null ? "Revisa el cambio de ruta y responde." : `Revisa el cambio de ruta y responde antes de las ${time}.`),
    routeChangeAction: "Ver propuesta",
    routeChangePendingTitle: "Cambio de ruta pendiente",
    routeChangePendingMessage: "Esperamos la respuesta del resto de pasajeros.",
    fullMapTitle: "Ruta del coche",
    openInMaps: "Ver mi recogida en Mapas",
    openInMapsFailed: "No hemos podido abrir la app de mapas.",
    pickupEta: (time: string) => `Recogida prevista a las ${time}`,
    centerOnCar: "Centrar en el coche",
    routeMapA11y: "Mapa interactivo con el coche y tu punto de recogida",
    pickupLine: (label: string | null) => (label === null || label === "" ? "Tu recogida" : `Tu recogida · ${label}`),
  },

  contact: {
    title: (name: string) => `Contactar con ${name}`,
    message: "Elige cómo quieres hablar con la persona que conduce.",
    writeTitle: "Escribir un mensaje",
    writeSubtitle: "Abre el chat de esta reserva",
    callTitle: (name: string) => `Llamar a ${name}`,
    callSubtitle: "Solo mientras dura el viaje",
    chatUnavailable: "El chat no está disponible: la reserva ya no está activa o hay un bloqueo entre las dos personas.",
    callOutside: (from: string | null, until: string | null) =>
      from !== null && until !== null ? `Podrás llamar desde las ${from} hasta las ${until}.` : "Solo puedes llamar durante la ventana del viaje.",
    callDisabled: (name: string) => `${name} ha desactivado las llamadas. Puedes escribirle por el chat.`,
    callPeerUnavailable: (name: string) => `${name} ya no tiene un teléfono activo. Puedes escribirle por el chat.`,
    callOpenFailed: "No hemos podido abrir el marcador de tu móvil.",
    callUnknown: "No podemos facilitarte el teléfono ahora mismo.",
    chatFailed: "No hemos podido abrir el chat. Inténtalo de nuevo.",
    opening: "Abriendo…",
  },

  code: {
    title: "Código de recogida",
    subtitle: (name: string) => `Díselo a ${name} al subir`,
    generating: "Generando tu código…",
    lostTitle: "Ya tienes un código generado",
    lostMessage: "Por seguridad no podemos volver a mostrarlo. Genera uno nuevo y el anterior dejará de valer.",
    generateNew: "Generar código nuevo",
    generate: "Generar mi código",
    notStartedMessage: "Podrás generar tu código cuando el viaje haya empezado.",
    notEligibleMessage: "Esta reserva ya no admite un código de recogida.",
    verifiedTitle: "Recogida confirmada",
    verifiedMessage: (time: string | null) => (time === null ? "El código se ha verificado. ¡Buen viaje!" : `Código verificado a las ${time}. ¡Buen viaje!`),
    lockedTitle: "Código bloqueado",
    lockedMessage: "Se agotaron los intentos de verificación. Genera un código nuevo.",
    attemptsLeft: (n: number) => (n === 1 ? "Queda 1 intento de verificación" : `Quedan ${n} intentos de verificación`),
    copy: "Copiar código",
    copyDone: "Código copiado",
    copyFailed: "No hemos podido copiar el código.",
    generatedAt: (time: string) => `Generado a las ${time}`,
    a11y: (digits: string) => `Código de recogida: ${digits}`,
    a11yHidden: "Código de recogida oculto",
    stateGenerated: "Generado",
    stateVerified: "Verificado",
  },

  inCar: {
    title: "En el coche",
    occupancyTitle: "En el coche",
    occupancyLine: (occupied: number, capacity: number) => `${occupied} de ${capacity} plazas ocupadas`,
    driverRole: "Al volante",
    you: "Tú",
    passenger: "Pasajero",
    hiddenPassengers: (n: number) => (n === 1 ? "1 pasajero" : `${n} pasajeros`),
    tripTitle: "Tu trayecto",
    pickupRole: "recogida",
    stopRole: "parada",
    dropoffRole: "destino",
    inProgress: "En curso",
    shareTitle: "Compartir viaje",
    sharePrivate: "(privado)",
    shareActive: "(enlace activo)",
    shareA11y: "Compartir el viaje con alguien de confianza mediante un enlace privado",
    help: "Ayuda",
    call: (name: string) => `Llamar a ${name}`,
    cancelledTitle: "Viaje cancelado",
    cancelledMessage: "El viaje o tu reserva se han cancelado.",
    etaCalculating: "Calculando la llegada…",
    notArrivedTitle: (name: string) => `${name} aún no ha llegado`,
    notArrivedMessage: "Cuando el coche llegue a tu recogida podrás darle el código. Mientras tanto puedes seguirlo en el mapa.",
    notArrivedAction: "Ver el coche en el mapa",
    waitingBannerA11y: "Estado del coche",
  },

  vehicle: {
    plateA11y: (plate: string) => `Matrícula ${plate}`,
    photoA11y: (line: string) => `Ilustración de un ${line}`,
    carA11y: "Coche",
  },

  driver: {
    ratingA11y: (value: string) => `Valoración ${value} sobre 5`,
    newDriver: "Nuevo",
    avatarA11y: (name: string) => `Foto de ${name}`,
  },

  routeChange: {
    title: "Cambio de ruta",
    proposesTitle: (name: string) => `${name} propone una nueva parada`,
    proposesMessage: "Quiere recoger a otro pasajero en su ruta.",
    proposesMessageGeneric: "Revisa cómo cambia tu trayecto antes de responder.",
    expiresAt: (time: string) => `Responde antes de las ${time}`,
    yourPickup: "Tu recogida",
    newStop: "Nueva parada",
    yourDestination: "Tu destino",
    before: "Antes",
    now: "Ahora",
    arrivalEstimated: "Llegada estimada",
    deltaMinutes: (minutes: number) => (minutes === 0 ? "sin cambio" : `${minutes > 0 ? "+" : "−"}${Math.abs(minutes)}${NBSP}min`),
    deltaCaption: "de trayecto",
    priceTitle: "Precio del viaje",
    priceIllustrative: "(ilustrativo)",
    priceBefore: "Antes",
    priceNow: "Ahora",
    noSurcharge: "Sin recargo por esta parada",
    priceUnchanged: "El precio no cambia",
    appliedOnlyIfAccepted: "El cambio de ruta se aplicará solo si lo aceptas.",
    notRequiredTitle: "No hace falta que respondas",
    notRequiredMessage: "El cambio no modifica de forma material tu hora ni tu precio. Te hemos avisado igualmente.",
    reject: "Rechazar",
    accept: "Aceptar",
    rejectTitle: "¿Rechazar el cambio de ruta?",
    rejectMessage: "El viaje seguirá como estaba y la parada nueva no se añadirá.",
    rejectConfirm: "Sí, rechazar",
    rejectBack: "Volver",
    acceptedTitle: "Has aceptado el cambio",
    acceptedMessage: "Si todos los afectados aceptan, la parada se añadirá a la ruta. Te avisaremos.",
    appliedTitle: "Cambio aplicado",
    appliedMessage: "La parada nueva ya forma parte de la ruta.",
    rejectedTitle: "Has rechazado el cambio",
    rejectedMessage: "El viaje sigue como estaba.",
    resolvedTitle: {
      expired: "La propuesta ha caducado",
      cancelled: "La propuesta se ha retirado",
      rejected: "La propuesta se ha rechazado",
      accepted: "Cambio aplicado",
    },
    resolvedMessage: {
      expired: "Nadie respondió a tiempo y el viaje sigue como estaba.",
      cancelled: "La persona que conduce la ha retirado y el viaje sigue como estaba.",
      rejected: "Alguien la rechazó y el viaje sigue como estaba.",
      accepted: "La parada nueva ya forma parte de la ruta.",
    },
    backToTrip: "Volver a mi viaje",
    staleDriver: "Sin señal",
    mapA11y: "Mapa con tu recogida, la parada nueva y tu destino",
    loading: "Cargando la propuesta…",
    sendFailed: "No hemos podido enviar tu respuesta",
  },

  codeEntry: {
    title: "Código de recogida",
    subtitle: (name: string) => `Se lo das a ${name} al subir`,
    action: "Mostrar código de recogida",
    sheetTitle: "Tu código de recogida",
  },
} as const;
