/**
 * Textos de las pantallas de «Liquidaciones», «Versiones de tarifa», «Documentos legales» y «Atención al cliente» del
 * panel (sin lámina: mismo lenguaje que 37–40). Español de España, frases cortas y honestas sobre lo que está bloqueado
 * o pendiente: nunca se promete un abono, una devolución ni una publicación que el servidor no haya confirmado.
 */
export const backofficeStrings = {
  common: {
    cancel: "Cancelar",
    close: "Cerrar",
    retry: "Reintentar",
    errorTitle: "No se ha podido completar",
    readOnly: "Tu rol permite consultar esta sección, pero no modificarla.",
    refreshFailed: "No hemos podido actualizar. Mostramos lo último que cargaste.",
    yes: "Sí",
  },

  // ── Liquidaciones ───────────────────────────────────────────────────────────────────────────────────────────────
  payouts: {
    subtitle: "Liquidaciones",
    intro: "Una liquidación por persona conductora y mes. Pedir el abono lo manda al proveedor de pago: figurará como abonado solo cuando él lo confirme.",
    providerOffTitle: "Pagos aún no disponibles",
    providerOffMessage: "Todavía no hay proveedor de pago activo. Puedes generar las liquidaciones, pero no se puede pedir ningún abono y no se enviará nada.",
    providerOnTitle: "Proveedor de pago activo",
    providerOnMessage: "Al pedir un abono, la liquidación queda «En proceso» hasta que el proveedor confirme o rechace.",
    generate: "Generar liquidaciones",
    generateA11y: "Generar las liquidaciones de un mes",
    generateTitle: "Generar liquidaciones",
    generateSubtitle: "Se crea una liquidación por cada persona conductora con saldo disponible ese mes. No se repiten las ya generadas.",
    periodLabel: "Mes (mm/aaaa)",
    periodPlaceholder: "Por ejemplo 09/2026",
    periodHelper: (label: string) => `Se generarán las de ${label}.`,
    generateConfirm: "Generar",
    generated: (created: number, skipped: number) => {
      const head = created === 0 ? "No se ha creado ninguna liquidación nueva" : created === 1 ? "Se ha creado 1 liquidación" : `Se han creado ${created} liquidaciones`;
      const tail = skipped === 0 ? "." : skipped === 1 ? ". 1 persona se ha omitido (sin saldo o ya liquidada)." : `. ${skipped} personas se han omitido (sin saldo o ya liquidadas).`;
      return `${head}${tail}`;
    },
    periodFilter: "Mes",
    periodFilterA11y: "Filtrar por mes",
    periodAll: "Todos los meses",
    statusFilterA11y: "Filtrar por estado",
    statusAll: "Todos los estados",
    statusFilterAll: "Estado",
    statusLabels: { draft: "Generada", processing: "En proceso", paid: "Abonada", failed: "Fallida", cancelled: "Cancelada" } as Readonly<Record<string, string>>,
    countsLine: (parts: string[]) => parts.join(" · "),
    bookings: (count: number) => (count === 1 ? "1 reserva" : `${count} reservas`),
    paidAt: (when: string) => `Abonada el ${when}`,
    createdAt: (when: string) => `Generada ${when}`,
    failure: (reason: string) => `El abono no se completó: ${reason}.`,
    failureReasons: {
      account_rejected: "la cuenta de cobro fue rechazada",
      provider_rejected: "el proveedor rechazó el abono",
    } as Readonly<Record<string, string>>,
    failureFallback: "el proveedor no lo completó",
    execute: "Pedir abono",
    executeRetry: "Reintentar abono",
    executeBlocked: "Bloqueado: no hay proveedor de pago activo.",
    executeTitle: "¿Pedir el abono?",
    executeMessage: (name: string, amount: string) => `Se pedirá al proveedor el abono de ${amount} a ${name}. Hasta que él lo confirme, la liquidación figura «En proceso».`,
    executeConfirm: "Pedir abono",
    executed: "Abono pedido. Figurará como abonado cuando el proveedor lo confirme.",
    processingNote: "Esperando la confirmación del proveedor.",
    emptyTitle: "No hay liquidaciones",
    emptyMessage: "Cuando haya saldo disponible de un mes, genera sus liquidaciones desde el botón de arriba.",
    emptyFilteredTitle: "No hay liquidaciones con este filtro",
    emptyFilteredMessage: "Prueba con otro mes u otro estado.",
    clearFilters: "Quitar filtros",
    deniedMessage: "Las liquidaciones son solo para Finanzas y Administración. Si las necesitas, pide a Administración que revise tu acceso.",
    amountNote: "Importe neto para la persona conductora.",
  },

  // ── Versiones de tarifa ─────────────────────────────────────────────────────────────────────────────────────────
  versions: {
    subtitle: "Versiones de tarifa",
    intro: "Borradores, tarifas aprobadas y retiradas. Una versión solo rige cuando se activa con una decisión aprobada.",
    version: (n: number) => `Versión ${n}`,
    status: { draft: "Borrador", approved: "En vigor", retired: "Retirada" } as Readonly<Record<string, string>>,
    rate: "Tarifa por km",
    passenger: "Comisión pasajero",
    driver: "Comisión conductor",
    premium: "Cuota Premium",
    cap: "Límite de gastos compartidos",
    pending: "Por definir",
    noCap: "Sin límite definido",
    from: (when: string) => `En vigor desde ${when}`,
    retiredAt: (when: string) => `Retirada ${when}`,
    updated: (when: string) => `Actualizada ${when}`,
    reference: (ref: string) => `Decisión aprobada: ${ref}`,
    notes: "Notas",
    emptyTitle: "Todavía no hay versiones",
    emptyMessage: "Guarda un borrador desde «Tarifas» y aparecerá aquí.",
    openDraft: "Abrir el borrador",
    activate: "Activar esta versión…",
    activateBlocked: "Bloqueado: la activación de tarifas está desactivada hasta que haya una decisión económica aprobada.",
    activateAdminOnly: "Solo Administración puede activar una tarifa.",
    deniedMessage: "Las versiones de tarifa son solo para Administración y Finanzas.",
  },

  // ── Documentos legales ──────────────────────────────────────────────────────────────────────────────────────────
  legal: {
    subtitle: "Documentos legales",
    intro: "Los textos legales de la app. Un borrador no tiene validez legal hasta que Legal lo revise y lo publiques con su referencia.",
    kinds: { terms: "Términos y condiciones", privacy: "Política de privacidad", cancellation: "Política de cancelación", private_check_notice: "Aviso de la comprobación privada" } as Readonly<Record<string, string>>,
    status: { draft_pending_legal_review: "Pendiente de revisión legal", published: "Publicado", retired: "Retirado" } as Readonly<Record<string, string>>,
    statusShort: { draft_pending_legal_review: "Borrador", published: "Vigente", retired: "Retirado" } as Readonly<Record<string, string>>,
    version: (n: number) => `Versión ${n}`,
    published: (when: string) => `Publicado el ${when}`,
    effectiveFrom: (when: string) => `En vigor desde ${when}`,
    noEffect: "Sin validez legal hasta su publicación.",
    newVersion: "Nueva versión",
    newVersionA11y: "Crear una versión nueva de un documento",
    view: "Ver texto",
    hideText: "Ocultar texto",
    publish: "Publicar…",
    editCopy: "Crear versión a partir de esta",
    emptyTitle: "No hay documentos legales",
    emptyMessage: "Crea la primera versión de un documento con «Nueva versión».",
    loadingText: "Cargando el texto…",
    textError: "No se ha podido cargar el texto de esta versión.",
    deniedMessage: "Los documentos legales son solo para Administración.",
    publishTitle: (label: string) => `Publicar ${label}`,
    publishSubtitle: "La publicación retira la versión vigente y es irreversible. Necesita la referencia de la revisión legal que aprueba este texto.",
    referenceLabel: "Referencia de la revisión legal",
    referencePlaceholder: "Por ejemplo REV-LEGAL-2026-014",
    dateLabel: "Entra en vigor el (opcional)",
    dateHelper: "Sin fecha, rige desde ahora.",
    publishConfirm: "Publicar",
    publishedToast: "Documento publicado.",
    versionCreated: "Versión creada como borrador pendiente de revisión legal.",
    sectionsCount: (n: number) => (n === 1 ? "1 sección" : `${n} secciones`),
  },

  legalEditor: {
    subtitle: "Nueva versión legal",
    intro: "La versión nace como borrador pendiente de revisión legal: guardarla no cambia nada de lo que ven las personas usuarias.",
    kindLabel: "Documento",
    kindSheet: "Elige el documento",
    titleLabel: "Título",
    titlePlaceholder: "Por ejemplo, Términos y condiciones",
    sectionsHeading: "Secciones",
    sectionN: (n: number) => `Sección ${n}`,
    headingLabel: "Encabezado",
    paragraphsLabel: "Párrafos",
    paragraphsHelper: "Separa los párrafos con una línea en blanco.",
    bulletsLabel: "Viñetas",
    bulletsHelper: "Una viñeta por línea.",
    addSection: "Añadir sección",
    removeSection: "Quitar esta sección",
    moveUp: "Subir",
    moveDown: "Bajar",
    save: "Guardar borrador",
    cancel: "Cancelar",
    discardTitle: "¿Descartar los cambios?",
    discardMessage: "Todo lo que has escrito en esta versión se perderá.",
    discardConfirm: "Descartar",
    keepEditing: "Seguir editando",
    fixErrors: "Revisa los campos marcados.",
    saved: "Borrador guardado. Sigue pendiente de revisión legal.",
    prefilled: (label: string, version: number) => `Parte del texto de la versión ${version} de «${label}».`,
    loadingBase: "Cargando el texto base…",
    baseError: "No se ha podido cargar el texto base. Puedes escribir la versión desde cero.",
  },

  // ── Atención al cliente ─────────────────────────────────────────────────────────────────────────────────────────
  support: {
    subtitle: "Atención al cliente",
    statusTabs: { open: "Abiertas", answered: "Respondidas", closed: "Cerradas", all: "Todas" } as Readonly<Record<string, string>>,
    tabsA11y: "Estado de las consultas",
    status: { open: "Esperando respuesta", answered: "Respondida", closed: "Cerrada" } as Readonly<Record<string, string>>,
    assignedOptions: { any: "Todas las personas", me: "Asignadas a mí", unassigned: "Sin asignar" } as Readonly<Record<string, string>>,
    assignedSheet: "Asignación",
    categoryAll: "Todas las categorías",
    categoryLabels: { trip_issue: "Problema con un viaje", payment_issue: "Problema de pago", account_profile: "Cuenta y perfil" } as Readonly<Record<string, string>>,
    categorySheet: "Categoría",
    filtersA11y: "Filtrar la cola",
    unassigned: "Sin asignar",
    assignedTo: (name: string) => `Asignada a ${name}`,
    assignedToMe: "Asignada a ti",
    messages: (n: number) => (n === 1 ? "1 mensaje" : `${n} mensajes`),
    attachments: (n: number) => (n === 1 ? "1 adjunto" : `${n} adjuntos`),
    waiting: (when: string) => `Esperando desde ${when}`,
    answeredAt: (when: string) => `Respondida ${when}`,
    emptyTitle: { open: "No hay consultas abiertas", answered: "No hay consultas respondidas", closed: "No hay consultas cerradas", all: "No hay consultas" } as Readonly<Record<string, string>>,
    emptyMessage: "Cuando una persona escriba desde el centro de ayuda, su consulta aparecerá aquí.",
    emptyFilteredTitle: "No hay consultas con este filtro",
    emptyFilteredMessage: "Prueba con otra asignación o categoría.",
    clearFilters: "Quitar filtros",
    deniedMessage: "La atención al cliente es solo para Administración y Atención al cliente.",
    unavailableTitle: "Atención no disponible",
    refreshHint: "La cola se actualiza sola cada 30 segundos.",
  },

  ticket: {
    subtitle: "Consulta",
    reference: (ref: string) => `Consulta ${ref}`,
    from: "De",
    category: "Categoría",
    created: (when: string) => `Recibida ${when}`,
    closedBy: { staff: "Cerrada por el equipo", user: "Cerrada por la persona usuaria" } as Readonly<Record<string, string>>,
    closedAt: (who: string, when: string) => `${who} · ${when}`,
    tripLink: "Viaje relacionado",
    bookingLink: "Reserva relacionada",
    conversation: "Conversación",
    you: "Tú",
    team: "Equipo MVC",
    user: "Persona usuaria",
    attachmentView: "Ver adjunto",
    attachmentA11y: (n: number, size: string) => `Ver el adjunto ${n}, ${size}`,
    attachmentLabel: (n: number) => `Adjunto ${n}`,
    assignMe: "Asignármela",
    release: "Liberar",
    assigned: "Consulta asignada a ti.",
    released: "Consulta liberada.",
    close: "Cerrar consulta",
    closeTitle: "¿Cerrar la consulta?",
    closeMessage: "La persona ya no podrá recibir más respuestas en ella. Si vuelve a escribir, se abrirá otra consulta.",
    closeConfirm: "Cerrar consulta",
    closedToast: "Consulta cerrada.",
    replyLabel: "Tu respuesta",
    replyPlaceholder: "Escribe una respuesta clara y amable…",
    replyHelper: (left: number) => `Quedan ${left} caracteres.`,
    send: "Enviar respuesta",
    sent: "Respuesta enviada.",
    closedNote: "La consulta está cerrada: no se puede responder.",
    readOnly: "Tu rol permite leer la consulta, pero no responderla.",
    loadError: "No se ha podido cargar la consulta.",
    notFound: "Esa consulta ya no existe.",
    viewerTitle: "Adjunto privado",
    viewerNotice: "Vas a abrir un archivo privado de la persona. El acceso queda registrado en la auditoría y el enlace caduca en 2 minutos.",
    viewerOpen: "Abrir adjunto",
    viewerExpires: (seconds: number) => `Caduca en ${seconds} s`,
    viewerExpired: "El enlace ha caducado. Vuelve a abrir el adjunto para ver otro.",
    viewerReopen: "Abrir de nuevo",
    viewerError: "No se ha podido abrir el adjunto.",
    viewerOther: "Este adjunto no es una imagen. Ábrelo con el enlace seguro.",
    viewerOtherAction: "Abrir en otra pestaña",
    viewerClose: "Cerrar",
    noteLabel: "Motivo de la consulta del adjunto (opcional)",
    notePlaceholder: "Por ejemplo, comprobar la captura del error",
  },
} as const;

export type BackofficeStrings = typeof backofficeStrings;
