/**
 * Textos del paquete «admin-ops» (panel de personal: tarifas, operación, alertas, auditoría, legal, atención y
 * liquidaciones). Español de España. Los literales de la lámina 40 se copian TAL CUAL; el resto sigue su voz:
 * frases cortas, sin tecnicismos, honestas sobre lo que está bloqueado o pendiente.
 */
export const opsStrings = {
  header: {
    title: "Panel MVC",
    tariffsSubtitle: "Tarifas y operaciones",
    avatarLabel: "Tu acceso al panel",
    back: "Volver",
  },

  tabs: {
    tariffs: "Tarifas",
    operations: "Operaciones",
    alerts: "Alertas",
    audit: "Auditoría",
    a11yLabel: "Secciones del panel",
  },

  common: {
    retry: "Reintentar",
    loading: "Cargando…",
    save: "Guardar",
    cancel: "Cancelar",
    close: "Cerrar",
    apply: "Aplicar",
    confirm: "Confirmar",
    back: "Volver",
    loadMore: "Cargar más",
    loadMoreFailed: "No hemos podido cargar más. Lo ya cargado se conserva.",
    loadingMore: "Cargando más…",
    refresh: "Actualizar",
    none: "—",
    pending: "Por definir",
    noName: "Persona sin nombre",
    system: "Sistema",
    offlineTitle: "Sin conexión",
    offlineDetail: "Mostramos lo último que cargaste.",
    staleRefresh: "No hemos podido actualizar. Mostramos lo último que cargaste.",
    errorTitle: "No hemos podido cargar esto",
    savedToast: "Guardado",
    updatedBy: (name: string, when: string) => `Última modificación: ${when} · ${name}`,
  },

  noPermission: {
    title: "Sin permiso",
    message: "Tu rol no da acceso a esta sección. Si lo necesitas, pide a Administración que revise tus permisos.",
    sectionMessage: (section: string) => `Tu rol no da acceso a «${section}». Si lo necesitas, pide a Administración que revise tus permisos.`,
    readOnlyHint: "Puedes consultarlo, pero solo Administración puede modificarlo.",
    readOnlyTariffs: "Puedes consultar las tarifas, pero tu rol no permite modificarlas.",
  },

  access: {
    sheetTitle: "Tu acceso al panel",
    sheetSubtitle: "Lo que tu rol permite en estas pantallas. Cada acción se vuelve a comprobar en el servidor.",
    rolesLabel: "Roles",
    noRoles: "Sin rol de personal",
    confirmedFromServer: "Permisos confirmados por el servidor.",
    deducedFromRoles: "Permisos deducidos de tus roles; el servidor los vuelve a comprobar en cada acción.",
    roleLabels: {
      admin: "Administración",
      verification_admin: "Verificación",
      finance_admin: "Finanzas",
      support_admin: "Atención al cliente",
    },
    levels: { write: "Puede editar", read: "Solo lectura", none: "Sin acceso" },
    areas: {
      tariffs: "Tarifas",
      operations: "Operación y alertas en tiempo real",
      alerts: "Alertas de operación",
      audit: "Auditoría",
      legal: "Documentos legales",
      support: "Atención al cliente",
      payouts: "Liquidaciones",
    },
    payoutsYes: "Puede generar y pedir abonos",
    payoutsNo: "Sin acceso",
    goHome: "Ir al inicio del panel",
  },

  // ── Pestaña «Tarifas» (lámina 40a/40b: literales) ──────────────────────────────────────────────────────────────
  tariffs: {
    cardTitle: "Configuración de tarifas (propuesta)",
    ratePending: "Tarifa por km (propuesta)",
    rateInputs: "Tarifa base por km (propuesta)",
    rateSuffix: "€ / km",
    rateShortPending: "tarifa por definir",
    rateA11y: "Tarifa por kilómetro en euros",
    provinceInfo: "Solo trayectos dentro de la provincia.",
    driverPending: "Comisión conductor",
    passengerPending: "Comisión pasajero",
    driverInputs: "Comisión conductor (propuesta)",
    passengerInputs: "Comisión pasajero (propuesta)",
    commissionSuffix: "%",
    /** Unidad que dibuja la lámina 40a junto a una comisión todavía «Por definir». */
    pendingUnit: "€",
    commissionA11yDriver: "Comisión del conductor en porcentaje",
    commissionA11yPassenger: "Comisión del pasajero en porcentaje",
    premiumLabel: "Cuota Premium (propuesta)",
    premiumSuffix: "€ / mes",
    premiumA11y: "Cuota Premium en euros al mes",
    pending: "Por definir",
    selectHint: "Toca para definir el valor",
    exampleTitlePending: "Ejemplo de aportación",
    exampleTitleInputs: "Precio final para el pasajero (ejemplo)",
    exampleTrip: "Trayecto de {km} km (propuesta)",
    exampleCaptionInputs: "Incluye tarifa + comisiones (por definir).",
    exampleLoading: "Calculando…",
    exampleUnavailable: "No se pudo calcular el ejemplo.",
    exampleInvalid: "Corrige los datos marcados para ver el ejemplo.",
    exampleExpandHint: "Toca para ver el desglose del ejemplo",
    breakdownTitle: "Desglose del ejemplo",
    breakdownTag: "ejemplo",
    breakdown: {
      contribution: "Aportación por trayecto",
      passengerCommission: "Comisión del pasajero",
      passengerTotal: "Total para el pasajero",
      driverCommission: "Comisión del conductor",
      driverNet: "Neto del conductor",
    },
    distanceLabel: "Distancia del ejemplo (km)",
    distanceError: "Escribe una distancia entre 0,001 y 2.000 km.",
    save: "Guardar borrador",
    saveA11y: "Guardar el borrador de tarifa",
    saved: "Borrador guardado.",
    savedDetail: "No cambia ninguna reserva ni ninguna tarifa en vigor.",
    nothingToSave: "No hay cambios que guardar.",
    fixErrors: "Revisa los campos marcados.",
    discard: "Descartar cambios",
    discardA11y: "Descartar los cambios sin guardar",
    unsavedBadge: "Cambios sin guardar",
    restrictionsTitle: "Restricciones de operación",
    restrictionsSubtitle: "Solo trayectos dentro de la provincia",
    restrictionsLockedTitle: "Restricción fija",
    restrictionsLockedMessage:
      "«Solo trayectos dentro de la provincia» es una regla de producto: MVC opera dentro de UNA provincia y esta restricción no se puede desactivar.",
    alertsTitle: "Alertas en tiempo real",
    applyNoteFallback: "Los cambios de tarifas afectan solo a futuras reservas. No se modifican reservas confirmadas.",
    /** La lámina parte la nota antes de este fragmento. */
    applyNoteBreakBefore: "a futuras reservas",
    auditNoteFallback: "Registro en auditoría privada de MVC",
    // Bajo el pliegue
    draftMeta: (version: number, when: string, who: string | null) =>
      who === null ? `Borrador v${version} · actualizado ${when}` : `Borrador v${version} · actualizado ${when} · ${who}`,
    noDraft: "Todavía no hay borrador. Escribe una propuesta y guarda el borrador.",
    extrasTitle: "Más datos del borrador",
    distanceHelper: "Solo cambia el ejemplo de arriba; no se guarda.",
    approvalRef: (reference: string) => `Decisión aprobada: ${reference}`,
    activateAdminOnly: "Solo Administración puede activar una tarifa.",
    capLabel: "Límite de gastos compartidos (propuesta)",
    capSuffix: "€ / trayecto",
    capHelper: "Tope por pasajero y trayecto. Déjalo vacío si no hay límite definido.",
    notesLabel: "Notas del borrador",
    notesPlaceholder: "Contexto de la propuesta (opcional)",
    activeTitle: "Tarifa en vigor",
    activeNone: "Todavía no hay ninguna tarifa aprobada.",
    activeNoneDetail: "Mientras no exista una decisión económica aprobada, los importes de la app se muestran como «Por definir».",
    activeVersion: (version: number) => `Versión ${version}`,
    activeFrom: (when: string) => `En vigor desde ${when}`,
    activeRate: "Tarifa por km",
    activeDriver: "Comisión conductor",
    activePassenger: "Comisión pasajero",
    activePremium: "Cuota Premium",
    activeCap: "Límite de gastos compartidos",
    capNone: "Sin límite definido",
    activationTitle: "Activación de la tarifa",
    activationBlocked: "Bloqueado",
    activationBlockedFootnote: "Un borrador no es una tarifa en vigor: guardarlo no cambia ninguna reserva.",
    activationAvailable: "Disponible",
    activationAvailableMessage: "La activación está habilitada. Activar una versión exige la referencia de la decisión aprobada y una fecha futura.",
    activate: "Activar esta versión…",
    activateIncomplete: "Define la tarifa por km y las dos comisiones para poder activarla.",
    activateSaveFirst: "Guarda primero los cambios del borrador.",
    historyLink: "Historial de versiones",
    historySubtitle: "Borradores, tarifas aprobadas y retiradas",
  },

  activate: {
    title: "Activar la tarifa",
    message: "Se aplicará solo a reservas NUEVAS desde la fecha que indiques. No cambia reservas confirmadas.",
    referenceLabel: "Referencia de la decisión aprobada",
    referencePlaceholder: "Acta o ticket, por ejemplo ACTA-2026-11-03",
    referenceError: "Indica la referencia de la decisión económica aprobada (entre 3 y 300 caracteres).",
    dateLabel: "Entra en vigor el",
    datePlaceholder: "dd/mm/aaaa",
    dateError: "Escribe una fecha futura válida, por ejemplo 10/11/2026.",
    confirm: "Activar tarifa",
    success: "Tarifa activada.",
    successDetail: "Rige para las reservas nuevas desde la fecha indicada.",
    blocked: "Activación bloqueada por el servidor. No se ha cambiado nada.",
  },

  definition: {
    titleDriver: "Comisión del conductor (propuesta)",
    titlePassenger: "Comisión del pasajero (propuesta)",
    titlePremium: "Cuota Premium (propuesta)",
    messageCommission: "Escribe el porcentaje. Puedes dejarlo «Por definir» mientras no haya decisión.",
    messagePremium: "Escribe el importe mensual en euros. Puedes dejarlo «Por definir» mientras no haya decisión.",
    commissionLabel: "Porcentaje",
    commissionPlaceholder: "Por ejemplo 10",
    premiumLabel: "Importe al mes (€)",
    premiumPlaceholder: "Por ejemplo 2,99",
    apply: "Aplicar",
    keepPending: "Dejar «Por definir»",
  },

  // ── Pestaña «Operaciones» ───────────────────────────────────────────────────────────────────────────────────────
  operations: {
    rulesTitle: "Reglas de alerta",
    rulesIntro: "Las alertas se crean solo a partir de eventos reales: nunca se inventan.",
    masterOnA11y: "Alertas en tiempo real activadas",
    masterOffA11y: "Alertas en tiempo real desactivadas",
    ruleA11y: (label: string) => `Regla: ${label}`,
    activeCount: (active: number, total: number) => `${active} de ${total} reglas activas`,
    edit: "Ajustar umbrales",
    editClose: "Ocultar umbrales",
    paramSave: "Guardar umbrales",
    paramReset: "Restablecer",
    paramSaved: "Umbrales guardados.",
    toggleSaved: "Cambio guardado.",
    toggleFailed: "No se pudo guardar el cambio. Se ha restaurado el valor anterior.",
    restoredNote: "Se ha restaurado el valor anterior.",
    paramLabels: {
      unusual_cancellations: { thresholdCount: "Cancelaciones para avisar", windowMinutes: "En una ventana de (minutos)" },
      route_incidents: { thresholdCount: "Incidencias para avisar", windowMinutes: "En una ventana de (minutos)" },
      schedule_price_changes: { maxPendingMinutes: "Propuesta sin respuesta durante (minutos)" },
    } as Readonly<Record<string, Readonly<Record<string, string>>>>,
    sourceUnavailable: "Sin fuente de datos",
    readOnlyTitle: "Solo lectura",
    confirmOffTitle: "¿Desactivar las alertas en tiempo real?",
    confirmOffMessage: "Dejarán de evaluarse las tres reglas y no se avisará de cancelaciones inusuales, cambios sin responder ni incidencias. Puedes volver a activarlas cuando quieras.",
    confirmOffAction: "Desactivar",
    lastUpdated: (when: string, who: string | null) => (who === null ? `Última modificación: ${when}` : `Última modificación: ${when} · ${who}`),
    neverUpdated: "Sin modificaciones todavía: valores por defecto.",
    linksTitle: "Más herramientas",
    linkVersions: { title: "Versiones de tarifa", subtitle: "Historial y activación" },
    linkPayouts: { title: "Liquidaciones", subtitle: "Generar y pedir abonos a conductores" },
    linkLegal: { title: "Documentos legales", subtitle: "Versiones, borradores y publicación" },
    linkSupport: { title: "Atención al cliente", subtitle: "Cola de consultas de las personas usuarias" },
  },

  // ── Pestaña «Alertas» ───────────────────────────────────────────────────────────────────────────────────────────
  alerts: {
    statusOptions: { open: "Abiertas", acknowledged: "Reconocidas", resolved: "Resueltas", all: "Todas" },
    kindAll: "Todas las reglas",
    kindLabels: {
      unusual_cancellations: "Cancelaciones inusuales",
      schedule_price_changes: "Cambios de horario o precio",
      route_incidents: "Incidencias en ruta",
    } as Readonly<Record<string, string>>,
    skippedPrefix: "No se evaluó:",
    kindFilterTitle: "Filtrar por regla",
    kindFilterA11y: "Filtrar por regla",
    statusA11y: "Filtrar por estado",
    evaluate: "Evaluar ahora",
    evaluateA11y: "Evaluar las reglas de alerta ahora",
    evaluating: "Evaluando…",
    evaluated: (created: number, auto: number) => {
      const newPart = created === 0 ? "ninguna alerta nueva" : created === 1 ? "1 alerta nueva" : `${created} alertas nuevas`;
      const autoPart = auto === 0 ? "" : auto === 1 ? " y 1 cerrada sola" : ` y ${auto} cerradas solas`;
      return `Evaluación hecha: ${newPart}${autoPart}.`;
    },
    skipped: {
      disabled: "regla desactivada",
      realtime_alerts_off: "alertas en tiempo real desactivadas",
      source_unavailable: "sin fuente de datos",
    },
    severity: { info: "Información", warning: "Aviso", critical: "Crítica" },
    status: { open: "Abierta", acknowledged: "Reconocida", resolved: "Resuelta" },
    detected: (when: string) => `Detectada ${when}`,
    acknowledgedAt: (when: string) => `Reconocida ${when}`,
    resolvedAt: (when: string) => `Resuelta ${when}`,
    acknowledge: "Reconocer",
    resolve: "Resolver",
    acknowledgedToast: "Alerta reconocida.",
    resolvedToast: "Alerta resuelta.",
    confirmResolveTitle: "¿Resolver esta alerta?",
    confirmResolveMessage: "Se cerrará y dejará de figurar entre las abiertas. Si el problema persiste, el evaluador creará otra.",
    emptyOpenTitle: "No hay alertas abiertas",
    emptyOpenMessage: "Cuando una regla detecte algo con datos reales, aparecerá aquí. Puedes evaluar las reglas ahora.",
    emptyOtherTitle: "No hay alertas con este filtro",
    emptyOtherMessage: "Prueba con otro estado o con todas las reglas.",
    readOnlyHint: "Tu rol permite consultar las alertas, pero no gestionarlas.",
    dataTitle: "Datos de la alerta",
    dataShow: "Ver datos",
    dataHide: "Ocultar datos",
    dataLabels: {
      count: "Recuento",
      cancellations: "Cancelaciones",
      incidents: "Incidencias",
      thresholdCount: "Umbral",
      windowMinutes: "Ventana (min)",
      maxPendingMinutes: "Máximo sin respuesta (min)",
      pendingMinutes: "Sin respuesta (min)",
      proposalId: "Propuesta",
      tripId: "Viaje",
      bookingIds: "Reservas",
    } as Readonly<Record<string, string>>,
    noData: "Sin datos adicionales.",
    busy: "Guardando…",
    province: (name: string) => `Provincia: ${name}`,
    notificationHint: "Las alertas nuevas avisan a Administración y a Atención al cliente.",
  },

  // ── Pestaña «Auditoría» ─────────────────────────────────────────────────────────────────────────────────────────
  audit: {
    presets: { all: "Todo", admin: "Administración", tariffs: "Tarifas", support: "Atención", legal: "Legal", payouts: "Liquidaciones" },
    presetsA11y: "Filtrar por tipo de acción",
    filters: "Filtros",
    filtersA11y: "Abrir los filtros avanzados",
    filtersTitle: "Filtros de auditoría",
    filtersSubtitle: "Combina los que necesites. Las fechas son días naturales de Madrid.",
    actionLabel: "Acción",
    actionPlaceholder: "admin.tariff_draft.saved o admin.*",
    actionHelper: "Exacta, o con * al final para buscar por prefijo.",
    actorLabel: "Persona (identificador)",
    actorPlaceholder: "UUID de la persona",
    entityTypeLabel: "Tipo de entidad",
    entityTypePlaceholder: "tariff_version",
    entityIdLabel: "Identificador de la entidad",
    entityIdPlaceholder: "UUID o número",
    fromLabel: "Desde",
    toLabel: "Hasta",
    datePlaceholder: "dd/mm/aaaa",
    apply: "Aplicar filtros",
    clear: "Quitar filtros",
    activeFilters: (count: number) => (count === 1 ? "1 filtro activo" : `${count} filtros activos`),
    privacyNote: "Registro privado de MVC. El servidor oculta los datos personales de los metadatos («[oculto]»).",
    rowActor: (name: string) => name,
    redactions: (count: number) => (count === 1 ? "1 dato oculto" : `${count} datos ocultos`),
    detailsShow: "Ver detalle",
    detailsHide: "Ocultar detalle",
    entity: "Entidad",
    request: "Petición",
    eventId: "Evento",
    metadata: "Metadatos",
    noMetadata: "Sin metadatos.",
    onlyThisPerson: "Solo esta persona",
    onlyThisEntity: "Solo esta entidad",
    emptyTitle: "No hay eventos con este filtro",
    emptyMessage: "Prueba con otro tipo de acción o con otras fechas.",
    emptyNoFilterTitle: "Todavía no hay eventos",
    emptyNoFilterMessage: "Los eventos aparecerán aquí a medida que el personal use el panel.",
    onlyAdmin: "La auditoría solo está disponible para Administración.",
  },
} as const;

export type OpsStrings = typeof opsStrings;
