/**
 * Textos del paquete `driver` · «publicar rutas» (vehículo, requisitos, solicitudes de pasajeros), en es-ES, tuteo y frases
 * cortas como las láminas 17 a 20. Las pantallas no llevan literales: todo sale de aquí (y los importes, de `formatMoney`).
 */
import { formatCountdown, pluralize } from "@/i18n";

export const publishStrings = {
  common: {
    retry: "Reintentar",
    close: "Cerrar",
    cancel: "Cancelar",
    back: "Volver",
    understood: "Entendido",
    openSettings: "Abrir ajustes",
    offlineTitle: "Sin conexión",
    offlineDetail: "Mostramos lo último que tenemos. Se actualizará al volver la conexión.",
    offlineAction: "Necesitas conexión para hacer esto. Inténtalo cuando vuelvas a tener red.",
    loadError: "No hemos podido cargarlo",
    loadErrorDetail: "Revisa tu conexión e inténtalo de nuevo.",
    updating: "Actualizando…",
    plate: (plate: string): string => plate,
  },

  // ── 18 · Publica tu ruta ────────────────────────────────────────────────────────────────────────────────────────────
  routeForm: {
    title: "Publica tu ruta",
    loading: "Cargando el formulario",
    origin: "Origen",
    destination: "Destino",
    originPlaceholder: "Elige el origen",
    destinationPlaceholder: "Elige el destino",
    originSearch: "Origen de la ruta",
    destinationSearch: "Destino de la ruta",
    schedules: "Horarios previstos",
    outbound: (to: string): string => (to ? `Ida (hacia ${to})` : "Ida"),
    returnLeg: (from: string): string => (from ? `Vuelta (desde ${from})` : "Vuelta"),
    noReturn: "Sin vuelta",
    timeUnset: "Elige hora",
    outboundSheetTitle: "Hora de salida de la ida",
    outboundSheetSubtitle: "A qué hora sales del origen.",
    returnSheetTitle: "Hora de salida de la vuelta",
    returnSheetSubtitle: "A qué hora sales del destino de regreso. Es opcional.",
    frequency: "Frecuencia",
    daily: "Diaria (laborables)",
    oneOff: "Puntual",
    dailyHint: "Se publica de lunes a viernes, empezando el próximo día laborable.",
    date: "Día del viaje",
    dateUnset: "Elige el día",
    seats: "Plazas",
    seatsLess: "Quitar una plaza",
    seatsMore: "Añadir una plaza",
    seatsValue: (n: number): string => `${n}`,
    detour: "Máx. desvío por parada",
    detourValue: (minutes: number): string => `${minutes} min`,
    detourSheetTitle: "Máximo desvío por parada",
    detourSheetSubtitle: "Cuánto aceptas desviarte para recoger a alguien.",
    pickupOnRoute: "Recoger en ruta",
    pickupOnRouteHint: "Permito recoger en paradas dentro de mi ruta.",
    calculate: "Calcular ruta",
    calculating: "Calculando…",
    notReadyTitle: "Antes de publicar te falta",
    notReadyAction: "Completar requisitos",
    noVehicleTitle: "Necesitas un vehículo",
    noVehicleMessage: "Añade tu vehículo y sus documentos para poder publicar rutas.",
    vehicleLine: (name: string, seats: number): string => `${name} · ${seats} plazas`,
    discardTitle: "¿Salir sin calcular la ruta?",
    discardMessage: "Perderás lo que has escrito.",
    discardConfirm: "Salir",
    discardKeep: "Seguir editando",
    errors: {
      origin: "Elige el origen de la ruta.",
      destination: "Elige el destino de la ruta.",
      same: "El origen y el destino no pueden ser el mismo sitio.",
      outbound: "Elige la hora de salida.",
      date: "Elige el día del viaje.",
      seats: "Elige entre 1 y las plazas de tu vehículo.",
      returnBeforeOutbound: "La vuelta tiene que salir después de la ida.",
    },
  },

  // ── 19 · Paradas y recorrido ────────────────────────────────────────────────────────────────────────────────────────
  stops: {
    title: "Paradas y recorrido",
    mapLabel: "Mapa de la ruta con sus paradas",
    originTag: "Origen",
    destinationTag: "Destino",
    stopTag: "Parada",
    optionalTag: "Opcional",
    addStop: "Añadir parada",
    addStopSearch: "Nueva parada",
    searchOther: "Buscar otra parada",
    searchOtherSheet: "Cambiar esta parada",
    outsideTag: "Fuera de provincia",
    suggested: "(sugerida)",
    save: "Guardar ruta",
    saving: "Guardando…",
    recalculating: "Recalculando la ruta…",
    moveTitle: (label: string): string => label,
    moveUp: "Subir",
    moveDown: "Bajar",
    remove: "Quitar parada",
    change: "Cambiar parada",
    makeOptional: "Marcar como opcional",
    makeFixed: "Quitar «opcional»",
    detour: (minutes: number): string => `Desvío +${minutes} min`,
    alternatives: "Paradas dentro de la provincia",
    stopsA11y: (index: number, label: string, time: string | null): string => `${index}. ${label}${time ? `, ${time}` : ""}`,
    handleA11y: (label: string): string => `Opciones de la parada ${label}`,
    summary: (km: string, minutes: number): string => `${km} · ${minutes} min`,
    planError: "No hemos podido calcular la ruta.",
    discardTitle: "¿Salir sin guardar la ruta?",
    discardMessage: "La ruta no se publicará.",
    discardConfirm: "Salir",
    discardKeep: "Seguir editando",
    missingDraftTitle: "Esta ruta ya no está",
    missingDraftMessage: "Vuelve a empezar desde «Publica tu ruta».",
    missingDraftAction: "Publicar una ruta",
    toastSaved: "Ruta publicada",
  },

  // ── Ruta publicada ──────────────────────────────────────────────────────────────────────────────────────────────────
  published: {
    title: "Ruta publicada",
    heading: "¡Tu ruta está publicada!",
    oneOff: (when: string): string => `Los pasajeros ya pueden pedirte plaza para el ${when}.`,
    daily: (count: number): string => `Hemos publicado ${count} viajes de los próximos 28 días. Seguiremos añadiendo más.`,
    routeLabel: "Ruta",
    scheduleLabel: "Horarios",
    seatsLabel: "Plazas",
    frequencyLabel: "Frecuencia",
    distanceLabel: "Distancia",
    openRequests: "Ver solicitudes",
    seeTrip: "Ver mi viaje",
    publishAnother: "Publicar otra ruta",
    home: "Ir al mapa",
    notFoundTitle: "No encontramos esta ruta",
    notFoundMessage: "Puede que ya no exista.",
  },

  // ── 17 · Tu vehículo ─────────────────────────────────────────────────────────────────────────────────────────────────
  vehicle: {
    title: "Tu vehículo",
    loading: "Cargando tu vehículo",
    photoChange: "Cambiar foto",
    photoAdd: "Añadir foto",
    photoOptional: "(opcional)",
    photoEmpty: "Aún no hay foto de tu vehículo",
    photoEmptyHint: "Con una foto, los pasajeros reconocen tu coche en la recogida.",
    photoStatusReview: "Foto en revisión",
    photoStatusRejected: "Foto rechazada",
    photoA11y: (name: string): string => `Foto de ${name}`,
    photoCameraA11y: "Cambiar la foto del vehículo",
    photoSheetTitle: "Foto del vehículo",
    photoTake: "Hacer una foto",
    photoLibrary: "Elegir de la galería",
    photoUploading: {
      preparing: "Preparando la foto…",
      uploading: "Subiendo la foto…",
      finishing: "Casi listo…",
    },
    photoUploaded: "Foto enviada. La revisaremos enseguida.",
    photoDenied: "Sin permiso de cámara no podemos hacer la foto. Puedes elegir una de tu galería.",
    photoBlocked: "El permiso de cámara está desactivado. Actívalo en los ajustes del móvil o elige una foto de la galería.",
    photoUnavailable: "No hemos podido abrir la cámara en este dispositivo. Elige una foto de la galería.",
    libraryDenied: "Sin permiso para ver tus fotos no podemos elegir una. Puedes hacer una con la cámara.",
    libraryBlocked: "El permiso de fotos está desactivado. Actívalo en los ajustes del móvil o haz una foto con la cámara.",
    photoTooLarge: "La foto pesa más de 20 MB. Elige otra o hazla con menos resolución.",
    photoUnreadable: "No hemos podido leer esa foto. Elige otra.",

    make: "Marca",
    model: "Modelo",
    plate: "Matrícula",
    color: "Color",
    seats: "Plazas disponibles",
    seatsHint: "Sin contarte a ti",
    searchPlaceholder: "Busca o escribe",
    useCustom: (text: string): string => `Usar «${text}»`,
    noMatches: "No hay coincidencias. Escríbelo y pulsa «Usar».",
    makeSheetTitle: "Elige la marca",
    modelSheetTitle: "Elige el modelo",
    modelNeedsMake: "Elige primero la marca",
    makePlaceholder: "Elige la marca",
    modelPlaceholder: "Elige el modelo",
    platePlaceholder: "1234 ABC",
    colorPlaceholder: "Gris",
    seatsMinusA11y: "Una plaza menos",
    seatsPlusA11y: "Una plaza más",
    seatsValueA11y: (n: number): string => `${pluralize(n, "plaza")} disponibles`,
    plateErrorEmpty: "Escribe la matrícula",
    plateErrorFormat: "Revisa la matrícula. Ejemplo: 1234 ABC",
    plateErrorTaken: "Ya hay un vehículo registrado con esa matrícula.",
    makeError: "Elige la marca",
    modelError: "Elige el modelo",
    colorError: "El color es demasiado largo",
    seatsError: "Elige entre 1 y 8 plazas",

    save: "Guardar",
    saving: "Guardando…",
    create: "Guardar vehículo",
    noChanges: "No hay cambios que guardar.",
    saved: "Vehículo guardado",
    savedReview: "Vehículo guardado. Lo revisaremos de nuevo antes de que puedas publicar.",
    created: "Vehículo añadido. Lo revisaremos antes de que puedas publicar.",
    confirmTitle: "¿Guardar los cambios?",
    confirmMessage:
      "Si cambias los datos de tu vehículo, lo revisaremos de nuevo y no podrás publicar rutas hasta que lo aprobemos.",
    confirmAction: "Guardar cambios",
    discardTitle: "¿Salir sin guardar?",
    discardMessage: "Has cambiado datos del vehículo y todavía no se han guardado.",
    discardAction: "Salir sin guardar",
    keepEditing: "Seguir editando",

    emptyTitle: "Añade tu vehículo",
    emptyMessage: "Para publicar rutas necesitamos los datos de tu coche. Lo revisaremos antes de que puedas publicar.",
    emptyAction: "Añadir vehículo",

    reviewPending: "Lo estamos revisando",
    reviewApproved: "Vehículo aprobado",
    reviewRejected: "Vehículo rechazado",
    reviewReason: (reason: string): string => `Motivo: ${reason}`,
    reviewEditHint: "Corrige los datos y vuelve a guardarlos para que lo revisemos.",

    otherVehicles: "Otros vehículos",
    otherVehicleRow: (name: string, plate: string): string => `${name} · ${plate}`,
    addAnother: "Añadir otro vehículo",
    currentVehicle: "Vehículo en uso",
    showVehicleA11y: (name: string): string => `Ver ${name}`,

    requirementsTitle: "Para poder publicar",
    requirementsAllDone: "Cumples todos los requisitos para publicar rutas.",
    requirementsLoadError: "No hemos podido comprobar tus requisitos",
    publishAction: "Publicar una ruta",
    publishBlocked: "Completa los requisitos para publicar",
  },

  // ── Requisitos (`GET /v1/me/driver/readiness`) ───────────────────────────────────────────────────────────────────────
  readiness: {
    states: {
      approved: "Aprobado",
      in_review: "En revisión",
      missing: "Falta",
      rejected: "Rechazado",
      expired: "Caducado",
    },
    docUploaded: "Documento subido",
    docUploadedReview: "Documento subido · en revisión",
    docMissing: "Falta subirlo",
    docRejected: "Rechazado: sube otro",
    docExpired: "Caducado: sube la renovación",
    expiresOn: (date: string): string => `Vigente hasta ${date}`,
    expiresSoon: (date: string): string => `Caduca el ${date}`,
    expiredOn: (date: string): string => `Caducó el ${date}`,
    actions: {
      upload: "Subir",
      renew: "Renovar",
      fix: "Corregir",
      review: "Ver estado",
      add: "Añadir",
    },
    keys: {
      public_photo: "Foto pública",
      identity: "Identidad",
      vehicle: "Vehículo",
      vehicle_documents: "Documentación del vehículo",
      vehicle_photo: "Foto del vehículo",
      insurance: "Seguro (uso particular)",
      driver_license: "Permiso de conducir",
    },
    hints: {
      public_photo: "Los pasajeros ven esta foto antes de aceptar el viaje.",
      identity: "Verificamos tu identidad antes de que puedas conducir.",
      vehicle: "Revisamos los datos de tu vehículo.",
      vehicle_documents: "Revisamos la documentación de tu vehículo.",
      vehicle_photo: "Una foto del vehículo ayuda a reconocerlo.",
      insurance: "Necesitamos un seguro vigente para uso particular.",
      driver_license: "Por ahora solo te lo pedimos como información.",
    },
    informative: "Informativo",
    blocking: "Necesario para publicar",
  },

  // ── Documentación del vehículo ───────────────────────────────────────────────────────────────────────────────────────
  documents: {
    title: "Documentación del vehículo",
    loading: "Cargando la documentación",
    vehicleLine: (name: string, plate: string): string => `${name} · ${plate}`,
    privacyNote: "Tus documentos se guardan en un espacio privado. Solo los ve el equipo de revisión de MVC.",
    sections: {
      photo: "Foto del vehículo",
      insurance: "Seguro (uso particular)",
      license: "Permiso de conducir",
      data: "Datos del vehículo",
    },
    status: {
      approved: "Aprobado",
      pending: "En revisión",
      rejected: "Rechazado",
      none: "Sin subir",
      expired: "Caducado",
    },
    photoHelp: "Una foto reciente en la que se vea el coche entero. JPG, PNG, WebP o HEIC de hasta 20 MB.",
    insuranceHelp:
      "Sube tu póliza o el recibo vigente en PDF o foto (hasta 20 MB). Revisamos a mano la fecha de caducidad: tú no tienes que escribirla.",
    licenseHelp: "Súbelo en PDF o foto (hasta 20 MB). Solo lo ve el equipo de revisión. Por ahora no es imprescindible para publicar.",
    licenseRejectedHint: "Súbelo de nuevo, con todos los datos bien legibles.",
    dataHelp: "Marca, modelo, matrícula y plazas. Los revisamos nosotros.",
    uploadPhoto: "Subir foto",
    replacePhoto: "Cambiar foto",
    uploadInsurance: "Subir seguro",
    replaceInsurance: "Subir otro seguro",
    renewInsurance: "Subir la renovación",
    uploadLicense: "Subir permiso",
    replaceLicense: "Subir otro permiso",
    editData: "Editar datos",
    viewFile: "Ver archivo",
    expiresOn: (date: string): string => `Vigente hasta ${date}`,
    expiresSoon: "Caduca pronto: sube la renovación cuando la tengas.",
    expiredOn: (date: string): string => `Caducó el ${date}`,
    expiresPending: "Fecha de caducidad pendiente de verificar",
    uploadedOn: (date: string): string => `Subido el ${date}`,
    reviewReason: (reason: string): string => `Motivo: ${reason}`,
    chooseSource: "¿Cómo quieres subirlo?",
    takePhoto: "Hacer una foto",
    fromLibrary: "Elegir de la galería",
    fromFiles: "Elegir un archivo (PDF o foto)",
    uploading: {
      preparing: "Preparando el archivo…",
      uploading: "Subiendo el archivo…",
      finishing: "Casi listo…",
    },
    uploaded: "Archivo enviado. Lo revisaremos enseguida.",
    cameraDenied: "Sin permiso de cámara no podemos hacer la foto. Elige un archivo o una foto de tu galería.",
    cameraBlocked: "El permiso de cámara está desactivado. Actívalo en los ajustes del móvil o elige un archivo.",
    libraryDenied: "Sin permiso para ver tus fotos no podemos elegir una. Haz una foto o elige un archivo.",
    libraryBlocked: "El permiso de fotos está desactivado. Actívalo en los ajustes del móvil o elige un archivo.",
    unavailable: "No hemos podido abrir esa opción en este dispositivo. Prueba con otra.",
    tooLarge: "El archivo pesa más de 20 MB. Elige otro más ligero.",
    unreadable: "No hemos podido leer ese archivo. Elige otro.",
    typeNotAllowed: "Ese formato no está permitido. Usa PDF, JPG, PNG o WebP.",
    openError: "No hemos podido abrir el archivo. Inténtalo de nuevo.",
    vehicleMissingTitle: "No encontramos ese vehículo",
    vehicleMissingMessage: "Puede que lo hayas eliminado o que no sea tuyo.",
    vehicleMissingAction: "Ir a mi vehículo",
  },

  // ── 20 · Solicitudes ─────────────────────────────────────────────────────────────────────────────────────────────────
  requests: {
    title: "Solicitudes",
    loading: "Cargando solicitudes",
    banner: "Gestiona solicitudes estando detenido.",
    pending: "Pendiente",
    waitingPayment: "Esperando el pago",
    confirmed: "Confirmada",
    rejected: "Rechazada",
    expired: "Caducada",
    cancelled: "Cancelada",
    detourLabel: "Desvío estimado",
    detourNone: "Sin desvío",
    detourValue: (minutes: number): string => `+${minutes} min`,
    occupancyTitle: "Plazas ocupadas en tu ruta",
    occupancySeats: (occupied: number, total: number): string => `${occupied} / ${total} ${total === 1 ? "plaza" : "plazas"}`,
    occupancyRange: (from: string, to: string): string => `${from} → ${to}`,
    occupancyA11y: (occupied: number, total: number, from: string, to: string): string =>
      `${pluralize(occupied, "plaza ocupada", "plazas ocupadas")} de ${total} entre ${from} y ${to}, sin contar esta solicitud`,
    stopFallback: (n: number): string => `Parada ${n}`,
    profileAndTalk: "Ver perfil y hablar",
    openDetailA11y: (name: string): string => `Ver la solicitud de ${name}`,
    profileAndTalkA11y: (name: string): string => `Ver el perfil de ${name} y hablar con esta persona`,
    accept: "Aceptar",
    reject: "Rechazar",
    acceptAll: "Aceptar todas",
    rejectAll: "Rechazar",
    acceptA11y: (name: string): string => `Aceptar la solicitud de ${name}`,
    rejectA11y: (name: string): string => `Rechazar la solicitud de ${name}`,
    acceptAllA11y: (name: string): string => `Aceptar todos los viajes de la reserva semanal de ${name}`,
    rejectAllA11y: (name: string): string => `Rechazar la reserva semanal de ${name}`,
    accepting: "Aceptando…",
    rejecting: "Rechazando…",
    mutualNote: ["La aceptación debe ser mutua.", "No se aplican cambios unilaterales de hora o precio."] as readonly string[],
    ratingNew: "Nuevo",
    messageTitle: (name: string): string => `Mensaje de ${name}`,
    weeklyBadge: "Reserva semanal",
    weeklySummary: (days: string, occurrences: number): string => `${days} · ${pluralize(occurrences, "viaje")}`,
    weeklyLegs: (legs: readonly ("outbound" | "return")[]): string =>
      legs.length === 2 ? "Ida y vuelta" : legs[0] === "return" ? "Solo vuelta" : "Solo ida",
    weeklyStart: (date: string): string => `Desde el ${date}`,
    dayLabel: (label: string): string => label,
    blocked: {
      NO_CAPACITY_ON_SEGMENT: "Ya no queda plaza en ese tramo.",
      TRIP_NOT_BOOKABLE: "Este viaje ya no admite solicitudes.",
    } as Record<string, string>,
    blockedFallback: "No se puede aceptar esta solicitud ahora.",
    holdTitle: "Plaza retenida",
    holdMessage: (name: string, countdown: string): string => `${name} tiene ${countdown} para pagar y confirmar la reserva.`,
    holdMessageNoClock: (name: string): string => `Esperamos el pago de ${name} para confirmar la reserva.`,
    holdCountdown: (seconds: number): string => formatCountdown(seconds),
    holdExpired: "El tiempo para pagar ha terminado. La plaza vuelve a estar libre.",
    holdNotPaid: "Aceptar no confirma la reserva: queda confirmada cuando el pasajero paga.",
    acceptedToast: (name: string): string => `Has aceptado a ${name}. Tiene 15 minutos para pagar.`,
    acceptedToastClock: (name: string, countdown: string): string => `Has aceptado a ${name}. Tiene ${countdown} para pagar.`,
    acceptedWeeklyToast: (name: string): string => `Has aceptado la reserva semanal de ${name}. Tiene 15 minutos para pagar.`,
    rejectedToast: (name: string): string => `Has rechazado la solicitud de ${name}.`,
    rejectedWeeklyToast: (name: string): string => `Has rechazado la reserva semanal de ${name}.`,
    confirmRejectTitle: (name: string): string => `¿Rechazar a ${name}?`,
    confirmRejectMessage: (name: string): string =>
      `${name} recibirá un aviso y no se le cobrará nada. No podrás deshacerlo.`,
    confirmRejectWeeklyMessage: (name: string): string =>
      `Se rechazarán todos los viajes de la reserva semanal de ${name}. No se le cobrará nada y no podrás deshacerlo.`,
    confirmRejectAction: "Rechazar",
    confirmAcceptWeeklyTitle: (name: string): string => `¿Aceptar la reserva semanal de ${name}?`,
    confirmAcceptWeeklyMessage: (trips: number): string =>
      `Se aceptan los ${trips} viajes a la vez: o todos o ninguno. El pasajero tendrá 15 minutos para pagar.`,
    confirmAcceptWeeklyAction: "Aceptar todas",
    noCapacityDates: (dates: string): string => `Ya no queda plaza el ${dates}.`,
    errorTitle: "No hemos podido completar la acción",
    emptyTitle: "No tienes solicitudes pendientes",
    emptyMessage: "Cuando alguien pida plaza en tus viajes, la verás aquí para aceptarla o rechazarla.",
    emptyAction: "Ver mis viajes",
    sectionPending: "Esperando tu respuesta",
    sectionPayment: "Esperando el pago",
    forTrip: (label: string): string => `Viaje de las ${label}`,
    filterTripNote: "Solo solicitudes de este viaje",
    filterTripClear: "Ver todas",
  },

  // ── Errores propios del paquete (ver logic/errors.ts) ────────────────────────────────────────────────────────────────
  errors: {
    plateTaken: "Ya hay un vehículo registrado con esa matrícula.",
    plateTakenTitle: "Matrícula ya registrada",
    vehicleInvalid: "Revisa la marca, el modelo y el color del vehículo.",
    plateInvalid: "Revisa la matrícula. Ejemplo: 1234 ABC",
    seatsInvalid: "Elige entre 1 y 8 plazas.",
    vehicleMissing: "No encontramos ese vehículo. Puede que ya no exista.",
    driverRole: "Necesitas el perfil de conductor para hacer esto.",
    tooManyStops: "Puedes añadir hasta 10 paradas intermedias.",
    seatsExceedVehicle: "No puedes ofrecer más plazas de las que tiene tu vehículo.",
    outsideProvince: "Un punto de la ruta está fuera de la provincia. Corrígelo para guardar.",
    routeLeavesProvince: "La ruta sale de la provincia. Elige puntos y paradas de una misma provincia.",
    noRouteWithinProvince: "No hemos encontrado una ruta que se quede dentro de la provincia.",
    routeTooShort: "El origen y el destino están demasiado cerca para publicar una ruta.",
    startInPast: "El primer viaje no puede ser en el pasado. Elige otra fecha u hora.",
    oneOffDateRequired: "Elige el día del viaje.",
    invalidDateRange: "La fecha final no puede ser anterior a la de inicio.",
    invalidTime: "Revisa la hora de salida.",
    mapsUnavailable: "No podemos calcular rutas ahora mismo. Inténtalo en unos minutos.",
    provinceMissing: "No encontramos esa provincia.",
    requestNotPending: "Esta solicitud ya no está pendiente: el pasajero la ha retirado o ya se respondió.",
    requestMissing: "No encontramos esta solicitud. Puede que ya no esté disponible.",
    inWeekly: "Esta solicitud forma parte de una reserva semanal: se acepta o se rechaza entera.",
    tripNotBookable: "Este viaje ya no admite solicitudes.",
    tripNotBookableTitle: "Viaje no disponible",
    uploadExpired: "La subida ha caducado. Vuelve a intentarlo.",
    uploadType: "Ese formato no está permitido.",
    uploadSize: "El archivo supera el tamaño permitido (20 MB).",
    uploadRate: "Has hecho demasiados intentos. Espera un momento e inténtalo de nuevo.",
    storageOff: "Ahora mismo no podemos guardar archivos. Inténtalo más tarde.",
    uploadFailed: "No hemos podido subir el archivo. Comprueba tu conexión e inténtalo de nuevo.",
    documentInReview: "Ya tienes un documento en revisión. Te avisaremos cuando lo revisemos.",
    alreadyVerified: "Tu identidad ya está verificada.",
    idempotencyReused: "Esta petición ya se había enviado con otros datos. Vuelve a intentarlo.",
    notReadyTitle: "Aún no puedes publicar",
    notReady: "Completa los requisitos para publicar rutas.",
    notReadyWith: (names: string): string => `Para publicar te falta: ${names}.`,
    noCapacityTitle: "Ya no queda plaza",
    noCapacity: "Ya no queda plaza en ese tramo.",
    noCapacityOn: (dates: string): string => `Ya no queda plaza el ${dates}.`,
  },

  // ── Detalle de la solicitud ──────────────────────────────────────────────────────────────────────────────────────────
  requestDetail: {
    title: "Detalle de la solicitud",
    loading: "Cargando la solicitud",
    notFoundTitle: "No encontramos la solicitud",
    notFoundMessage: "Puede que ya no esté disponible o que el pasajero la haya retirado.",
    notFoundAction: "Ver solicitudes",
    passenger: "Pasajero",
    since: (date: string): string => `Solicitud del ${date}`,
    trip: "Tramo",
    boardAt: "Sube en",
    leaveAt: "Se baja en",
    category: "Tipo de viaje",
    day: "Día",
    detour: "Desvío estimado",
    occupancy: "Plazas ocupadas",
    message: "Mensaje del pasajero",
    messageNone: "No ha dejado ningún mensaje.",
    weekly: "Reserva semanal",
    status: "Estado",
    talk: "Hablar con",
    talkLocked: (name: string): string => `Podrás hablar con ${name} cuando se confirme la reserva.`,
    talkOpen: (name: string): string => `Hablar con ${name}`,
    talkError: "No hemos podido abrir la conversación. Inténtalo de nuevo.",
    photoNotApproved: "Foto no disponible",
    ratingLine: (rating: string, count: number): string => `${rating} (${count})`,
  },
} as const;

export type PublishStrings = typeof publishStrings;
