import { DomainError } from "../../errors.js";

/** Códigos estables del módulo (documentados en docs/contracts/trips.md; la app mapea por `code`). */
export type TripsCode =
  | "VALIDATION_ERROR" | "RATE_LIMITED" | "BAD_REQUEST" | "INVALID_CURSOR"
  | "PROVINCE_NOT_FOUND" | "ORIGIN_OUTSIDE_PROVINCE" | "DESTINATION_OUTSIDE_PROVINCE"
  | "SEARCH_DATE_REQUIRED" | "INVALID_SEARCH_WEEKDAYS" | "INVALID_TIME"
  | "TRIP_NOT_FOUND" | "TRIP_NOT_BOOKABLE" | "TRIP_NOT_OWNED" | "DRIVER_CANNOT_REQUEST_OWN_TRIP"
  | "NO_CAPACITY_ON_SEGMENT" | "DUPLICATE_OPEN_REQUEST"
  | "INVALID_REQUEST_SHAPE" | "INVALID_SEGMENT_RANGE"
  | "PICKUP_POINT_INVALID" | "PICKUP_POINT_OUTSIDE_PROVINCE" | "PICKUP_NOT_ON_ROUTE" | "PICKUP_DETOUR_TOO_LARGE"
  | "DROPOFF_STOP_INVALID" | "DROPOFF_BEFORE_PICKUP"
  | "IDEMPOTENCY_KEY_REUSED" | "IDEMPOTENCY_KEY_INVALID"
  | "REQUEST_NOT_FOUND" | "REQUEST_NOT_WITHDRAWABLE" | "REQUEST_NOT_PENDING" | "REQUEST_IN_WEEKLY_RESERVATION"
  | "WEEKLY_RESERVATION_NOT_FOUND" | "TRIP_NOT_RECURRING" | "SERIES_HAS_NO_RETURN"
  | "WEEKLY_OCCURRENCE_UNAVAILABLE" | "WEEKLY_WEEKDAY_NOT_OFFERED" | "WEEKLY_NO_OCCURRENCES"
  | "WEEKLY_START_DATE_IN_PAST" | "INVALID_CANCELLATION_POLICY_VERSION"
  | "DRIVER_NOT_READY" | "VEHICLE_NOT_FOUND" | "VEHICLE_NOT_OWNED" | "OFFERED_SEATS_EXCEED_VEHICLE"
  | "ROUTE_POINT_OUTSIDE_PROVINCE" | "NO_ROUTE_WITHIN_PROVINCE" | "PUBLISH_START_DATE_IN_PAST"
  | "ONE_OFF_DATE_REQUIRED" | "TOO_MANY_STOPS" | "MAPS_PROVIDER_UNAVAILABLE" | "ROUTE_TOO_SHORT" | "INVALID_DATE_RANGE"
  | "FAVORITE_NOT_FOUND" | "FAVORITES_LIMIT_REACHED" | "FAVORITE_IN_USE" | "FAVORITE_OUTSIDE_PROVINCES"
  | "ROUTINE_ENTRY_NOT_FOUND" | "ROUTINE_ENTRY_EXISTS" | "ROUTINE_LIMIT_REACHED" | "ROUTINE_SAME_PLACE"
  | "INVALID_WEEK_START" | "AUTH_FORBIDDEN" | "EMPTY_UPDATE";

/** Crea un DomainError con código tipado y mensaje en español apto para mostrar al usuario. */
export function err(code: TripsCode, status: number, message: string, details?: unknown): DomainError {
  return new DomainError(code, message, status, details);
}
