/**
 * Textos del paquete «solicitar plaza y pagar» (pantallas 13 Punto de recogida · 14 Tu plaza semanal · 15 Revisa tu
 * solicitud · 16 Estado y pago · Procesando el pago · Resultado del pago). Los literales de las láminas se copian TAL
 * CUAL («Elegir punto», «Enviar solicitud», «Pagar reserva», «Por definir», «ejemplo»…).
 *
 * Reglas de voz (BUILD_BRIEF §2): una solicitud no es una reserva; nunca se promete un cobro, una devolución ni una plaza
 * que el servidor no haya confirmado; los errores no culpan a la persona.
 */
import { formatCountdown, formatDateLong, formatDayMonth, formatDistance, pluralize, strings } from "@/i18n";

const common = strings.common;

export const requestStrings = {
  common: {
    retry: common.retry,
    close: common.close,
    cancel: common.cancel,
    back: strings.a11y.back,
    offlineTitle: strings.connectivity.offlineTitle,
    offlineDetail: "Necesitamos conexión para esta pantalla. Cuando vuelva la red se actualizará sola.",
    loadError: "No hemos podido cargar los datos.",
    guestTitle: "Crea tu cuenta para solicitar plaza",
    guestMessage: "Con una cuenta puedes ver los puntos de recogida, elegir el tuyo y enviar la solicitud al conductor.",
    guestAction: "Crear cuenta",
    tripUnavailableTitle: "Viaje no disponible",
    tripUnavailableMessage: "Este viaje ya no está disponible. Puede que el conductor lo haya cancelado.",
    seeOtherTrips: "Buscar otro viaje",
    myTrips: "Ir a mis viajes",
    staleDetail: "No hemos podido actualizar los datos. Te mostramos lo último que teníamos.",
    loadingLabel: strings.common.loading,
    perExample: "ejemplo",
    pendingAmount: strings.money.pending,
    moreInfo: strings.a11y.moreInfo,
  },

  // ── 13 · Punto de recogida ─────────────────────────────────────────────────────────────────────────────────────
  pickup: {
    title: "Punto de recogida",
    panelTitle: "Puntos de recogida propuestos",
    choose: "Elegir punto",
    legendCar: "Ruta del conductor",
    legendWalk: "Trayecto a pie desde el punto",
    safetyFallback: "Comprueba que el punto permite una parada segura y legal.",
    recommended: "Recomendado",
    mapLabel: "Mapa con el recorrido del coche y los puntos de recogida propuestos",
    walk: (minutes: number): string => `${minutes} min a pie`,
    detour: (minutes: number): string => `Desvío +${minutes} min`,
    detailLine: (walkMinutes: number, detourMinutes: number): string => `${walkMinutes} min a pie · Desvío +${detourMinutes} min`,
    pinChip: (distanceM: number): string => `A ${formatDistance(distanceM)} de tu destino`,
    /** Mismo texto en dos líneas, para la etiqueta del mapa. */
    pinChipTitle: (distanceM: number): string => `A ${formatDistance(distanceM)}\nde tu destino`,
    walkChip: (minutes: number): string => `${minutes} min`,
    boardsAt: (time: string): string => `Te recoge a las ${time}`,
    proposalLabel: (code: string): string => `Punto ${code}`,
    selectedHint: "Seleccionado",
    selectHint: "Toca para elegir este punto de recogida",
    unnamed: "Punto de encuentro en la ruta",
    emptyTitle: "No hay puntos de recogida cerca",
    emptyMessage: "El conductor no puede recogerte cerca de ese lugar. Prueba con otro punto de partida.",
    emptyAction: "Cambiar punto de partida",
    originTitle: "¿Desde dónde sales?",
    originMessage: "Indica tu punto de partida y te proponemos dónde puede recogerte el conductor.",
    originUseLocation: "Usar mi ubicación",
    originSearch: "Buscar un lugar",
    originSearchTitle: "Punto de partida",
    originChange: "Cambiar punto de partida",
    originChangeShort: "Cambiar",
    originFrom: (label: string): string => `Desde ${label}`,
    locating: "Buscando tu ubicación…",
    myLocation: "Mi ubicación",
    locationDeniedTitle: "No tenemos tu ubicación",
    locationDeniedMessage: "Puedes buscar tu punto de partida a mano; no hace falta activar la ubicación.",
    locationBlockedMessage: "La ubicación está desactivada para MVC en los ajustes del móvil. Puedes activarla ahí o buscar tu punto de partida a mano.",
    locationOffMessage: "La ubicación del móvil está desactivada. Actívala o busca tu punto de partida a mano.",
    locationUnavailableMessage: "Ahora mismo no hemos podido obtener tu ubicación. Prueba otra vez o busca tu punto de partida a mano.",
    locationAllow: "Permitir ubicación",
    locationSettings: "Abrir ajustes",
    locationRetry: "Probar otra vez",
    tripNotBookable: "Este viaje ya no admite solicitudes de plaza.",
    ownTrip: "Es tu propio viaje: no puedes solicitar plaza en él.",
  },

  // ── 14 · Tu plaza semanal ──────────────────────────────────────────────────────────────────────────────────────
  weekly: {
    title: "Tu plaza semanal",
    daysTitle: "Días de la semana",
    outbound: "Ida (mañana)",
    returnLeg: "Vuelta (tarde)",
    legFrom: (from: string, to: string): string => `Desde ${from} hasta ${to}.`,
    pickupPoint: (code: string | null): string => (code === null ? "tu punto de recogida" : `punto de recogida ${code}`),
    startTitle: "Inicio de la reserva",
    exceptionsTitle: "Fechas con excepciones (opcional)",
    exceptionsRow: "Añadir fechas (vacaciones, festivos, etc.)",
    exceptionsCount: (n: number): string => `${pluralize(n, "fecha")} con excepciones`,
    banner: "La plaza se reserva los días acordados.",
    cancellation: "Condiciones de cancelación",
    cancellationTitle: "Condiciones de cancelación",
    cancellationMessage:
      "Todavía no hay condiciones de cancelación aprobadas, así que no se aplica ninguna penalización ni se promete ningún reembolso. Cuando existan, las verás aquí antes de confirmar la reserva.",
    cancellationClose: "Entendido",
    legEdit: (label: string): string => `${label}. Cambiar`,
    startEdit: (date: string): string => `Inicio de la reserva: ${date}. Cambiar`,
    exceptionsEdit: "Fechas con excepciones. Cambiar",
    daysOffered: "Los días atenuados no los hace el conductor.",
    continue: strings.common.continue,
    checking: "Comprobando las plazas de cada día…",
    pickerStartTitle: "Inicio de la reserva",
    pickerStartHint: "Elige el primer día en que necesitas la plaza.",
    pickerStartDay: (iso: string): string => formatDateLong(iso),
    pickerExceptionsTitle: "Fechas con excepciones",
    pickerExceptionsHint: "Marca los días en los que no necesitarás la plaza (vacaciones, festivos…). No se solicitarán.",
    pickerExceptionsClear: "Quitar todas",
    pickerExceptionsSave: "Guardar fechas",
    pickerExceptionsEmpty: "No hay días de reserva que marcar con los días y el inicio elegidos.",
    pickerDone: "Elegir este día",
    weeksTitle: "Semanas a reservar",
    weeksValue: (n: number): string => pluralize(n, "semana"),
    weeksLess: "Una semana menos",
    weeksMore: "Una semana más",
    legSheetTitle: (label: string): string => label,
    legSheetInclude: "Incluir este trayecto",
    legSheetKeepOne: "Debe quedar al menos un trayecto.",
    legSheetNoReturn: "El conductor no ofrece este trayecto.",
    legSheetBoards: (time: string): string => `Te recoge a las ${time}`,
    legSheetArrives: (time: string): string => `Llegas sobre las ${time}`,
    changeDays: "Cambiar días",
    daysSheetTitle: "Días de tu reserva",
    daysSheetHint: "Se envía una solicitud por cada día. Así está cada uno ahora mismo:",
    dayAvailable: "Hay plaza",
    dayRequested: "Ya solicitado",
    dayException: "Excepción",
    dayFull: "Sin plaza",
    dayPast: "Ya ha pasado",
    dayNoTrip: "Sin viaje",
    daySeats: (n: number): string => pluralize(n, "plaza libre", "plazas libres"),
    partialTitle: (n: number): string => `${pluralize(n, "día")} sin plaza`,
    partialMessage: (dates: string): string => `No hay plaza para: ${dates}. Puedes reservar solo los días con plaza o cambiar las fechas.`,
    partialSwitch: "Reservar solo los días con plaza",
    partialSwitchHint: "Se omiten los días sin plaza y se solicitan los demás.",
    partialSeeDays: "Ver días",
    noneTitle: "No hay plaza en esos días",
    noneMessage: "El conductor no tiene plazas libres con los días y el inicio elegidos. Cambia los días o la fecha de inicio.",
    noDaysTitle: "Elige al menos un día",
    noDaysMessage: "Marca los días de la semana en los que necesitas la plaza.",
    notRecurringTitle: "Este viaje no es semanal",
    notRecurringMessage: "El conductor ofrece este viaje solo una vez. Puedes solicitar la plaza para ese día.",
    notRecurringAction: "Solicitar para un día",
    dayNotOffered: (day: string): string => `El conductor no hace este viaje los ${day}.`,
    issueOn: (message: string, date: string): string => `${message} (${date})`,
    validationDays: "Elige al menos un día de la semana.",
    validationLegs: "Elige al menos un trayecto: ida o vuelta.",
    validationStart: "Elige una fecha de inicio que no haya pasado.",
    validationNoOccurrences: "Con estos días y fechas no queda ningún día que reservar.",
    dateList: (dates: readonly string[]): string => {
      const labels = dates.map((d) => formatDayMonth(d));
      if (labels.length <= 1) return labels.join("");
      return `${labels.slice(0, -1).join(", ")} y ${labels[labels.length - 1] ?? ""}`;
    },
  },

  // ── 15 · Revisa tu solicitud ───────────────────────────────────────────────────────────────────────────────────
  review: {
    title: "Revisa tu solicitud",
    distance: "Distancia estimada (ida)",
    driver: "Conductor",
    drivesHabitually: "Conduce este trayecto habitualmente.",
    drivesOnce: "Viaje puntual.",
    ratings: (count: number): string => `(${pluralize(count, "valoración", "valoraciones")})`,
    noRatings: "Sin valoraciones todavía",
    originFallback: "Origen",
    destinationFallback: "Destino",
    seat: "Tu plaza",
    seatWeekdays: (days: string): string => days,
    seatLegs: (outbound: string | null, back: string | null): string => {
      const parts: string[] = [];
      if (outbound !== null) parts.push(`Ida ${outbound}`);
      if (back !== null) parts.push(`Vuelta ${back}`);
      return parts.join(" · ");
    },
    seatSingle: (iso: string): string => formatDateLong(iso),
    seatSingleTimes: (boards: string, arrives: string): string => `Recogida ${boards} · Llegada ${arrives}`,
    pickup: "Punto de recogida",
    pickupWalk: (minutes: number): string => `(${minutes} min a pie)`,
    pickupFallbackName: "Punto de recogida elegido",
    dropoff: "Destino",
    detailTitle: "Detalle de la aportación (ejemplo)",
    detailTitleDefined: "Detalle de la aportación",
    contribution: "Aportación según recorrido",
    contributionExample: (distanceM: number): string => `Ejemplo orientativo (${formatDistance(distanceM)})`,
    contributionDistance: (distanceM: number): string => `Según recorrido (${formatDistance(distanceM)})`,
    managementFee: "Gestión MVC · Por definir",
    managementFeeDefined: "Gestión MVC",
    totalSingle: "Total antes de confirmar",
    totalWeekly: "Total · Pendiente de tarifa final",
    totalWeeklyDefined: "Total por semana",
    weeklyRate: (perKm: string): string => `Ejemplo · ${perKm}`,
    weeklyRateDefined: (perKm: string): string => `Tarifa · ${perKm}`,
    weeklyPerTrip: (distance: string, amount: string): string => `${distance} por trayecto · ${amount}`,
    weeklyPerWeek: (days: number, legsPerDay: 1 | 2, amount: string): string =>
      `${pluralize(days, "día")}, ${legsPerDay === 2 ? "ida y vuelta" : "solo ida"} · ${amount}/semana`,
    weeklyPerWeekPending: (days: number, legsPerDay: 1 | 2, amount: string): string =>
      `${pluralize(days, "día")}, ${legsPerDay === 2 ? "ida y vuelta" : "solo ida"} · ${amount}`,
    feeHelpTitle: "¿Qué es la gestión MVC?",
    feeHelpMessage:
      "Es lo que MVC cobra por gestionar la reserva y el pago. Todavía no está definida: cuando lo esté, la verás aquí antes de confirmar nada.",
    feeHelpClose: "Entendido",
    warningTitle: "El conductor debe aceptar tu solicitud.",
    warningMessage: "No se realiza ningún cobro todavía.",
    send: "Enviar solicitud",
    sending: "Enviando solicitud…",
    messageTitle: (name: string): string => `Mensaje para ${name}`,
    messageHint: "Opcional. Lo verá el conductor junto con tu solicitud.",
    messagePlaceholder: "Por ejemplo: llevo una mochila pequeña.",
    messageSave: "Guardar mensaje",
    messageRemove: "Quitar mensaje",
    messageAdded: "Mensaje añadido",
    messageLimit: (count: number, max: number): string => `${count}/${max}`,
    driverSheetVehicle: "Vehículo",
    driverSheetSeeTrip: "Ver el viaje",
    daysSheetOpen: "Ver los días de la reserva",
    dropoffSheetTitle: "¿Dónde bajas?",
    dropoffArrives: (time: string): string => `Llegas sobre las ${time}`,
    seatSheetSingleHint: "Esta es la plaza que solicitas. El conductor decidirá si la acepta.",
    sendOffline: "Sin conexión no podemos enviar la solicitud. Cuando vuelva la red, pulsa «Reintentar»: no se enviará dos veces.",
    blockedTitle: "No se puede enviar la solicitud",
    openRequestTitle: "Ya tienes una solicitud en este viaje",
    openRequestMessage: "Mientras esté abierta no puedes enviar otra igual.",
    openRequestAction: "Ver mi solicitud",
    noSeats: "Ya no quedan plazas libres en este tramo.",
    ownTrip: "Es tu propio viaje: no puedes solicitar plaza en él.",
    notBookable: "Este viaje ya no admite solicitudes de plaza.",
    authRequired: "Crea tu cuenta para enviar la solicitud.",
    duplicateTitle: "Ya tienes una solicitud abierta",
    duplicateMessage: "Ya has solicitado plaza en este viaje. Mira cómo va en Mis viajes.",
    sentToast: "Solicitud enviada. Te avisamos cuando el conductor responda.",
    weeklySentToast: (n: number): string => `${pluralize(n, "solicitud", "solicitudes")} enviadas. Te avisamos cuando el conductor responda.`,
    partialSentToast: (sent: number, skipped: number): string =>
      `${pluralize(sent, "solicitud", "solicitudes")} enviadas; ${pluralize(skipped, "día")} sin plaza ${skipped === 1 ? "se ha omitido" : "se han omitido"}.`,
  },

  // ── 16 · Estado y pago ─────────────────────────────────────────────────────────────────────────────────────────
  status: {
    title: "Estado y pago",
    steps: ["Solicitud", "Aceptada", "Pago", "Confirmada"] as const,
    accepted: "¡Solicitud aceptada!",
    acceptedBy: (name: string): string => `${name} ha aceptado tu solicitud.`,
    acceptedWeeklyBy: (name: string): string => `${name} ha aceptado tus solicitudes.`,
    holdTitle: "Tu plaza queda reservada provisionalmente durante",
    holdInfo: "Completa el pago para confirmar la plaza. Si no pagas a tiempo, la reserva se liberará.",
    holdSeconds: (seconds: number): string => formatCountdown(seconds),
    holdA11y: (seconds: number): string => `Tiempo restante de la reserva provisional: ${formatCountdown(seconds)}`,
    methodTitle: "Método de pago",
    methodApplePay: "Apple Pay",
    methodGooglePay: "Google Pay",
    methodCard: "Tarjeta",
    methodUnavailable: "No disponible",
    methodSaved: (label: string): string => label,
    summaryTitle: "Resumen del pago",
    summaryExampleTitle: "Ejemplo de pago",
    summaryAmountPending: "Importe por definir",
    summaryContribution: "Tu aportación",
    summaryContributionExample: "Tu aportación (ejemplo)",
    summaryWeeklyContributionExample: "Aportación semanal (ejemplo)",
    summaryWeeklyContribution: "Aportación semanal",
    summaryFee: "Gestión MVC",
    summaryTotal: "Total",
    pay: "Pagar reserva",
    paying: "Abriendo el pago…",
    payBlocked: "Pago no disponible",
    rejectedBandTitle: "Si la solicitud es rechazada",
    rejectedBandMessage: "Te avisaremos y no se realizará ningún cobro.",
    // pendiente de respuesta
    waitingTitle: (name: string): string => `Esperando a ${name}`,
    waitingMessage: "El conductor tiene que aceptar tu solicitud. No se realiza ningún cobro todavía.",
    waitingSince: (time: string): string => `Enviada a las ${time}`,
    withdraw: "Retirar solicitud",
    withdrawTitle: "¿Retirar tu solicitud?",
    withdrawMessage: (name: string): string => `Dejarás de esperar la respuesta de ${name}. No se ha realizado ningún cobro.`,
    withdrawConfirm: "Retirar solicitud",
    withdrawKeep: "Mantener solicitud",
    withdrawn: "Solicitud retirada",
    withdrawnTitle: "Has retirado tu solicitud",
    withdrawnMessage: "No se ha realizado ningún cobro. Puedes buscar otro viaje cuando quieras.",
    // finales no felices
    rejectedTitle: (name: string): string => `${name} no ha podido aceptar tu solicitud`,
    rejectedMessage: "No se ha realizado ningún cobro. Prueba con otro viaje a la misma hora.",
    expiredRequestTitle: "La solicitud ha caducado",
    expiredRequestMessage: "El conductor no respondió a tiempo. No se ha realizado ningún cobro.",
    holdExpiredTitle: "La reserva provisional ha caducado",
    holdExpiredMessage: "No llegaste a pagar a tiempo y la plaza se ha liberado. No se ha realizado ningún cobro por esta solicitud.",
    paymentLateTitle: "Tu pago llegó con la reserva ya caducada",
    paymentLateMessage:
      "La plaza se había liberado, así que no se ha creado ninguna reserva. Revisaremos el pago y te lo comunicaremos; no hace falta que hagas nada más.",
    confirmedTitle: "¡Plaza confirmada!",
    confirmedMessage: (name: string): string => `Tu plaza con ${name} está reservada.`,
    confirmedAction: "Ver mi reserva",
    paymentOpenTitle: "Hay un pago en curso",
    paymentOpenMessage: "Estamos esperando la confirmación del pago. Hasta que llegue no se marca como pagado.",
    paymentOpenAction: "Ver estado del pago",
    // reserva semanal
    weeklyPendingTitle: (name: string): string => `Esperando a ${name}`,
    weeklyDays: (n: number): string => pluralize(n, "día"),
    weeklyConfirmedCount: (confirmed: number, total: number): string => `${confirmed} de ${total} confirmados`,
    partiallyConfirmedTitle: "Reserva semanal confirmada en parte",
    partiallyConfirmedMessage: "Algunos días están confirmados y otros no. Revisa el detalle de la reserva.",
    seeWeekly: "Ver la reserva semanal",
    // bloqueo por proveedor / importe
    blockedTitle: "Pagos aún no disponibles",
    blockedProviderMessage: "Tu plaza sigue reservada provisionalmente, pero todavía no se puede cobrar. Esto no depende de ti: en cuanto se active el cobro podrás pagar aquí.",
    blockedAmountMessage: "El importe de esta reserva todavía no está definido, así que no se puede cobrar. Tu plaza sigue reservada mientras dure la cuenta atrás.",
    blockedState: "Bloqueado",
    blockedHint: "Por qué no se puede pagar ahora mismo",
    blockedMethodMessage: "El método que has elegido no está disponible ahora mismo. Prueba con otro.",
    blockedGeneric: "Ahora mismo no se puede iniciar el pago. Inténtalo de nuevo en unos minutos.",
    loadingContext: "Preparando el pago…",
    contextError: "No hemos podido preparar el pago.",
    notFoundTitle: "Solicitud no encontrada",
    notFoundMessage: "No encontramos esta solicitud. Puede que ya no exista o que no sea tuya.",
    sdkUnsupportedTitle: "Este móvil aún no puede completar el pago",
    sdkUnsupportedMessage: "Hemos creado el pago, pero esta versión de la app no puede mostrar la hoja de pago. Hasta que el servidor lo confirme no se marca como pagado.",
    payFailedTitle: "No hemos podido iniciar el pago",
    paymentCancelled: "Has cancelado el pago. Tu plaza sigue reservada hasta que acabe la cuenta atrás.",
    updated: (time: string): string => `Actualizado a las ${time}`,
    stepA11y: (label: string, state: string): string => `${label}: ${state}`,
  },

  // ── Procesando el pago ─────────────────────────────────────────────────────────────────────────────────────────
  processing: {
    title: "Procesando el pago",
    heading: "Estamos confirmando tu pago",
    message: "Esperamos la confirmación del banco. Puede tardar unos segundos; no cierres la app.",
    messageWeekly: (done: number, total: number): string => `Confirmados ${done} de ${total} pagos. No cierres la app.`,
    holdLeft: "Tiempo de la reserva provisional",
    note: "El pago solo se marca como realizado cuando lo confirma el servidor.",
    slowTitle: "Está tardando más de lo normal",
    slowMessage: "Seguimos comprobándolo. No pagues otra vez: si el pago se confirma, lo verás aquí.",
    timeoutTitle: "No hemos podido confirmar el pago todavía",
    timeoutMessage:
      "Todavía no tenemos la confirmación. No lo damos por pagado ni por fallido. Puedes volver a comprobarlo o mirar el estado de tu solicitud; cuando el banco responda, lo verás reflejado.",
    check: "Volver a comprobar",
    seeStatus: "Ver estado de la solicitud",
    leave: "Salir y comprobar después",
    offlineTitle: "Sin conexión mientras confirmamos el pago",
    offlineDetail: "No pierdes nada: el pago sigue su curso en el servidor. Volveremos a comprobarlo cuando haya red.",
    errorTitle: "No hemos podido comprobar el pago",
    a11yWorking: "Confirmando el pago. Espera unos segundos.",
  },

  // ── Resultado del pago ─────────────────────────────────────────────────────────────────────────────────────────
  result: {
    title: "Resultado del pago",
    confirmedTitle: "¡Plaza confirmada!",
    confirmedMessage: "El servidor ha confirmado tu pago y tu plaza está reservada.",
    confirmedWeeklyMessage: (confirmed: number): string => `Se ha confirmado el pago de ${pluralize(confirmed, "día")} de tu reserva semanal.`,
    paidAmount: "Importe pagado",
    method: "Método",
    receiptNote: "Tienes el justificante en tu historial de pagos.",
    seeBooking: "Ver mi reserva",
    seeWeekly: "Ver la reserva semanal",
    seePayments: "Ver mis pagos",
    pendingTitle: "Pago pendiente de confirmar",
    pendingMessage: "Todavía no tenemos la confirmación definitiva. No se marca como pagado hasta entonces.",
    reviewTitle: "Estamos revisando tu pago",
    reviewMessage: "El pago necesita una revisión por nuestra parte. No hace falta que pagues otra vez; te contaremos el resultado.",
    lateTitle: "El pago llegó tarde",
    lateMessage:
      "La reserva provisional ya había caducado y la plaza se había liberado, así que no se ha creado ninguna reserva. Revisaremos el pago y te lo comunicaremos.",
    failedTitle: "No se ha completado el pago",
    failedMessage: "Tu pago no ha podido realizarse. Comprueba tu método de pago e inténtalo de nuevo.",
    failedCardDeclined: "El banco ha rechazado el pago. Prueba con otra tarjeta u otro método.",
    failedInsufficient: "El banco indica que no hay saldo suficiente. Prueba con otro método.",
    retry: "Reintentar pago",
    changeMethod: "Cambiar método de pago",
    cancelledTitle: "Pago cancelado",
    cancelledMessage: "Has cerrado el pago antes de terminar. Tu plaza sigue reservada hasta que acabe la cuenta atrás.",
    expiredTitle: "El pago ha caducado",
    expiredMessage: "No se completó a tiempo. Si la reserva provisional sigue activa, puedes intentarlo de nuevo.",
    refundedTitle: "Pago devuelto",
    refundedMessage: "El importe de este pago se ha devuelto.",
    partialTitle: "Reserva semanal confirmada en parte",
    partialMessage: (confirmed: number, total: number): string =>
      `Se han confirmado ${confirmed} de ${total} días. Los demás no se han cobrado o están en revisión.`,
    backToRequest: "Volver a la solicitud",
    notFoundTitle: "Pago no encontrado",
    notFoundMessage: "No encontramos este pago. Puede que no sea tuyo o que ya no exista.",
    nothingCharged: "Hasta que el servidor lo confirme, nada se da por cobrado.",
  },

  // ── Errores propios del paquete (se registran en `registerErrorMessages`) ───────────────────────────────────────
  errors: {
    PICKUP_POINT_INVALID: { title: "Punto de recogida no válido", message: "Ese punto de recogida ya no es válido para este viaje. Elige otro." },
    PICKUP_POINT_OUTSIDE_PROVINCE: { title: "Punto fuera de la provincia", message: "El punto de recogida está fuera de la provincia. Elige otro." },
    PICKUP_NOT_ON_ROUTE: { title: "Punto fuera de la ruta", message: "El conductor no pasa por ese punto. Elige uno de los propuestos." },
    PICKUP_DETOUR_TOO_LARGE: { title: "Desvío demasiado grande", message: "Ese punto obliga al conductor a desviarse más de lo que acepta. Elige otro." },
    DROPOFF_STOP_INVALID: { title: "Destino no válido", message: "La parada de destino no es válida para este viaje." },
    DROPOFF_BEFORE_PICKUP: { title: "Destino antes de la recogida", message: "El destino debe estar después del punto de recogida." },
    INVALID_REQUEST_SHAPE: { title: "Solicitud incompleta", message: "Falta algún dato de la solicitud. Vuelve a elegir el punto de recogida." },
    INVALID_SEGMENT_RANGE: { title: "Tramo no válido", message: "El tramo elegido no es válido para este viaje." },
    DRIVER_CANNOT_REQUEST_OWN_TRIP: { title: "Es tu propio viaje", message: "No puedes solicitar plaza en un viaje que conduces tú." },
    DUPLICATE_OPEN_REQUEST: { title: "Ya tienes una solicitud abierta", message: "Ya has solicitado plaza en este viaje. Mira cómo va en Mis viajes." },
    REQUEST_NOT_FOUND: { title: "Solicitud no encontrada", message: "No encontramos esta solicitud. Puede que ya no exista." },
    REQUEST_NOT_WITHDRAWABLE: { title: "Ya no se puede retirar", message: "El conductor ya ha respondido a esta solicitud, así que no se puede retirar." },
    WEEKLY_START_DATE_IN_PAST: { title: "Fecha de inicio pasada", message: "El inicio de la reserva no puede ser un día que ya ha pasado." },
    WEEKLY_WEEKDAY_NOT_OFFERED: { title: "Día no ofrecido", message: "El conductor no hace este viaje alguno de los días elegidos." },
    WEEKLY_NO_OCCURRENCES: { title: "Sin días que reservar", message: "Con los días y las fechas elegidos no queda ningún día que reservar." },
    WEEKLY_OCCURRENCE_UNAVAILABLE: { title: "Algún día sin plaza", message: "Al menos uno de los días elegidos ya no tiene plaza. Cambia las fechas o reserva solo los días con plaza." },
    SERIES_HAS_NO_RETURN: { title: "Sin trayecto de vuelta", message: "El conductor no ofrece vuelta en este viaje. Elige solo la ida." },
    TRIP_NOT_RECURRING: { title: "Viaje no semanal", message: "Este viaje se ofrece una sola vez. Solicita la plaza para ese día." },
    INVALID_CANCELLATION_POLICY_VERSION: { title: "Condiciones desactualizadas", message: "Las condiciones de cancelación han cambiado. Vuelve a abrir la pantalla para verlas." },
    PAYMENTS_PROVIDER_DISABLED: { title: "Pagos aún no disponibles", message: "Tu plaza sigue reservada provisionalmente, pero todavía no se puede cobrar." },
    PAYMENT_PROVIDER_UNAVAILABLE: { title: "Pagos aún no disponibles", message: "Tu plaza sigue reservada provisionalmente, pero todavía no se puede cobrar." },
    PAYMENT_AMOUNT_NOT_DEFINED: { title: "Importe por definir", message: "El importe de esta reserva todavía no está definido, así que no se puede cobrar." },
    PAYMENT_ALREADY_OPEN: { title: "Ya hay un pago en curso", message: "Estamos esperando la confirmación de un pago de esta solicitud." },
    PAYMENT_METHOD_NOT_AVAILABLE: { title: "Método no disponible", message: "Ese método de pago no está disponible ahora mismo. Prueba con otro." },
    PAYMENT_NOT_FOUND: { title: "Pago no encontrado", message: "No encontramos este pago." },
    PAYMENT_PROVIDER_ERROR: { title: "El servicio de pago ha fallado", message: "No se ha cobrado nada. Inténtalo de nuevo en unos minutos." },
    REQUEST_NOT_PAYABLE: { title: "Esta solicitud no se puede pagar", message: "La solicitud ya no está pendiente de pago." },
    REQUEST_ALREADY_PAID: { title: "Ya está pagada", message: "Esta solicitud ya tiene la plaza confirmada." },
    HOLD_EXPIRED: { title: "Reserva provisional caducada", message: "La plaza se ha liberado porque no se pagó a tiempo." },
    IDEMPOTENCY_KEY_REQUIRED: { title: "No hemos podido enviarlo", message: "Vuelve a intentarlo." },
    IDEMPOTENCY_KEY_REUSED: { title: "Petición repetida", message: "Esta operación ya se había enviado con otros datos. Vuelve a empezar desde la pantalla anterior." },
  },

  a11y: {
    back: strings.a11y.back,
    pickupMap: "Mapa de puntos de recogida",
    recenter: strings.a11y.locateMe,
    driverRow: (name: string): string => `Conductor ${name}. Toca para añadir un mensaje`,
    routeBar: (from: string, to: string): string => `Trayecto de ${from} a ${to}`,
    pickupHint: "Abre la pantalla para cambiar el punto de recogida",
    dropoffHint: "Abre la lista de paradas para cambiar el destino",
    pay: "Pagar la reserva",
    methodOption: (label: string, selected: boolean): string => `${label}${selected ? ", seleccionado" : ""}`,
    removeException: (label: string): string => `Quitar la excepción del ${label}`,
    dayToggle: (label: string, selected: boolean): string => `${label}${selected ? ", seleccionado" : ""}`,
  },
} as const;

export type RequestStrings = typeof requestStrings;
