/** Textos de «Tu viaje publicado», «Cancelar el viaje», «Proponer una parada» y «Viaje terminado» (conductor). */
import { pluralize } from "@/i18n";

export const tripStrings = {
  manage: {
    title: "Tu viaje publicado",
    loading: "Cargando tu viaje",
    statusPublished: "Publicado",
    statusActive: "En curso",
    statusCompleted: "Terminado",
    statusCancelled: "Cancelado",
    summaryTitle: "Resumen",
    when: "Salida",
    vehicle: "Vehículo",
    seats: "Plazas",
    route: "Ruta",
    routeKm: (distance: string, duration: string): string => `${distance} · ${duration}`,
    stopsTitle: "Paradas",
    optionalSuffix: "(opcional)",
    passengers: "Pasajeros",
    noPassengers: "Aún no hay pasajeros confirmados",
    openConsole: "Abrir consola del viaje",
    requests: "Ver solicitudes",
    propose: "Proponer nueva parada",
    cancel: "Cancelar viaje",
    cancelUnavailable: "Con el viaje en curso no se puede cancelar.",
    recurring: (days: string): string => `Se repite ${days}`,
  },
  cancel: {
    unavailableTitle: "Todavía no se puede cancelar el viaje entero",
    unavailableMessage: "El servidor aún no admite esta acción. Cancela las reservas una a una desde la lista de pasajeros; cada pasajero recibirá el aviso.",
    title: "Cancelar el viaje",
    titleBooking: "Cancelar la reserva",
    intro: "Cuéntanos por qué cancelas. Avisaremos a tus pasajeros de inmediato.",
    introBooking: "Cuéntanos por qué cancelas esta reserva. Avisaremos al pasajero de inmediato.",
    reasonTitle: "Motivo de la cancelación",
    reasons: {
      schedule_change: "Ha cambiado mi horario",
      vehicle_issue: "Problema con el vehículo",
      emergency: "Una emergencia",
      passenger_issue: "Problema con un pasajero",
      other: "Otro motivo",
    },
    noteLabel: "Comentario (opcional)",
    notePlaceholder: "Lo verá el pasajero en el aviso.",
    reasonRequired: "Elige un motivo para continuar.",
    warningTitle: "Qué pasará",
    warningTrip: (confirmed: number): string =>
      confirmed === 0
        ? "Se cerrará el viaje y las solicitudes que sigan abiertas."
        : `Se cancelarán ${pluralize(confirmed, "reserva confirmada", "reservas confirmadas")}. Las devoluciones se abren en revisión: no están garantizadas ni tienen plazo definido.`,
    warningBooking: "La reserva se cancelará y se abrirá una revisión de la devolución. No está garantizada ni tiene plazo definido.",
    submit: "Cancelar viaje",
    submitBooking: "Cancelar reserva",
    keep: "Mantener el viaje",
    dialogTitle: "¿Cancelar el viaje?",
    dialogTitleBooking: "¿Cancelar la reserva?",
    dialogMessage: "Esta acción no se puede deshacer.",
    confirm: "Sí, cancelar",
    back: "No, volver",
    doneTitle: "Viaje cancelado",
    doneTitleBooking: "Reserva cancelada",
    doneMessage: (bookings: number, closed: number): string => {
      const parts: string[] = [];
      if (bookings > 0) parts.push(`${pluralize(bookings, "reserva cancelada", "reservas canceladas")}`);
      if (closed > 0) parts.push(`${pluralize(closed, "solicitud cerrada", "solicitudes cerradas")}`);
      return parts.length > 0 ? `${parts.join(" · ")}. Tus pasajeros ya han recibido el aviso.` : "No había pasajeros que avisar.";
    },
    doneMessageBooking: "El pasajero ya ha recibido el aviso.",
    already: "Ya estaba cancelado: te mostramos el resultado anterior.",
    refundsTitle: "Devoluciones",
    refundReview: "En revisión",
    refundNone: "Sin pago que devolver",
    refundOpened: "Hemos abierto una revisión de la devolución. No está garantizada ni tiene plazo definido.",
    toTrips: "Volver a mis viajes",
    notCancellableTitle: "No se puede cancelar",
    notCancellableMessage: "Solo se puede cancelar un viaje publicado que aún no ha empezado.",
  },
  propose: {
    title: "Proponer una parada",
    intro: "Elige un punto nuevo dentro de la provincia. Calcularemos el desvío y avisaremos a quien le afecte.",
    stopTitle: "Nueva parada",
    stopPlaceholder: "Buscar el lugar de la parada",
    stopChange: "Cambiar",
    stopRequired: "Elige dónde quieres parar.",
    afterTitle: "Después de",
    afterAuto: "Lo decidimos por la ruta (recomendado)",
    noSurcharge: "Sin recargo por esta parada",
    submit: "Enviar propuesta",
    sending: "Calculando el desvío…",
    resultTitleApplied: "Parada añadida",
    resultMessageApplied: "Nadie necesitaba aceptar el cambio, así que ya está aplicado. Hemos avisado a los afectados.",
    resultTitlePending: "Propuesta enviada",
    resultMessagePending: (accepted: number, required: number): string => `${accepted} de ${required} han aceptado`,
    detour: (distance: string, duration: string): string => `Desvío: ${distance} · ${duration}`,
    plannedAt: (time: string): string => `Paso previsto a las ${time}`,
    expires: (time: string): string => `Caduca a las ${time}`,
    participants: "Pasajeros afectados",
    decisionAccepted: "Ha aceptado",
    decisionRejected: "Ha rechazado",
    decisionPending: "Sin responder",
    notRequired: "No necesita aceptar",
    delta: (minutes: number): string => (minutes === 0 ? "Sin cambio de hora" : `${minutes > 0 ? "+" : "−"}${Math.abs(minutes)} min`),
    withdraw: "Retirar propuesta",
    withdrawTitle: "¿Retirar la propuesta?",
    withdrawMessage: "Tus pasajeros dejarán de ver la parada nueva y el viaje sigue como estaba.",
    withdrawConfirm: "Retirar",
    withdrawn: "Propuesta retirada",
    backToConsole: "Volver a la consola",
    statusLabel: {
      pending: "Esperando respuesta",
      accepted: "Aceptada",
      rejected: "Rechazada",
      expired: "Caducada",
      cancelled: "Retirada",
    },
    resolution: {
      auto_applied: "Se aplicó al enviarla.",
      all_accepted: "Todos aceptaron: la parada ya está en la ruta.",
      rejected_by_passenger: "Un pasajero la rechazó: el viaje sigue como estaba.",
      expired: "Nadie respondió a tiempo: el viaje sigue como estaba.",
      cancelled_by_driver: "La retiraste: el viaje sigue como estaba.",
      capacity_lost: "Ya no hay plaza para esa parada: el viaje sigue como estaba.",
      superseded: "Otra propuesta la sustituyó.",
    },
    mapTitle: "Ruta con la parada nueva",
    unavailable: "No se puede proponer una parada ahora mismo.",
  },
  finished: {
    title: "Viaje terminado",
    loading: "Cargando el resumen",
    heroTitle: "Has terminado el viaje",
    heroMessage: (time: string | null): string => (time ? `Terminaste a las ${time}.` : "Gracias por conducir con MVC."),
    pickedUp: "Recogidos",
    noShow: "No presentados",
    passengersTitle: "Pasajeros",
    completedLine: "Trayecto completado",
    noShowLine: "No se presentó a la recogida",
    other: "Sin recogida verificada",
    nothing: "No hubo pasajeros en este viaje.",
    publishAnother: "Publicar otra ruta",
    toTrips: "Volver a mis viajes",
    notYet: "Este viaje aún no ha terminado",
    notYetMessage: "El resumen estará disponible cuando termines el viaje.",
    requests: "Ver solicitudes",
    reportIssue: "Reportar una incidencia",
  },
} as const;
