/**
 * Textos en español (es-ES) de las pantallas de exploración del slice `search` (09 Inicio mapa, 10 Define tu recorrido,
 * 11 Resultados, 12 Detalle del viaje y el buscador de lugares). Los literales de las láminas se copian tal cual
 * («Coches en tu provincia», «Busco coche», «Sin coincidencias», «Propuesta»…).
 *
 * Las funciones devuelven frases con plurales y números ya compuestos para que las pantallas no concatenen textos.
 */
import { pluralize } from "@/i18n";

export const browseStrings = {
  common: {
    retry: "Reintentar",
    cancel: "Cancelar",
    close: "Cerrar",
    createAccount: "Crear cuenta",
    keepExploring: "Seguir explorando",
    back: "Volver",
  },

  province: {
    sheetTitle: "Elige tu provincia",
    sheetSubtitle: "Solo mostramos trayectos dentro de una misma provincia.",
    selected: "Provincia seleccionada",
    a11yChip: (name: string) => `Provincia: ${name}. Cambiar de provincia`,
    loadErrorTitle: "No hemos podido cargar las provincias",
    loadErrorMessage: "Comprueba tu conexión e inténtalo de nuevo.",
    /** Mientras no hay provincia cargada el chip dice esto. */
    loadingChip: "Provincia",
  },

  place: {
    titleOrigin: "Origen",
    titleDestination: "Destino",
    titleGeneric: "Buscar lugar",
    placeholderOrigin: "Tu municipio o dirección",
    placeholderDestination: "Tu destino",
    placeholderGeneric: "Busca un lugar",
    a11yField: "Buscar un lugar",
    minChars: "Escribe al menos 3 letras para buscar.",
    useMyLocation: "Usar mi ubicación",
    useMyLocationHint: "Te sugerimos tu municipio actual.",
    locating: "Buscando tu ubicación…",
    myLocationLabel: "Mi ubicación",
    recent: "Recientes",
    clearRecent: "Borrar",
    results: "Resultados",
    searching: "Buscando…",
    noResultsTitle: "No encontramos ese lugar",
    noResultsMessage: "Prueba con otro nombre, un municipio o una dirección completa.",
    searchErrorTitle: "No hemos podido buscar",
    // Solo se ve si el servidor rechaza la sesión (401): un invitado busca lugares igual que quien tiene cuenta.
    guestTitle: "Entra para buscar lugares",
    guestMessage: "No hemos podido validar tu sesión. Entra con tu móvil o crea tu cuenta para buscar direcciones.",
    offlineDetail: "No podemos buscar lugares ahora",
    locationDeniedTitle: "Necesitamos tu permiso",
    locationDeniedMessage: "Para usar tu ubicación, permite el acceso cuando te lo pida el móvil. Siempre puedes escribir tu municipio.",
    locationBlockedTitle: "Ubicación desactivada para MVC",
    locationBlockedMessage: "Actívala en los ajustes del móvil o escribe tu municipio a mano.",
    locationOffTitle: "Ubicación del móvil apagada",
    locationOffMessage: "Enciende la ubicación del móvil e inténtalo de nuevo, o escribe tu municipio.",
    locationFailedTitle: "No hemos podido ubicarte",
    locationFailedMessage: "Prueba de nuevo en un sitio con mejor cobertura o escribe tu municipio.",
    outsideOriginTitle: "Origen fuera de provincia",
    outsideDestinationTitle: "Destino fuera de provincia",
    outsideGenericTitle: "Fuera de provincia",
    outsideMessage: (provinceName: string) =>
      `Solo hacemos trayectos dentro de la provincia de ${provinceName}. Elige un lugar de esa provincia.`,
    outsideMessageGeneric: "Ese lugar no está en ninguna provincia disponible todavía. Elige un lugar dentro de la provincia.",
    provinceCheckFailed: "No hemos podido comprobar la provincia de ese lugar. Inténtalo de nuevo.",
    resultA11y: (title: string, subtitle: string | null) => (subtitle ? `${title}. ${subtitle}` : title),
    allowLocation: "Permitir ubicación",
    openSettings: "Abrir ajustes",
    typeToSearch: "Escribe un municipio, una dirección o un sitio conocido.",
  },

  /** 09 · Inicio mapa. */
  mapHome: {
    title: "Coches en tu provincia",
    roleSeeking: "Busco coche",
    roleOffering: "Ofrezco plazas",
    roleGroupA11y: "Qué quieres hacer",
    categoriesA11y: "Categoría del trayecto",
    searchPlaceholder: "¿A dónde vas?",
    searchA11y: "¿A dónde vas? Busca tu destino",
    filterSeats: "Con plazas",
    filterSeatsOnly: "Solo con plazas",
    filterA11y: (label: string, active: boolean) => `Filtro de coches: ${label}${active ? ", con cambios" : ""}. Cambiar filtro`,
    filterSheetTitle: "Filtrar coches",
    filterSheetSubtitle: "Elige qué coches quieres ver en el mapa.",
    filterSeatsHeading: "Plazas",
    filterSeatsAnyDescription: "Coches con plazas libres. Los que van completos se ven en gris.",
    filterSeatsOnlyLabel: "Solo con plazas libres",
    filterSeatsOnlyDescription: "Oculta los coches que van completos.",
    filterWhenHeading: "Salida",
    filterHours: (hours: number) => `En las próximas ${hours} horas`,
    filterApply: "Ver coches",
    filterReset: "Quitar filtros",
    mapA11y: (provinceName: string) => `Mapa con los coches de la provincia de ${provinceName}`,
    mapA11yFallback: "Mapa con los coches de tu provincia",
    loadingCars: "Buscando coches…",
    carsErrorTitle: "No hemos podido cargar los coches",
    carsErrorMessage: "No hemos podido conectar con el servidor. Inténtalo de nuevo en unos segundos.",
    carsOfflineMessage: "Sin conexión no podemos enseñarte los coches. Cuando vuelva Internet se actualizará solo.",
    offlineTitle: "Sin conexión",
    offlineDetail: "Mostramos los últimos coches que cargamos",
    staleTitle: "No se pudo actualizar el mapa",
    staleDetail: "Mostramos los últimos coches cargados",
    truncatedTitle: "Hay muchos coches",
    truncatedMessage: "Hay más de los que caben en el mapa. Elige una categoría o una franja de salida más corta para afinar.",
    emptyTitle: "Aún no hay coches por aquí",
    emptyMessage: "Ahora mismo no hay coches con salida próxima. Define tu recorrido y mira otras horas y días.",
    emptyFilteredTitle: "Ningún coche con estos filtros",
    emptyFilteredMessage: "Prueba a quitar los filtros o a ampliar la franja de salida.",
    emptyDefineRoute: "Definir mi recorrido",
    provincesErrorTitle: "No hemos podido cargar las provincias",
    provincesErrorMessage: "Necesitamos saber tu provincia para enseñarte los coches. Comprueba tu conexión e inténtalo de nuevo.",
    noProvinceTitle: "Aún no hay provincias disponibles",
    noProvinceMessage: "Estamos preparando el servicio en tu zona. Vuelve a probar en unos días.",
    provinceChipA11yLoading: "Cargando provincias",
    recenter: "Centrar en mi ubicación",
    locationDeniedTitle: "Permite la ubicación para verte en el mapa",
    locationDeniedMessage: "La usamos solo mientras tienes la app abierta. Siempre puedes buscar un destino sin ella.",
    locationBlockedTitle: "La ubicación está desactivada para MVC",
    locationBlockedMessage: "Actívala en los ajustes del móvil para verte en el mapa.",
    locationOffTitle: "Ubicación del móvil apagada",
    locationOffMessage: "Enciende la ubicación del móvil para verte en el mapa.",
    locationFailedTitle: "No hemos podido ubicarte",
    locationFailedMessage: "Prueba de nuevo en un sitio con mejor cobertura.",
    locationOutsideTitle: "Estás fuera de la provincia",
    locationOutsideMessage: (provinceName: string) => `Te enseñamos los coches de la provincia de ${provinceName}.`,
    allowLocation: "Permitir ubicación",
    openSettings: "Abrir ajustes",
    retry: "Reintentar",
    dismiss: "Cerrar aviso",
    offerTitle: "Crea tu cuenta para ofrecer plazas",
    offerMessage: "Para publicar tu ruta necesitamos verificar tu móvil. Puedes seguir mirando el mapa sin cuenta.",
    offerCreate: "Crear cuenta",
    carPanel: {
      title: (count: number) => (count === 1 ? "Coche en esta zona" : `${count} coches en esta zona`),
      subtitleCluster: "Elige uno para ver el viaje",
      openTrip: "Ver viaje",
      full: "Completo",
      seats: (seats: number) => (seats <= 0 ? "Completo" : seats === 1 ? "1 plaza libre" : `${seats} plazas libres`),
      departsAt: (time: string) => `Sale a las ${time}`,
      departedAt: (time: string) => `Salió a las ${time}`,
      live: "En marcha",
      positionNote: "Posición aproximada",
      positionStale: "Posición sin actualizar",
      route: (origin: string | null, destination: string | null) =>
        origin !== null && destination !== null ? `${origin} → ${destination}` : (origin ?? destination ?? "Trayecto sin detallar"),
      rowA11y: (route: string, seats: string, time: string) => `${route}. ${seats}. ${time}. Ver viaje`,
      close: "Cerrar",
    },
    markerA11y: (route: string, seats: string) => `Coche: ${route}. ${seats}`,
    clusterA11y: (count: number) => `${count} coches agrupados. Toca para acercar`,
  },

  /** 10 · Define tu recorrido. */
  defineRoute: {
    title: "Define tu recorrido",
    useLocation: "Usar mi ubicación (opcional)",
    useLocationHint: "Te sugerimos tu municipio actual.",
    originLabel: "Origen",
    originPlaceholder: "Tu municipio",
    destinationLabel: "Destino",
    destinationPlaceholder: "Tu destino",
    originA11y: (value: string | null) => (value ? `Origen: ${value}. Cambiar` : "Origen. Elige tu municipio"),
    destinationA11y: (value: string | null) => (value ? `Destino: ${value}. Cambiar` : "Destino. Elige tu destino"),
    clearField: (field: string) => `Borrar ${field}`,
    swap: "Intercambiar origen y destino",
    whenTitle: "¿Cuándo viajas?",
    arrivalLabel: "Llegada al destino",
    returnLabel: "Regreso (opcional)",
    returnNone: "Sin regreso",
    weekly: "Semanal",
    oneOff: "Puntual",
    modeA11y: "Frecuencia del viaje",
    weekdaysLabel: "Días de la semana",
    dateLabel: "Día del viaje",
    datePlaceholder: "Elige el día",
    categoryLabel: "Categoría",
    categoryAny: "Categoría (opcional)",
    categorySheetTitle: "Categoría del trayecto",
    categoryAnyOption: "Cualquiera",
    categoryAnyDescription: "Todos los coches, sea cual sea el motivo del viaje.",
    submit: "Buscar compañeros",
    submitBusy: "Comprobando…",
    // Validación
    originRequired: "Elige el lugar de salida.",
    destinationRequired: "Elige a dónde vas.",
    samePlace: "El origen y el destino no pueden ser el mismo sitio.",
    sameProvinceRequired: "Origen y destino deben estar en la misma provincia. Solo hacemos trayectos dentro de una provincia.",
    daysRequired: "Elige al menos un día de la semana.",
    dateRequired: "Elige el día del viaje.",
    datePast: "Esa fecha ya ha pasado. Elige hoy o un día posterior.",
    dateTooFar: "Solo puedes buscar viajes de los próximos 90 días.",
    arrivalInvalid: "La hora de llegada no es válida.",
    arrivalPast: "Esa hora de llegada ya ha pasado hoy. Elige otra hora o un día posterior.",
    returnInvalid: "La hora de regreso no es válida.",
    returnAfterArrival: "El regreso tiene que ser más tarde que la llegada.",
    provinceCheckFailed: "No hemos podido comprobar la provincia. Comprueba tu conexión e inténtalo de nuevo.",
    offlineDetail: "No podemos comprobar tu recorrido ahora",
    summaryFix: "Revisa los campos marcados para continuar.",
    categoryChip: "Categoría",
    categoryChipA11y: (label: string | null) => (label !== null ? `Categoría: ${label}. Cambiar` : "Categoría: cualquiera. Cambiar"),
    locationNoticeOutsideTitle: "Ubicación fuera de provincia",
    checking: "Comprobando tu recorrido…",
    // Selectores de hora y fecha
    timeSheetTitleArrival: "Llegada al destino",
    timeSheetTitleReturn: "Regreso",
    timeSheetSubtitleArrival: "¿A qué hora quieres llegar?",
    timeSheetSubtitleReturn: "¿A qué hora quieres volver? Es opcional.",
    timeHours: "Hora",
    timeMinutes: "Minutos",
    timeApply: "Aceptar",
    timeSelectedA11y: (time: string) => `Hora elegida: ${time}`,
    timeHourA11y: (hour: string) => `${hour} horas`,
    timeMinuteA11y: (minute: string) => `${minute} minutos`,
    dateSheetTitle: "Día del viaje",
    dateSheetSubtitle: "Elige el día en que quieres viajar.",
    datePrevMonth: "Mes anterior",
    dateNextMonth: "Mes siguiente",
    dateApply: "Aceptar",
    dateToday: "Hoy",
    dateTomorrow: "Mañana",
    dateDayA11y: (label: string, selected: boolean) => `${label}${selected ? ", elegido" : ""}`,
    dateDayDisabledA11y: (label: string) => `${label}, no disponible`,
    // Ubicación
    locationDeniedTitle: "Necesitamos tu permiso",
    locationDeniedMessage: "Permite el acceso a tu ubicación cuando te lo pida el móvil, o escribe tu municipio.",
    locationBlockedTitle: "Ubicación desactivada para MVC",
    locationBlockedMessage: "Actívala en los ajustes del móvil o escribe tu municipio a mano.",
    locationOffTitle: "Ubicación del móvil apagada",
    locationOffMessage: "Enciende la ubicación del móvil e inténtalo de nuevo, o escribe tu municipio.",
    locationFailedTitle: "No hemos podido ubicarte",
    locationFailedMessage: "Prueba de nuevo en un sitio con mejor cobertura o escribe tu municipio.",
    locationOutside: (provinceName: string | null) =>
      provinceName !== null
        ? `Tu ubicación no está en la provincia de ${provinceName}. Escribe un municipio de esa provincia.`
        : "Tu ubicación está fuera de las provincias disponibles. Escribe un municipio de la provincia.",
    allowLocation: "Permitir ubicación",
    openSettings: "Abrir ajustes",
    retry: "Reintentar",
    locating: "Buscando tu ubicación…",
  },

  /** 11 · Resultados. */
  tripResults: {
    title: "Coches disponibles",
    arrivalBy: (time: string) => `Llegada ${time}`,
    edit: "Editar",
    editA11y: "Editar el recorrido",
    modeMap: "Mapa",
    modeList: "Lista",
    modesA11y: "Cómo ver los resultados",
    mapLabel: "Mapa con tu recorrido y los coches que pasan cerca",
    seats: (count: number) => (count === 1 ? "1 plaza" : `${count} plazas`),
    fromLabel: (label: string) => `Desde ${label}`,
    fromUnknown: "Punto de recogida",
    pickupInMinutes: (minutes: number, distance: string) => `Te recoge en ${minutes} min · ${distance}`,
    pickupAtTime: (time: string, distance: string) => `Te recoge a las ${time} · ${distance}`,
    arriveApprox: (time: string) => `Llegada aprox. ${time}`,
    destinationFallback: "Tu destino",
    viewTrip: "Ver viaje",
    viewTripA11y: (driver: string) => `Ver el viaje de ${driver}`,
    cardA11y: (driver: string, seats: string, from: string) => `${driver}, ${seats}, ${from}`,
    price: (amount: string) => `${amount} por trayecto`,
    returnAvailable: (time: string) => `Vuelta a las ${time}`,
    partialDays: (matched: string) => `Solo ${matched}`,
    noMatchesTitle: "Sin coincidencias",
    noMatchesFallback: "Prueba a ampliar el horario o más días.",
    noMatchesApply: "Aplicar",
    emptyTitle: "No hay coches para este recorrido",
    emptyMessage: "Prueba a ampliar el horario, elegir más días o cambiar el origen o el destino.",
    emptyEdit: "Cambiar el recorrido",
    errorTitle: "No hemos podido buscar coches",
    offlineTitle: "Sin conexión",
    offlineMessage: "Conéctate para ver los coches disponibles.",
    noProvinceTitle: "Elige una provincia",
    noProvinceMessage: "Necesitamos saber en qué provincia viajas para buscar coches.",
    loading: "Buscando coches…",
    resultsCount: (count: number) => (count === 1 ? "1 coche" : `${count} coches`),
    loadMore: "Ver más coches",
    loadingMore: "Cargando…",
    refreshFailed: "No hemos podido actualizar los resultados. Mostramos los últimos que tenemos.",
  },
} as const;

export type BrowseStrings = typeof browseStrings;

/** «3 resultados» / «1 resultado». */
export function resultsCount(count: number): string {
  return pluralize(count, "resultado");
}
