/**
 * GENERADO por tools/preview/map/gen-places.mjs desde tools/preview/map/data/places.json. NO editar a mano.
 * Coordenadas APROXIMADAS (±300 m) escritas a mano para la provincia de Sevilla: sirven para semillas, vista previa y
 * pruebas; nunca como dato de geocodificación ni de navegación.
 */
export const SEVILLA_PLACES_DATA = [
  { id: "sevilla", name: "Sevilla", kind: "municipio", municipio: "Sevilla", lat: 37.3886, lng: -5.9953 },
  { id: "centro-de-sevilla", name: "Centro de Sevilla", kind: "barrio", municipio: "Sevilla", lat: 37.3885, lng: -5.9925 },
  { id: "triana", name: "Triana", kind: "barrio", municipio: "Sevilla", lat: 37.3815, lng: -6.0095 },
  { id: "macarena", name: "Macarena", kind: "barrio", municipio: "Sevilla", lat: 37.4045, lng: -5.9835 },
  { id: "nervion", name: "Nervión", kind: "barrio", municipio: "Sevilla", lat: 37.3815, lng: -5.9695 },
  { id: "san-pablo", name: "San Pablo", kind: "barrio", municipio: "Sevilla", lat: 37.3995, lng: -5.9615 },
  { id: "los-remedios", name: "Los Remedios", kind: "barrio", municipio: "Sevilla", lat: 37.3745, lng: -6.0085 },
  { id: "los-bermejales", name: "Los Bermejales", kind: "barrio", municipio: "Sevilla", lat: 37.35, lng: -5.9885 },
  { id: "heliopolis", name: "Heliópolis", kind: "barrio", municipio: "Sevilla", lat: 37.356, lng: -5.979 },
  { id: "cerro-del-aguila", name: "Cerro del Águila", kind: "barrio", municipio: "Sevilla", lat: 37.3745, lng: -5.9575 },
  { id: "sevilla-este", name: "Sevilla Este", kind: "barrio", municipio: "Sevilla", lat: 37.3935, lng: -5.9235 },
  { id: "torreblanca", name: "Torreblanca", kind: "barrio", municipio: "Sevilla", lat: 37.3745, lng: -5.9145 },
  { id: "pino-montano", name: "Pino Montano", kind: "barrio", municipio: "Sevilla", lat: 37.4225, lng: -5.9775 },
  { id: "bellavista", name: "Bellavista", kind: "barrio", municipio: "Sevilla", lat: 37.3375, lng: -5.9775 },
  { id: "san-jeronimo", name: "San Jerónimo", kind: "barrio", municipio: "Sevilla", lat: 37.415, lng: -5.9885 },
  { id: "el-arenal", name: "El Arenal", kind: "barrio", municipio: "Sevilla", lat: 37.3855, lng: -5.9985 },
  { id: "plaza-de-espana", name: "Plaza de España", kind: "landmark", municipio: "Sevilla", lat: 37.3772, lng: -5.9869 },
  { id: "isla-magica", name: "Isla Mágica", kind: "landmark", municipio: "Sevilla", lat: 37.4075, lng: -6.0035 },
  { id: "torre-sevilla", name: "Torre Sevilla", kind: "landmark", municipio: "Sevilla", lat: 37.403, lng: -6.0115 },
  { id: "catedral-de-sevilla", name: "Catedral de Sevilla", kind: "landmark", municipio: "Sevilla", lat: 37.386, lng: -5.9926 },
  { id: "torre-del-oro", name: "Torre del Oro", kind: "landmark", municipio: "Sevilla", lat: 37.3825, lng: -5.9962 },
  { id: "puente-de-triana", name: "Puente de Triana", kind: "landmark", municipio: "Sevilla", lat: 37.3854, lng: -6.0013 },
  { id: "estacion-santa-justa", name: "Estación de Santa Justa", kind: "estacion", municipio: "Sevilla", lat: 37.3925, lng: -5.9755 },
  { id: "estacion-plaza-de-armas", name: "Estación Plaza de Armas", kind: "estacion", municipio: "Sevilla", lat: 37.3893, lng: -6.0003 },
  { id: "estadio-olimpico-cartuja", name: "Estadio de La Cartuja", kind: "landmark", municipio: "Sevilla", lat: 37.4175, lng: -6.008 },
  { id: "parque-de-maria-luisa", name: "Parque de María Luisa", kind: "parque", municipio: "Sevilla", lat: 37.3735, lng: -5.9915 },
  { id: "parque-del-alamillo", name: "Parque del Alamillo", kind: "parque", municipio: "Sevilla", lat: 37.4215, lng: -5.995 },
  { id: "estadio-ramon-sanchez-pizjuan", name: "Estadio Sánchez-Pizjuán", kind: "landmark", municipio: "Sevilla", lat: 37.384, lng: -5.9705 },
  { id: "estadio-benito-villamarin", name: "Estadio Benito Villamarín", kind: "landmark", municipio: "Sevilla", lat: 37.3565, lng: -5.9817 },
  { id: "universidad-de-sevilla", name: "Universidad de Sevilla", kind: "campus", municipio: "Sevilla", lat: 37.379, lng: -5.9925 },
  { id: "campus-reina-mercedes", name: "Campus de Reina Mercedes", kind: "campus", municipio: "Sevilla", lat: 37.3573, lng: -5.9863 },
  { id: "universidad-pablo-de-olavide", name: "Universidad Pablo de Olavide", kind: "campus", municipio: "Sevilla", lat: 37.3563, lng: -5.9358 },
  { id: "campus-palmas-altas", name: "Campus Palmas Altas", kind: "campus", municipio: "Sevilla", lat: 37.355, lng: -5.948 },
  { id: "hospital-virgen-del-rocio", name: "Hospital Virgen del Rocío", kind: "hospital", municipio: "Sevilla", lat: 37.3585, lng: -5.977 },
  { id: "hospital-virgen-macarena", name: "Hospital Virgen Macarena", kind: "hospital", municipio: "Sevilla", lat: 37.4045, lng: -5.9835 },
  { id: "hospital-virgen-de-valme", name: "Hospital Virgen de Valme", kind: "hospital", municipio: "Sevilla", lat: 37.318, lng: -5.9845 },
  { id: "hospital-san-juan-de-dios-aljarafe", name: "Hospital San Juan de Dios", kind: "hospital", municipio: "Bormujos", lat: 37.3724, lng: -6.0788 },
  { id: "calle-luis-montoto", name: "C. Luis Montoto", kind: "calle", municipio: "Sevilla", lat: 37.3862, lng: -5.9762 },
  { id: "avenida-de-kansas-city", name: "Av. de Kansas City", kind: "calle", municipio: "Sevilla", lat: 37.3826, lng: -5.9712 },
  { id: "avenida-manuel-siurot", name: "Av. Manuel Siurot", kind: "calle", municipio: "Sevilla", lat: 37.3685, lng: -5.9838 },
  { id: "avenida-de-la-buhaira", name: "Av. de la Buhaira", kind: "calle", municipio: "Sevilla", lat: 37.3815, lng: -5.979 },
  { id: "avenida-de-la-constitucion", name: "Av. de la Constitución", kind: "calle", municipio: "Sevilla", lat: 37.3855, lng: -5.9945 },
  { id: "avenida-de-la-palmera", name: "Av. de la Palmera", kind: "calle", municipio: "Sevilla", lat: 37.364, lng: -5.979 },
  { id: "avenida-de-andalucia", name: "Av. de Andalucía", kind: "calle", municipio: "Sevilla", lat: 37.364, lng: -5.969 },
  { id: "plaza-nueva", name: "Plaza Nueva", kind: "calle", municipio: "Sevilla", lat: 37.3886, lng: -5.9953 },
  { id: "puerta-de-jerez", name: "Puerta de Jerez", kind: "calle", municipio: "Sevilla", lat: 37.3829, lng: -5.9935 },
  { id: "prado-de-san-sebastian", name: "Prado de San Sebastián", kind: "calle", municipio: "Sevilla", lat: 37.379, lng: -5.9855 },
  { id: "camas", name: "Camas", kind: "municipio", municipio: "Camas", lat: 37.4044, lng: -6.0327 },
  { id: "tomares", name: "Tomares", kind: "municipio", municipio: "Tomares", lat: 37.3737, lng: -6.0475 },
  { id: "san-juan-de-aznalfarache", name: "San Juan de Aznalfarache", kind: "municipio", municipio: "San Juan de Aznalfarache", lat: 37.363, lng: -6.039 },
  { id: "mairena-del-aljarafe", name: "Mairena del Aljarafe", kind: "municipio", municipio: "Mairena del Aljarafe", lat: 37.3447, lng: -6.0629 },
  { id: "bormujos", name: "Bormujos", kind: "municipio", municipio: "Bormujos", lat: 37.3714, lng: -6.0734 },
  { id: "castilleja-de-la-cuesta", name: "Castilleja de la Cuesta", kind: "municipio", municipio: "Castilleja de la Cuesta", lat: 37.3855, lng: -6.054 },
  { id: "gines", name: "Gines", kind: "municipio", municipio: "Gines", lat: 37.387, lng: -6.075 },
  { id: "santiponce", name: "Santiponce", kind: "municipio", municipio: "Santiponce", lat: 37.4378, lng: -6.0447 },
  { id: "valencina-de-la-concepcion", name: "Valencina de la Concepción", kind: "municipio", municipio: "Valencina de la Concepción", lat: 37.413, lng: -6.0707 },
  { id: "espartinas", name: "Espartinas", kind: "municipio", municipio: "Espartinas", lat: 37.3863, lng: -6.1175 },
  { id: "gelves", name: "Gelves", kind: "municipio", municipio: "Gelves", lat: 37.333, lng: -6.0225 },
  { id: "palomares-del-rio", name: "Palomares del Río", kind: "municipio", municipio: "Palomares del Río", lat: 37.315, lng: -6.05 },
  { id: "coria-del-rio", name: "Coria del Río", kind: "municipio", municipio: "Coria del Río", lat: 37.2897, lng: -6.0538 },
  { id: "almensilla", name: "Almensilla", kind: "municipio", municipio: "Almensilla", lat: 37.308, lng: -6.095 },
  { id: "la-rinconada", name: "La Rinconada", kind: "municipio", municipio: "La Rinconada", lat: 37.4869, lng: -5.9809 },
  { id: "la-algaba", name: "La Algaba", kind: "municipio", municipio: "La Algaba", lat: 37.4647, lng: -6.0207 },
  { id: "dos-hermanas", name: "Dos Hermanas", kind: "municipio", municipio: "Dos Hermanas", lat: 37.2828, lng: -5.9208 },
  { id: "montequinto", name: "Montequinto", kind: "municipio", municipio: "Dos Hermanas", lat: 37.3317, lng: -5.9379 },
  { id: "alcala-de-guadaira", name: "Alcalá de Guadaíra", kind: "municipio", municipio: "Alcalá de Guadaíra", lat: 37.3376, lng: -5.8399 },
  { id: "mairena-del-alcor", name: "Mairena del Alcor", kind: "municipio", municipio: "Mairena del Alcor", lat: 37.3705, lng: -5.7461 },
  { id: "carmona", name: "Carmona", kind: "municipio", municipio: "Carmona", lat: 37.4713, lng: -5.6411 },
  { id: "utrera", name: "Utrera", kind: "municipio", municipio: "Utrera", lat: 37.1853, lng: -5.7812 },
  { id: "los-palacios-y-villafranca", name: "Los Palacios y Villafranca", kind: "municipio", municipio: "Los Palacios y Villafranca", lat: 37.163, lng: -5.922 },
  { id: "la-puebla-del-rio", name: "La Puebla del Río", kind: "municipio", municipio: "La Puebla del Río", lat: 37.268, lng: -6.063 },
  { id: "alcala-del-rio", name: "Alcalá del Río", kind: "municipio", municipio: "Alcalá del Río", lat: 37.5167, lng: -5.9792 },
  { id: "el-viso-del-alcor", name: "El Viso del Alcor", kind: "municipio", municipio: "El Viso del Alcor", lat: 37.385, lng: -5.714 },
  { id: "ecija", name: "Écija", kind: "municipio", municipio: "Écija", lat: 37.5423, lng: -5.0826 },
] as const;
