/**
 * GENERADO por tools/preview/map/gen-road-routes.mjs (a partir de las carreteras dibujadas en el mapa base). NO editar a mano.
 * Rutas ILUSTRATIVAS: siguen los ejes del mapa ilustrativo de la vista previa, no una red viaria real. Distancia y duración son
 * estimaciones (autovía 80 km/h, avenida 45 km/h, calle 30 km/h). Úsalas como semilla/pruebas; nunca como resultado de un
 * servicio de rutas. Se leen con `SEVILLA_ROAD_ROUTES` (roadRoutes.ts).
 */
import type { SevillaPlaceId } from './places';

export interface RoadRouteRecord {
  readonly id: string;
  readonly name: string;
  readonly from: SevillaPlaceId;
  readonly to: SevillaPlaceId;
  readonly via: readonly SevillaPlaceId[];
  /** Vías principales del recorrido, en orden (referencia o nombre). */
  readonly roads: readonly string[];
  readonly distanceM: number;
  readonly durationS: number;
  /** Polilínea codificada (Google polyline, precisión 1e5). */
  readonly polyline: string;
}

export const SEVILLA_ROAD_ROUTES_DATA = [
  {
    id: "montequinto-universidad",
    name: "Montequinto → Universidad de Sevilla",
    from: "montequinto",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["Av. de la Palmera", "Av. de Menéndez Pelayo", "C. San Fernando"],
    distanceM: 8836,
    durationS: 867,
    polyline: "cjzbFzvfc@eHjwAoDpd@oCxWgDpWwCdQ_Hd^e@\\sE}BmHoC}HqAaNu@eNDaIp@sW~Ewa@nGuMxCoMvDcM~EgQ~IgLhHkT|Ood@nK_AnKOhEFhEfArQbB?",
  },
  {
    id: "montequinto-dos-hermanas-universidad",
    name: "Montequinto → Universidad de Sevilla",
    from: "montequinto",
    to: "universidad-de-sevilla",
    via: ["dos-hermanas"],
    roads: ["Av. de la Palmera", "Av. de Menéndez Pelayo", "C. San Fernando"],
    distanceM: 8836,
    durationS: 867,
    polyline: "cjzbFzvfc@eHjwAoDpd@oCxWgDpWwCdQ_Hd^e@\\sE}BmHoC}HqAaNu@eNDaIp@sW~Ewa@nGuMxCoMvDcM~EgQ~IgLhHkT|Ood@nK_AnKOhEFhEfArQbB?",
  },
  {
    id: "dos-hermanas-universidad",
    name: "Dos Hermanas → Universidad de Sevilla",
    from: "dos-hermanas",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["Av. de Montequinto", "Av. de la Palmera", "Av. de Menéndez Pelayo", "C. San Fernando"],
    distanceM: 14482,
    durationS: 1319,
    polyline: "oxpbF~kcc@qi@zM_cA~Wca@rJ_p@|Naz@rP_\\lJ{VjIeHjwAoDpd@oCxWgDpWwCdQ_Hd^e@\\sE}BmHoC}HqAaNu@eNDaIp@sW~Ewa@nGuMxCoMvDcM~EgQ~IgLhHkT|Ood@nK_AnKOhEFhEfArQbB?",
  },
  {
    id: "mairena-universidad",
    name: "Mairena del Aljarafe → Universidad de Sevilla",
    from: "mairena-del-aljarafe",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["Av. de Tablada", "Paseo de Cristóbal Colón"],
    distanceM: 10028,
    durationS: 1059,
    polyline: "k{|bFbd_d@jOe{@hFyVdGgV`DaJ|AcD~T}a@fDyI`A{DvAeKf@uKPuK@sQw^aV}\\wVs\\mWZw@{IqGeGmFsRaSsTyYoFoGoK}I_LuHmCcBcn@{A{s@oEcBg^bB?",
  },
  {
    id: "palomares-mairena-sevilla",
    name: "Palomares del Río → Centro de Sevilla",
    from: "palomares-del-rio",
    to: "centro-de-sevilla",
    via: ["mairena-del-aljarafe"],
    roads: ["Av. de Tablada", "Paseo de Cristóbal Colón", "Av. de la Constitución"],
    distanceM: 14937,
    durationS: 1463,
    polyline: "wawbFns|c@c|@nZo|@n\\{[nJca@bKjOe{@hFyVdGgV`DaJ|AcD~T}a@fDyI`A{DvAeKf@uKPuK@sQw^aV}\\wVs\\mWZw@{IqGeGmFsRaSsTyYoFoGoK}ImPyKcn@{A{s@oEcBg^kUtEkRhFoRpEd@_RxBq@",
  },
  {
    id: "palomares-universidad",
    name: "Palomares del Río → Universidad de Sevilla",
    from: "palomares-del-rio",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["Av. de Tablada", "Paseo de Cristóbal Colón"],
    distanceM: 9511,
    durationS: 1017,
    polyline: "wawbFns|c@mb@_}@uQc]aSs[ie@cr@eWlBmN}J_r@oh@Zw@{IqGeGmFsRaSsTyYoFoGoK}ImPyKcn@{A{s@oEcBg^bB?",
  },
  {
    id: "luis-montoto-universidad",
    name: "C. Luis Montoto → Universidad de Sevilla",
    from: "calle-luis-montoto",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["Av. de Eduardo Dato", "Ronda Histórica", "C. San Fernando"],
    distanceM: 1949,
    durationS: 209,
    polyline: "q~dcF~dnc@zAnUvBhQtOzFjQtI_AnKOhEFhEfArQbB?",
  },
  {
    id: "torre-sevilla-centro",
    name: "Torre Sevilla → Centro de Sevilla",
    from: "torre-sevilla",
    to: "centro-de-sevilla",
    via: [],
    roads: ["SE-30", "Av. de Pino Montano", "Av. del Dr. Fedriani", "Av. de la Cruz Roja", "Av. del Torneo"],
    distanceM: 13415,
    durationS: 941,
    polyline: "wghcFzbuc@f@bB{DnEsErHmAnD_@fEFvKvAdXh@dXsEx@_Ip@aD@kGu@mHmCyGiE{W}TaTsPeKiJmJoKyLsQ_HmNsCgJy@}Dm@aE{@oK]uKSaRGcRJwKnAu^lAyQ~AwQlFua@tT|LxLxFlHlCzHbB`Ij@dXLbm@~A|BjPjB|JlClJdI~T}Ah@dH|\\fKtCzH`Bvk@jIe@}HHkEbAoKd@_RxBq@",
  },
  {
    id: "isla-magica-centro",
    name: "Isla Mágica → Centro de Sevilla",
    from: "isla-magica",
    to: "centro-de-sevilla",
    via: [],
    roads: ["Av. de Carlos III", "Puente de la Barqueta", "Av. del Torneo"],
    distanceM: 4250,
    durationS: 411,
    polyline: "{cicFzpsc@~B~h@zHqAvHkBvT_HFq_AfKtCzH`Bvk@jIe@}HHkEbAoKd@_RxBq@",
  },
  {
    id: "camas-universidad",
    name: "Camas → Universidad de Sevilla",
    from: "camas",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["SE-30", "Av. de Tablada", "Paseo de Cristóbal Colón"],
    distanceM: 13603,
    durationS: 1148,
    polyline: "ophcFjgyc@x{@bbAhx@~`Aj`@_NxLuFpY{PnSkRO{rAjMAdNW`SaBxH{AxC_AxL}FnGwEdGsFpJgKlFwGdIaMzTeb@aAw@Zw@{IqGeGmFsRaSsTyYoFoGoK}ImPyKcn@{A{s@oEcBg^bB?",
  },
  {
    id: "camas-centro",
    name: "Camas → Centro de Sevilla",
    from: "camas",
    to: "centro-de-sevilla",
    via: [],
    roads: ["SE-30", "Av. de Pino Montano", "Av. del Dr. Fedriani", "Av. de la Cruz Roja", "Av. del Torneo"],
    distanceM: 12513,
    durationS: 865,
    polyline: "ophcFjgyc@s@ke@sJxA_DPoGK}Cg@yC_AsCmAyGiE{W}TaTsPcOiNaJaLgIaMeEcIgDyI_CuJm@aE{@oKm@mXEy^l@kXvAeX|BaXlFua@tT|LxLxFlHlCzHbB`Ij@dXLbm@~A|BjPjB|JlClJdI~T}Ah@dH|\\fKtCzH`Bvk@jIe@}HHkEbAoKd@_RxBq@",
  },
  {
    id: "tomares-universidad",
    name: "Tomares → Universidad de Sevilla",
    from: "tomares",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["SE-30", "Av. de Tablada", "Paseo de Cristóbal Colón"],
    distanceM: 9346,
    durationS: 749,
    polyline: "spbcF|c|c@nSkRO{rAjMAdNW`SaBxH{AxC_AxL}FnGwEdGsFpJgKlFwGdIaMzTeb@aAw@Zw@{IqGeGmFsRaSsTyYoFoGoK}ImPyKcn@{A{s@oEcBg^bB?",
  },
  {
    id: "bormujos-universidad",
    name: "Bormujos → Universidad de Sevilla",
    from: "bormujos",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["Av. de Tablada", "Paseo de Cristóbal Colón"],
    distanceM: 13179,
    durationS: 1311,
    polyline: "gbbcFvead@d]aDza@gFxWoEpMeD~LeFrLqGfLgHpTsOjOe{@hFyVdGgV`DaJ|AcD~T}a@fDyI`A{DvAeKf@uKPuK@sQw^aV}\\wVs\\mWZw@{IqGeGmFsRaSsTyYoFoGoK}I_LuHmCcBcn@{A{s@oEcBg^bB?",
  },
  {
    id: "san-juan-centro",
    name: "San Juan de Aznalfarache → Centro de Sevilla",
    from: "san-juan-de-aznalfarache",
    to: "centro-de-sevilla",
    via: [],
    roads: ["A-49", "Av. de Tablada", "Paseo de Cristóbal Colón", "Av. de la Constitución"],
    distanceM: 11264,
    durationS: 1065,
    polyline: "wm`cFtnzc@jOjAzM|BnM{p@vOgt@dWrAdNNdSi@fh@sCyc@_\\s\\mWZw@{IqGeGmFsRaSsTyYoFoGoK}ImPyKcn@{A{s@oEcBg^kUtEkRhFoRpEd@_RxBq@",
  },
  {
    id: "gines-centro",
    name: "Gines → Centro de Sevilla",
    from: "gines",
    to: "centro-de-sevilla",
    via: [],
    roads: ["SE-30", "Av. de Tablada", "Paseo de Cristóbal Colón", "Av. de la Constitución"],
    distanceM: 14059,
    durationS: 1272,
    polyline: "wcecFvoad@z@ok@p@mX|Di|@j`@_NxLuFpY{PnSkRO{rAjMAdNW`SaBxH{AxC_AxL}FnGwEdGsFpJgKlFwGdIaMzTeb@aAw@Zw@{IqGeGmFsRaSsTyYoFoGoK}ImPyKcn@{A{s@oEcBg^kUtEkRhFoRpEd@_RxBq@",
  },
  {
    id: "castilleja-centro",
    name: "Castilleja de la Cuesta → Centro de Sevilla",
    from: "castilleja-de-la-cuesta",
    to: "centro-de-sevilla",
    via: [],
    roads: ["SE-30", "Av. de Tablada", "Paseo de Cristóbal Colón", "Av. de la Constitución"],
    distanceM: 12196,
    durationS: 1047,
    polyline: "kzdcFnl}c@j`@_NxLuFpY{PnSkRO{rAjMAdNW`SaBxH{AxC_AxL}FnGwEdGsFpJgKlFwGdIaMzTeb@aAw@Zw@{IqGeGmFsRaSsTyYoFoGoK}ImPyKcn@{A{s@oEcBg^kUtEkRhFoRpEd@_RxBq@",
  },
  {
    id: "gelves-universidad",
    name: "Gelves → Universidad de Sevilla",
    from: "gelves",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["Av. de Tablada", "Paseo de Cristóbal Colón"],
    distanceM: 6358,
    durationS: 637,
    polyline: "grzbFrgwc@eWlBmN}J_r@oh@Zw@{IqGeGmFsRaSsTyYoFoGoK}ImPyKcn@{A{s@oEcBg^bB?",
  },
  {
    id: "coria-universidad",
    name: "Coria del Río → Universidad de Sevilla",
    from: "coria-del-rio",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["Av. de Tablada", "Paseo de Cristóbal Colón"],
    distanceM: 11963,
    durationS: 1312,
    polyline: "scrbFfk}c@uTwYuUiXeOiN_LuHwLcGcMaF{i@gRiViK_ZoPwPgKgy@ai@eWlByc@_\\s\\mWZw@{IqGeGmFsRaSsTyYoFoGoK}ImPyKcn@{A{s@oEcBg^bB?",
  },
  {
    id: "alcala-universidad",
    name: "Alcalá de Guadaíra → Universidad de Sevilla",
    from: "alcala-de-guadaira",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["Av. de la Palmera", "Av. de Menéndez Pelayo", "C. San Fernando"],
    distanceM: 17522,
    durationS: 1913,
    polyline: "_o{bFjrsb@lDrwCpBhkAxCzwAtFdqBjNnsDkEb~@kD`k@aDd^qBpQaCjQwCdQ_Hd^e@\\gJiEwHsB_NkAeNMcIZ_D\\sW~Ewa@nGuMxCoMvDuQrHqUlMwXdSod@nK_AnKOhEFhEfArQbB?",
  },
  {
    id: "la-rinconada-universidad",
    name: "La Rinconada → Universidad de Sevilla",
    from: "la-rinconada",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["SE-30", "Av. de Pino Montano", "Av. del Dr. Fedriani", "Av. de la Cruz Roja", "Av. del Torneo", "Av. de la Constitución"],
    distanceM: 14365,
    durationS: 1176,
    polyline: "ctxcFrcoc@tu@qArq@a@h]PfX~@`N~@`XjCzu@tJvk@tIj_AtO`Daa@lFua@tT|LxLxFlHlCzHbB`Ij@dXLbm@~A|BjPjB|JlClJdI~T}Ah@dH|\\bPhEvp@xJe@}HHkEbAoKxj@qNlP_DbB?",
  },
  {
    id: "la-algaba-universidad",
    name: "La Algaba → Universidad de Sevilla",
    from: "la-algaba",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["SE-30", "Av. de Pino Montano", "Av. del Dr. Fedriani", "Av. de la Cruz Roja", "Av. del Torneo", "Av. de la Constitución"],
    distanceM: 13167,
    durationS: 1050,
    polyline: "kitcFl|vc@lZ_IfR}FdM{EbHkD`UsNdn@cd@zrA_z@FiZf@_R~@}QtCi^lFua@tT|LxLxFlHlCzHbB`Ij@dXLbm@~A|BjPjB|JlClJdI~T}Ah@dH|\\bPhEvp@xJe@}HHkEbAoKxj@qNlP_DbB?",
  },
  {
    id: "santiponce-universidad",
    name: "Santiponce → Universidad de Sevilla",
    from: "santiponce",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["SE-30", "Av. de Pino Montano", "Av. del Dr. Fedriani", "Av. de la Cruz Roja", "Av. del Torneo", "Av. de la Constitución"],
    distanceM: 17437,
    durationS: 1564,
    polyline: "gaocFjr{c@}Naj@qJi[qKuZ_MmYqHwMiByC{J}JqH_C}Cc@aI_@eNV_NpA}HjAsWnFlZ_IfR}FdM{EbHkD`UsNdn@cd@zrA_z@FiZf@_R~@}QtCi^lFua@tT|LxLxFlHlCzHbB`Ij@dXLbm@~A|BjPjB|JlClJdI~T}Ah@dH|\\bPhEvp@xJe@}HHkEbAoKxj@qNlP_DbB?",
  },
  {
    id: "valencina-universidad",
    name: "Valencina de la Concepción → Universidad de Sevilla",
    from: "valencina-de-la-concepcion",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["SE-30", "Av. de Tablada", "Paseo de Cristóbal Colón"],
    distanceM: 15579,
    durationS: 1500,
    polyline: "gfjcFzt`d@|m@fNvRjD|MdB`If@hXn@nl@Hz@ok@p@mX|Di|@j`@_NxLuFpY{PnSkRO{rAjMAdNW`SaBxH{AxC_AxL}FnGwEdGsFpJgKlFwGdIaMzTeb@aAw@Zw@{IqGeGmFsRaSsTyYoFoGoK}ImPyKcn@{A{s@oEcBg^bB?",
  },
  {
    id: "espartinas-universidad",
    name: "Espartinas → Universidad de Sevilla",
    from: "espartinas",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["Av. de Tablada", "Paseo de Cristóbal Colón"],
    distanceM: 17413,
    durationS: 1821,
    polyline: "k_ecFhyid@b|AqrGd]aDza@gFxWoEpMeD~LeFrLqGfLgHpTsOjOe{@fJqb@fCoJ`DaJ~DgI|NuWfG}N`A{DvAeKf@uKPuK@sQw^aV}\\wVs\\mWZw@{IqGeGmFyN_OqFkGqT{Y_KsJwTgOcn@{A{s@oEcBg^bB?",
  },
  {
    id: "almensilla-palomares-universidad",
    name: "Almensilla → Universidad de Sevilla",
    from: "almensilla",
    to: "universidad-de-sevilla",
    via: ["palomares-del-rio"],
    roads: ["Av. de Tablada", "Paseo de Cristóbal Colón"],
    distanceM: 13563,
    durationS: 1505,
    polyline: "_vubFvled@kTcbCkUcuCoe@abAmKcSwHsMkSi[m^wh@eWlBmN}J_r@oh@Zw@{IqGeGmFsRaSsTyYoFoGeGoFqGuEeLqHcn@{A{s@oEcBg^bB?",
  },
  {
    id: "upo-santa-justa",
    name: "Universidad Pablo de Olavide → Estación de Santa Justa",
    from: "universidad-pablo-de-olavide",
    to: "estacion-santa-justa",
    via: [],
    roads: ["Ronda del Tamarguillo", "Av. de Kansas City"],
    distanceM: 6268,
    durationS: 551,
    polyline: "{c_cFvifc@~Gp_@xAdKh@zFwDbLmDxIeE~H_FbHeGpFgLdHad@nSyd@fQuFrKyElHwIlLoJpKkK~IoLpGuGpEmf@xf@}FaP",
  },
  {
    id: "upo-universidad",
    name: "Universidad Pablo de Olavide → Universidad de Sevilla",
    from: "universidad-pablo-de-olavide",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["Av. de Andalucía", "Av. de Menéndez Pelayo", "C. San Fernando"],
    distanceM: 7211,
    durationS: 703,
    polyline: "{c_cFvifc@nIre@jAjKvAvQbCjQvOft@tDjSaN`DkM|Dmi@vSyL~FqGvE_CzB_J`LwEnHqH|MgJ`T{KlZod@nK_AnKOhEFhEfArQbB?",
  },
  {
    id: "sevilla-este-universidad",
    name: "Sevilla Este → Universidad de Sevilla",
    from: "sevilla-este",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["Av. del Dr. Fedriani", "Av. de la Cruz Roja", "Av. del Torneo", "Av. de la Constitución"],
    distanceM: 10435,
    durationS: 924,
    polyline: "klfcFz|cc@zA^cI~b@_CrPLpYKbRk@|QqBrQkB|JwCrL_FaC{Bz]uWrn@_K~ZkEhPsBzJaBdKyCtW_AzQ?fOrTl@|BjPjB|JlClJdI~T}Ah@dH|\\fKtCxMhCxf@bHe@}HHkEbAoKxj@qNlP_DbB?",
  },
  {
    id: "pino-montano-universidad",
    name: "Pino Montano → Universidad de Sevilla",
    from: "pino-montano",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["Av. de Pino Montano", "Av. del Dr. Fedriani", "Av. de la Cruz Roja", "Av. del Torneo", "Av. de la Constitución"],
    distanceM: 6544,
    durationS: 596,
    polyline: "salcFjnnc@iBxIxLxFhMhE~Cf@`Ij@dXLbm@~A|BjPjB|JlClJdI~T}Ah@dH|\\fKtCxMhCxf@bHe@}HHkEbAoKxj@qNlP_DbB?",
  },
  {
    id: "bellavista-universidad",
    name: "Bellavista → Universidad de Sevilla",
    from: "bellavista",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["Av. de la Palmera", "Av. de Menéndez Pelayo", "C. San Fernando"],
    distanceM: 5856,
    durationS: 487,
    polyline: "_o{bFxmnc@qAkTqE{BmHoC}HqAaNu@eNDaIp@sW~Ewa@nGqRpEaRnGkQrIyPdKkT|Ood@nK_AnKOhEFhEfArQbB?",
  },
  {
    id: "santa-justa-universidad",
    name: "Estación de Santa Justa → Universidad de Sevilla",
    from: "estacion-santa-justa",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["Av. de Kansas City", "Av. de Eduardo Dato", "Ronda Histórica", "C. San Fernando"],
    distanceM: 3254,
    durationS: 343,
    polyline: "cffcFzanc@|F`Pt_@i`@[bCOfERtKpAxQvBhQtOzFjQtI_AnKOhEFhEfArQbB?",
  },
  {
    id: "virgen-del-rocio-santa-justa",
    name: "Hospital Virgen del Rocío → Estación de Santa Justa",
    from: "hospital-virgen-del-rocio",
    to: "estacion-santa-justa",
    via: [],
    roads: ["Av. de la Palmera", "Av. de Menéndez Pelayo", "Ronda Histórica", "Av. de Eduardo Dato", "Av. de Kansas City"],
    distanceM: 5220,
    durationS: 487,
    polyline: "sq_cFfknc@uHYWeHuEjAaRnGkQrIyPdKkT|Ood@nKkQuIuO{FwBiQqAyQSuKNgEZcCu_@h`@}FaP",
  },
  {
    id: "valme-virgen-del-rocio",
    name: "Hospital Virgen de Valme → Hospital Virgen del Rocío",
    from: "hospital-virgen-de-valme",
    to: "hospital-virgen-del-rocio",
    via: [],
    roads: ["A-4", "Av. de la Palmera"],
    distanceM: 6893,
    durationS: 578,
    polyline: "otwbFbzoc@Sy^k@aR{@mKg@gEkEcWmLyj@e]pS{dAhr@sE}BmHoC}HqA_Ii@cIOeN\\}HfAuW~EyWzDyPnDVdHtHX",
  },
  {
    id: "utrera-universidad",
    name: "Utrera → Universidad de Sevilla",
    from: "utrera",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["A-376", "Av. de Montequinto", "Av. de la Palmera", "Av. de Menéndez Pelayo", "C. San Fernando"],
    distanceM: 32450,
    durationS: 2214,
    polyline: "cw}aFnchb@_}BdwDgoAtqBi\\xj@wN|WkQj]yS~b@adB|uDgrBphEcdAjzBcLkXiS_k@qi@zM_cA~Wca@rJ_p@|Naz@rP_\\lJ{VjIeHjwAoDpd@oCxWgDpWwCdQ_Hd^e@\\sE}BmHoC}HqAaNu@eNDaIp@sW~Ewa@nGuMxCoMvDcM~EgQ~IgLhHkT|Ood@nK_AnKOhEFhEfArQbB?",
  },
  {
    id: "carmona-universidad",
    name: "Carmona → Universidad de Sevilla",
    from: "carmona",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["A-4", "Av. de Miraflores", "Av. del Dr. Fedriani", "Av. de la Cruz Roja", "Av. del Torneo", "Av. de la Constitución"],
    distanceM: 37032,
    durationS: 2422,
    polyline: "srucFzwla@n`@fsHzDnd@pFpj@ja@lrDhMxoAnVztC~HzcAfIfjAnJl}AtJrpBrQjiErJvpCzFbqAnHljA~IbjAhCzW|D|]fDrW|DhWnG|\\nP|s@~Szx@jNdg@dJaLnGyExC{@~CNxCz@pCtAvGpEjSvQxJ`KfRrUaCzOiC|Wc@pK?fOrTl@|BjPjB|JlClJdI~T}Ah@dH|\\fKtCzH`Bvk@jIe@}HHkEbAoKxj@qNlP_DbB?",
  },
  {
    id: "mairena-del-alcor-universidad",
    name: "Mairena del Alcor → Universidad de Sevilla",
    from: "mairena-del-alcor",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["A-92", "Av. de la Palmera", "Av. de Menéndez Pelayo", "C. San Fernando"],
    distanceM: 30431,
    durationS: 2804,
    polyline: "s|acFbhab@b]tqAdSjy@~Mhn@l[j~AsQbh@uy@l}B}Tbq@eLh_@zOxVtIpL|MbPzJ|JvKjI|LnF`N`A`DBdS}@|RcCvWwElWaGx`@cLlDrwCpBhkAxCzwAtFdqBjNnsDeHjwAoDpd@oCxWgDpWwCdQ_Hd^e@\\sE}BmHoC}HqAaNu@eNDaIp@sW~Ewa@nGuMxCoMvDcM~EgQ~IgLhHkT|Ood@nK_AnKOhEFhEfArQbB?",
  },
  {
    id: "los-palacios-universidad",
    name: "Los Palacios y Villafranca → Universidad de Sevilla",
    from: "los-palacios-y-villafranca",
    to: "universidad-de-sevilla",
    via: [],
    roads: ["A-4", "Av. de Montequinto", "Av. de la Palmera", "Av. de Menéndez Pelayo", "C. San Fernando"],
    distanceM: 28879,
    durationS: 2154,
    polyline: "wkyaFnscc@cBbBsmCfVokHtt@}_AvKylBhVal@~G_JmIeJ{KkI}LyHqMaHkNgG_OoIwToKuZqi@zM_cA~Wca@rJ_p@|Naz@rP_\\lJ{VjIeHjwAoDpd@oCxWgDpWwCdQ_Hd^e@\\sE}BmHoC}HqAaNu@eNDaIp@sW~Ewa@nGuMxCoMvDcM~EgQ~IgLhHkT|Ood@nK_AnKOhEFhEfArQbB?",
  },
] as const satisfies readonly RoadRouteRecord[];

export type SevillaRoadRouteId = (typeof SEVILLA_ROAD_ROUTES_DATA)[number]['id'];
