/**
 * Textos en español (es-ES) del paquete «admin-review» del slice `admin`: 37 Resumen, 38 Usuarios y revisión,
 * 39 Reservas y devoluciones y las páginas adicionales (inicio del panel, expediente de usuario, devolución).
 *
 * Los literales de las láminas se copian tal cual («Pendientes», «Ver expediente», «Revisar devolución», «Por definir»,
 * «Acceso a documentación privada solo para personal autorizado de MVC.»). Aquí NO hay importes ni datos de ejemplo:
 * todo lo que depende del servidor llega por parámetro. Las funciones devuelven frases ya compuestas para que las
 * pantallas no concatenen textos.
 *
 * Desviación consciente de una palabra respecto a las láminas: la app no conoce el género de la persona, así que el rol
 * se rotula «Conductor» / «Pasajero» (en la lámina, «Conductora») y «Cancelada por el conductor» (lámina: «…por la
 * conductora»).
 */
import type {
  AdminPeriod,
  AdminPermission,
  AdminResource,
  AdminReviewItemKey,
  AdminReviewTab,
  ReviewState,
  TrustStaffRole,
} from "@/api/types";
import { NBSP, pluralize } from "@/i18n";

export const reviewStrings = {
  common: {
    panelTitle: "Panel MVC",
    retry: "Reintentar",
    cancel: "Cancelar",
    close: "Cerrar",
    back: "Volver",
    confirm: "Confirmar",
    understood: "Entendido",
    loading: "Cargando…",
    updating: "Actualizando…",
    loadingMore: "Cargando más…",
    loadMore: "Cargar más",
    loadMoreError: "No hemos podido cargar más.",
    offlineTitle: "Sin conexión",
    offlineDetail: "Mostramos lo último que tenías cargado.",
    offlineActionTitle: "Sin conexión",
    offlineActionDetail: "Esta acción necesita conexión. Inténtalo de nuevo cuando vuelvas a tenerla.",
    loadErrorTitle: "No hemos podido cargar los datos",
    loadErrorMessage: "Inténtalo de nuevo en unos segundos.",
    notAvailable: "—",
    seeAll: "Ver todos",
    yes: "Sí",
    no: "No",
    staffAvatarA11y: (name: string) => `Mi acceso al panel: ${name}`,
  },

  /** Control de acceso por rol (RBAC): lo que el rol no puede ver no se muestra; lo que el servidor deniega, «Sin permiso». */
  access: {
    checkingTitle: "Comprobando tu acceso",
    deniedTitle: "Sin permiso",
    deniedMessage: (areaLabel: string) => `Tu rol no incluye acceso a «${areaLabel}». Si lo necesitas, pídeselo a una persona con rol de administración.`,
    deniedGeneric: "Tu rol no incluye acceso a esta sección. Si lo necesitas, pídeselo a una persona con rol de administración.",
    deniedByServer: "El servidor ha denegado el acceso con tu rol actual. Quizá tus permisos hayan cambiado: vuelve al inicio del panel.",
    notStaffTitle: "Solo personal de MVC",
    notStaffMessage: "Esta zona es solo para el personal autorizado de MVC.",
    yourRoles: (roles: string) => `Tu acceso: ${roles}.`,
    noRoles: "Sin roles de personal",
    goHome: "Ir al inicio del panel",
    areaLabels: {
      summary: "Resumen",
      finance_kpis: "Indicadores económicos",
      review: "Usuarios y revisión",
      evidence: "Documentación privada",
      bookings: "Reservas y devoluciones",
      tariffs: "Tarifas",
      tariff_activation: "Activación de tarifas",
      operations: "Operaciones",
      alerts: "Alertas",
      audit: "Auditoría",
      legal: "Documentos legales",
      support: "Atención al cliente",
    } satisfies Record<AdminResource, string>,
    roleLabels: {
      admin: "Administración",
      verification_admin: "Verificación",
      finance_admin: "Finanzas",
      support_admin: "Atención al cliente",
    } satisfies Record<TrustStaffRole, string>,
    permissionLabels: {
      none: "Sin acceso",
      read: "Solo lectura",
      write: "Puede editar",
    } satisfies Record<AdminPermission, string>,
    sheetTitle: "Mi acceso al panel",
    sheetRoles: "Roles",
    sheetPermissions: "Qué puedes hacer",
    sheetNote: "Los permisos se leen del servidor en cada sesión. Si cambian, se aplican en tu siguiente consulta.",
    sheetHome: "Ir al inicio del panel",
    sheetLoadError: "No hemos podido leer tus permisos.",
  },

  provinces: {
    all: "Todas las provincias",
    sheetTitle: "Provincia",
    a11y: (name: string) => `Provincia: ${name}`,
    loadError: "No hemos podido cargar las provincias.",
  },

  /** 38 · Usuarios y revisión. */
  users: {
    subtitle: "Usuarios y revisión",
    tabsA11y: "Estado de la revisión",
    tabs: {
      pending: "Pendientes",
      approved: "Aprobados",
      rejected: "Rechazados",
    } satisfies Record<AdminReviewTab, string>,
    filters: {
      itemA11y: "Filtrar por elemento",
      roleA11y: "Filtrar por rol",
      sortA11y: "Ordenar la lista",
      itemAll: "Todos",
      itemSheetTitle: "Elemento a revisar",
      itemLabels: {
        identity: "Identidad",
        driver_license: "Permiso de conducir",
        profile_photo: "Foto de perfil",
        private_check: "Comprobación privada",
      } satisfies Record<AdminReviewItemKey, string>,
      roleLabel: "Rol",
      roleSheetTitle: "Rol de la persona",
      roleAll: "Todos los roles",
      roleDriver: "Conductores",
      rolePassenger: "Pasajeros",
      sortRecent: "Más recientes",
      sortOldest: "Más antiguas",
      sortSheetTitle: "Ordenar por",
      sortRecentHint: "Las entregas más recientes primero",
      sortOldestHint: "Las más antiguas primero: cola de trabajo",
      clear: "Quitar filtros",
    },
    roleDriver: "Conductor",
    rolePassenger: "Pasajero",
    roleBoth: "Conductor y pasajero",
    statusNone: "Sin entregas",
    rowStates: {
      none: "Sin enviar",
      in_review: "En revisión",
      needs_retry: "Nueva captura solicitada",
      approved: "Aprobado",
      rejected: "Rechazado",
    } satisfies Record<ReviewState, string>,
    viewDossier: "Ver expediente",
    approve: "Aprobar",
    reject: "Rechazar",
    accessNote: "Acceso a documentación privada solo para personal autorizado de MVC.",
    cardA11y: (name: string, role: string, status: string, pending: number) =>
      `${name}, ${role}. ${status}.${pending > 0 ? ` ${pending === 1 ? "1 elemento en revisión" : `${pending} elementos en revisión`}.` : ""}`,
    rowA11y: (label: string, stateLabel: string, badge: string | null) => (badge !== null ? `${label}. ${badge}.` : `${label}. ${stateLabel}.`),
    emptyTitle: {
      pending: "No hay revisiones pendientes",
      approved: "Todavía no hay aprobaciones",
      rejected: "Todavía no hay rechazos",
    } satisfies Record<AdminReviewTab, string>,
    emptyMessage: {
      pending: "Cuando alguien envíe su identidad, su permiso o su foto, aparecerá aquí.",
      approved: "Las personas cuya documentación apruebes aparecerán aquí.",
      rejected: "Las personas cuya documentación rechaces aparecerán aquí.",
    } satisfies Record<AdminReviewTab, string>,
    emptyFilteredTitle: "Ningún resultado con estos filtros",
    emptyFilteredMessage: "Prueba con otro elemento o con otro rol.",
    loadErrorTitle: "No hemos podido cargar la cola de revisión",
    approveConfirmTitle: (name: string) => `¿Aprobar a ${name}?`,
    approveConfirmMessage: (items: readonly string[]) =>
      `Se aprobará lo que está en revisión: ${joinList(items)}. La decisión queda registrada a tu nombre.`,
    approveConfirmLabel: "Aprobar",
    rejectSheetTitle: (name: string) => `Rechazar a ${name}`,
    rejectSheetSubtitle: (items: readonly string[]) => `Se rechazará lo que está en revisión: ${joinList(items)}.`,
    rejectReasonLabel: "Motivo (obligatorio)",
    rejectReasonPlaceholder: "Explica por qué no se puede aprobar",
    rejectReasonHelper: "Entre 3 y 1.000 caracteres. Queda en el expediente y en la auditoría.",
    rejectReasonTooShort: "Escribe un motivo de al menos 3 caracteres.",
    rejectReasonTooLong: "El motivo no puede pasar de 1.000 caracteres.",
    rejectConfirmLabel: "Rechazar",
    working: "Guardando la decisión…",
    decisionApproved: (name: string) => `Aprobado: ${name}.`,
    decisionRejected: (name: string) => `Rechazado: ${name}.`,
    decisionRetry: (name: string) => `Se ha pedido otra captura a ${name}.`,
    decisionPartial: (name: string, done: number, skipped: number) =>
      `${name}: ${pluralize(done, "elemento decidido", "elementos decididos")} y ${pluralize(skipped, "omitido", "omitidos")}.`,
    skippedNothing: "No había entrega pendiente de este elemento.",
    skippedInvalid: "Esta decisión no se puede aplicar a este elemento.",
    errorTitle: "No se ha guardado la decisión",
    staleTitle: "La lista ha cambiado",
    staleMessage: "Otra persona ya ha decidido sobre este expediente. Hemos actualizado la lista.",
  },

  /** Expediente de una persona usuaria. */
  dossier: {
    title: "Expediente",
    tabsA11y: "Secciones del expediente",
    tabs: { items: "Elementos", vehicles: "Vehículos", history: "Historial" },
    notFoundTitle: "No encontramos a esta persona",
    notFoundMessage: "Puede que la cuenta se haya eliminado. Vuelve a la lista y actualízala.",
    loadErrorTitle: "No hemos podido cargar el expediente",
    statusLabels: { active: "Cuenta activa", suspended: "Cuenta suspendida", deleted: "Cuenta eliminada" },
    createdAt: (when: string) => `Alta: ${when}`,
    phone: (masked: string) => `Teléfono: ${masked}`,
    phoneUnknown: "Teléfono: no disponible",
    summaryTitle: "Resumen",
    pendingCount: (count: number) => (count === 0 ? "Nada pendiente de revisar" : count === 1 ? "1 elemento en revisión" : `${count} elementos en revisión`),
    selfReview: "Es tu propio expediente: no puedes revisarlo ni abrir su documentación.",
    submittedAt: (when: string) => `Entregado: ${when}`,
    notSubmitted: "Sin entrega",
    decidedBy: (who: string, when: string) => `Decidido por ${who} · ${when}`,
    decidedAt: (when: string) => `Decidido: ${when}`,
    reasonLine: (reason: string) => `Motivo: ${reason}`,
    evidenceTitle: "Documentación entregada",
    evidenceNone: "No hay documentación entregada.",
    evidenceKinds: {
      profile_photo: "Foto de perfil",
      identity_selfie: "Selfie de la comprobación privada",
      private_document: "Documento privado",
    },
    evidenceMeta: (size: string, when: string) => `${size} · ${when}`,
    viewEvidence: "Ver documentación",
    viewEvidenceA11y: (label: string) => `Ver documentación: ${label}`,
    decisionsTitle: "Decisión",
    decisionNone: "No hay nada pendiente de decidir en este elemento.",
    decisionNoPermission: "Tu rol puede consultar este elemento, pero no decidir sobre él.",
    approve: "Aprobar",
    reject: "Rechazar",
    askRetry: "Pedir otra captura",
    vehiclesEmpty: "Esta persona no tiene vehículos registrados.",
    vehiclesNote: "La revisión de cada vehículo y de sus documentos se decide aquí, por separado.",
    vehicleAreas: {
      vehicle: "Vehículo y fotos",
      documentation: "Documentación y seguro",
    },
    vehicleStatus: {
      pending: "Pendiente",
      approved: "Aprobado",
      rejected: "Rechazado",
    },
    vehicleAreaStatusLine: (label: string, status: string) => `${label}: ${status}`,
    vehicleApprove: "Aprobar",
    vehicleReject: "Rechazar",
    vehicleOnlyPending: "Solo se puede decidir lo que está pendiente.",
    insuranceDateLabel: "Vencimiento del seguro (AAAA-MM-DD)",
    insuranceDateHelper: "Obligatorio al aprobar la documentación si el sistema no lo ha leído del documento.",
    insuranceDateInvalid: "Escribe la fecha con el formato AAAA-MM-DD.",
    historyEmpty: "Todavía no hay actividad registrada de esta persona.",
    historyBy: (who: string) => `por ${who}`,
    accessNoteFallback: "Acceso a documentación privada solo para personal autorizado de MVC.",
    retrySheetTitle: "Pedir otra captura",
    retrySheetSubtitle: "La persona tendrá que repetir la comprobación privada.",
    retryReasonLabel: "¿Qué ha fallado?",
    retryReasonRequired: "Elige qué ha fallado en la captura.",
    retryConfirm: "Pedir otra captura",
    rejectItemTitle: (item: string) => `Rechazar: ${item}`,
    approveItemTitle: (item: string) => `¿Aprobar «${item}»?`,
    approveItemMessage: "La decisión queda registrada a tu nombre.",
    reasonCodeLabel: "Motivo estándar (opcional)",
    reasonCodeNone: "Sin motivo estándar",
    reasonCodeSheetTitle: "Motivo estándar",
    decisionDone: (item: string, decision: string) => `${item}: ${decision}.`,
    decisionWords: { approved: "aprobado", rejected: "rechazado", needs_retry: "se ha pedido otra captura" },
  },

  /** Visor de documentación privada (URL firmada de 120 s; el acceso queda registrado). */
  evidence: {
    noticeTitle: "Documentación privada",
    noticeMessage: (name: string) =>
      `Vas a abrir documentación privada de ${name}. El acceso queda registrado a tu nombre, el enlace caduca en 2 minutos y la imagen no se guarda en este dispositivo.`,
    noticeOpen: "Abrir",
    viewerTitle: "Documentación privada",
    accessLogged: "Este acceso queda registrado en la auditoría de MVC.",
    requesting: "Pidiendo acceso seguro…",
    expiresIn: (clock: string) => `Caduca en ${clock}`,
    expired: "El enlace ha caducado y la imagen se ha retirado de la pantalla.",
    reopen: "Volver a pedir acceso",
    close: "Cerrar y olvidar",
    loadingImage: "Cargando la imagen…",
    imageError: "No se ha podido mostrar la imagen.",
    notImage: (contentType: string) => `Este archivo es de tipo ${contentType} y no se puede previsualizar aquí.`,
    openExternally: "Abrir en el navegador seguro",
    notFoundTitle: "La documentación ya no está disponible",
    notFoundMessage: "No encontramos este archivo. Actualiza el expediente.",
    selfTitle: "No puedes abrir tu propia documentación",
    selfMessage: "Por seguridad, nadie puede revisar ni abrir la documentación propia desde el panel.",
    storageMismatchTitle: "El archivo no coincide con el registro",
    storageMismatchMessage: "El almacenamiento no devuelve lo que esperábamos. Se ha avisado a administración: no se muestra nada.",
    storageDisabledTitle: "Almacenamiento privado no disponible",
    storageDisabledMessage: "El almacenamiento privado está desactivado en este entorno. Inténtalo más tarde.",
    purposeLabels: {
      identity_review: "Revisión de identidad",
      photo_moderation: "Moderación de foto",
      license_review: "Revisión del permiso de conducir",
      vehicle_review: "Revisión de vehículo",
      support_case: "Caso de atención",
      legal_request: "Requerimiento legal",
    },
  },

  /** 39 · Reservas y devoluciones. */
  bookings: {
    subtitle: "Reservas y devoluciones",
    tabsA11y: "Filtro de reservas",
    tabs: { all: "Todas", cancelled: "Canceladas", refunded: "Devueltas" },
    periodA11y: "Periodo",
    periodSheetTitle: "Periodo",
    refundPeriods: {
      "7d": "Últimos 7 días",
      "30d": "Últimos 30 días",
      "90d": "Últimos 90 días",
      "365d": "Último año",
      all: "Todo el histórico",
    },
    bookingPeriods: {
      today: "Hoy",
      yesterday: "Ayer",
      last_7_days: "Últimos 7 días",
      last_30_days: "Últimos 30 días",
      this_month: "Este mes",
    } satisfies Record<AdminPeriod, string>,
    originStatus: {
      passenger_cancellation: "Cancelada",
      driver_cancellation: "Cancelada",
      platform_cancellation: "Cancelada",
      force_majeure: "Fuerza mayor",
      no_show: "No se presentó",
      late_payment: "Pago tardío",
      other: "Otro motivo",
    },
    bookingStatus: {
      confirmed: "Confirmada",
      completed: "Completada",
      cancelled: "Cancelada",
      driver_cancelled: "Cancelada",
      no_show: "No se presentó",
    },
    labels: {
      paid: "Importe pagado (pasajero)",
      proposed: "Devolución propuesta",
      approved: "Devolución aprobada",
      fee: "Comisión plataforma (propuesta)",
      final: "Coste final pasajero",
      maxRefundable: "Máximo devolvible",
    },
    cancelledBy: {
      passenger: "Cancelada por el pasajero",
      driver: "Cancelada por el conductor",
      platform: "Cancelada por MVC",
      system: "Cancelada por el sistema",
    },
    noShowLine: "El pasajero no se presentó",
    latePaymentLine: "Pago confirmado cuando la plaza ya no estaba retenida",
    otherLine: "Devolución abierta",
    atTime: (line: string, time: string) => `${line} · ${time}`,
    review: "Revisar devolución",
    reviewA11y: (name: string) => `Revisar la devolución de ${name}`,
    readOnlyNote: "Solo lectura: las devoluciones las gestiona Finanzas.",
    refundStates: {
      not_applicable: "Sin devolución",
      pending_definition: "Devolución por definir",
      proposed: "Devolución propuesta",
      refunded: "Devuelta",
    },
    refundLine: {
      approved: "Aprobada · pendiente de enviar al proveedor de pago",
      executing: "Enviada al proveedor de pago · esperando su confirmación",
      refunded: "Devuelta · confirmada por el proveedor de pago",
      rejected: "Devolución rechazada",
      failed: "El proveedor de pago no pudo completar la devolución",
      blocked: "Bloqueada · el proveedor de pago no está disponible",
    },
    emptyTitle: {
      all: "No hay reservas con estos filtros",
      cancelled: "No hay devoluciones abiertas",
      refunded: "Todavía no hay devoluciones completadas",
    },
    emptyMessage: {
      all: "Prueba con otro periodo o con otra provincia.",
      cancelled: "Cuando se cancele una reserva pagada, su propuesta de devolución aparecerá aquí.",
      refunded: "Una devolución solo aparece aquí cuando el proveedor de pago la confirma.",
    },
    loadErrorTitle: "No hemos podido cargar las reservas",
    sourceFinance: "Propuestas de devolución",
    sourceSupport: "Reservas",
    cardA11y: (name: string, status: string, route: string) => `${name}. ${status}. ${route}.`,
    routeA11y: (from: string, to: string) => `De ${from} a ${to}`,
    unknownPlace: "Lugar sin nombre",
    unknownTrip: "Viaje sin fecha",
  },

  /** Detalle de una devolución (aprobar, rechazar, ejecutar). */
  refund: {
    subtitle: "Devolución",
    notFoundTitle: "No encontramos esta devolución",
    notFoundMessage: "Puede que ya no exista. Vuelve a la lista y actualízala.",
    loadErrorTitle: "No hemos podido cargar la devolución",
    passenger: "Pasajero",
    driver: "Conductor",
    trip: "Viaje",
    noDriver: "Sin conductor asignado",
    originTitle: "Origen de la devolución",
    origins: {
      passenger_cancellation: "Cancelación del pasajero",
      driver_cancellation: "Cancelación del conductor",
      platform_cancellation: "Cancelación de la plataforma",
      force_majeure: "Fuerza mayor",
      no_show: "El pasajero no se presentó",
      late_payment: "Pago tardío",
      other: "Otro motivo",
    },
    cancelReasonLine: (reason: string) => `Motivo indicado: ${reason}`,
    cancelNoteLine: (note: string) => `Nota: ${note}`,
    amountsTitle: "Importes",
    policyTitle: "Política aplicada",
    policyNone: "Todavía no hay una política de cancelación aprobada: la devolución la fija Finanzas al aprobar.",
    policyVersion: (version: number) => `Política versión ${version}`,
    statusTitle: "Estado",
    statusLabels: {
      pending_review: "Pendiente de revisión",
      approved: "Aprobada",
      executing: "En curso con el proveedor",
      refunded: "Devuelta",
      rejected: "Rechazada",
      failed: "Ha fallado",
      not_applicable: "No aplica",
    },
    executionLabels: {
      not_started: "Sin enviar al proveedor",
      awaiting_provider: "Esperando al proveedor de pago",
      submitted: "Enviada al proveedor",
      succeeded: "Confirmada por el proveedor",
      failed: "Rechazada por el proveedor",
    },
    steps: {
      proposal: "Propuesta creada",
      decision: "Decisión de Finanzas",
      provider: "Envío al proveedor de pago",
      confirmation: "Confirmación del proveedor",
    },
    stepPending: "Pendiente",
    stepBlocked: "Bloqueado",
    stepDone: "Hecho",
    stepRejected: "Rechazada",
    stepFailed: "Fallida",
    createdAt: (when: string) => `Creada: ${when}`,
    decidedAt: (when: string, who: string | null) => (who !== null ? `Decidida: ${when} · ${who}` : `Decidida: ${when}`),
    refundedAt: (when: string) => `Devuelta: ${when}`,
    decisionNote: (note: string) => `Nota de la decisión: ${note}`,
    decisionBasis: {
      policy: "Según la política",
      manual_override: "Importe cambiado a mano",
      manual_without_policy: "Decisión manual sin política aprobada",
      late_payment_full_refund: "Devolución íntegra por pago tardío",
    },
    blockedTitle: "Bloqueado",
    blockedMessage:
      "La devolución está aprobada, pero el proveedor de pago no está disponible. No se marca como devuelta hasta que el proveedor lo confirme.",
    executingTitle: "Esperando al proveedor",
    executingMessage: "La devolución se ha enviado al proveedor de pago. Solo se marcará como devuelta cuando él lo confirme.",
    refundedTitle: "Devuelta",
    refundedMessage: (when: string) => `Confirmada por el proveedor de pago el ${when}.`,
    failedTitle: "El proveedor no ha podido devolver el importe",
    failedMessage: "Puedes volver a pedirlo al proveedor. Hasta que lo confirme, no consta como devuelta.",
    rejectedTitle: "Devolución rechazada",
    rejectedMessage: "El pasajero ha sido avisado. No se devuelve ningún importe.",
    noPaymentTitle: "No hay un pago registrado",
    noPaymentMessage: "MVC no tiene registrado ningún pago que devolver en esta reserva.",
    payment: "Pago",
    paymentMethod: (label: string) => `Método: ${label}`,
    paymentStatus: (label: string) => `Estado del pago: ${label}`,
    paymentRefunded: (amount: string) => `Ya devuelto: ${amount}`,
    ledgerTitle: "Movimientos contables",
    ledgerEmpty: "Todavía no hay movimientos contables de esta devolución.",
    ledgerLine: (kind: string, account: string) => `${kind} · ${account}`,
    approve: "Aprobar devolución",
    reject: "Rechazar devolución",
    execute: "Enviar al proveedor de pago",
    retryExecute: "Volver a pedirlo al proveedor",
    actionsTitle: "Decisión",
    noActions: "No hay acciones disponibles en este estado.",
    noWritePermission: "Tu rol puede consultar esta devolución, pero no decidir sobre ella.",
    approveSheetTitle: "Aprobar devolución",
    approveSheetSubtitle: "Fija el importe que se devolverá al pasajero.",
    amountLabel: "Importe a devolver (€)",
    amountPlaceholder: "0,00",
    amountHelper: (maxText: string) => `Entre 0,01 € y ${maxText}.`,
    amountHelperPending: (maxText: string) => `Obligatorio: aún no hay propuesta. Máximo ${maxText}.`,
    amountRequired: "Escribe el importe a devolver.",
    amountInvalid: "Escribe un importe válido, por ejemplo 4,50.",
    amountTooLow: "El importe debe ser de al menos 0,01 €.",
    amountTooHigh: (maxText: string) => `No puede superar ${maxText}, lo que queda por devolver de este pago.`,
    noteLabel: "Nota de la decisión",
    noteLabelRequired: "Nota de la decisión (obligatoria)",
    notePlaceholder: "Explica el criterio aplicado",
    noteHelper: "Queda en el expediente de la devolución y en la auditoría.",
    noteRequired: "Escribe una nota: no hay política aplicable o has cambiado el importe propuesto.",
    noteTooLong: "La nota no puede pasar de 1.000 caracteres.",
    noteRejectRequired: "Escribe el motivo del rechazo (es obligatorio).",
    approveConfirm: "Aprobar",
    rejectSheetTitle: "Rechazar devolución",
    rejectSheetSubtitle: "El pasajero recibirá un aviso. La nota es obligatoria.",
    rejectConfirm: "Rechazar",
    executeConfirmTitle: "¿Pedir la devolución al proveedor?",
    executeConfirmMessage: "Se enviará la orden de devolución. No constará como devuelta hasta que el proveedor la confirme.",
    executeConfirmLabel: "Enviar",
    doneApproved: "Devolución aprobada.",
    doneApprovedBlocked: "Devolución aprobada. Queda bloqueada hasta que el proveedor de pago esté disponible.",
    doneRejected: "Devolución rechazada.",
    doneExecuted: "Orden enviada al proveedor de pago.",
    errorTitle: "No se ha completado la acción",
    stale: "El estado de la devolución ha cambiado. Hemos actualizado los datos.",
    exceedsPaid: (maxText: string) => `El importe supera lo que queda por devolver (${maxText}).`,
    providerDisabledTitle: "Proveedor de pago no disponible",
    providerDisabledMessage: "La orden no se ha enviado: el proveedor de pago está desactivado. La devolución sigue aprobada y bloqueada.",
    working: "Guardando…",
  },

  /** 37 · Resumen de administración. */
  summary: {
    subtitle: "Resumen de administración",
    periodA11y: "Periodo",
    periodSheetTitle: "Periodo",
    periods: {
      today: "Hoy",
      yesterday: "Ayer",
      last_7_days: "Últimos 7 días",
      last_30_days: "Últimos 30 días",
      this_month: "Este mes",
    } satisfies Record<AdminPeriod, string>,
    tiles: {
      activeTrips: "Viajes activos",
      requests: "Solicitudes",
      incidents: "Incidencias",
      grossRevenue: "Ingresos brutos",
      operatingCosts: "Costes operativos",
      result: "Resultado",
    },
    illustrative: "Datos ilustrativos",
    pendingDefinition: "Por definir",
    noRate: "Sin tarifa aprobada",
    noSource: "Sin datos todavía",
    tileA11yDefinition: (definition: string) => `Qué se cuenta: ${definition}`,
    flat: "0%",
    isNew: "Nuevo",
    comparedWith: "Frente al periodo anterior de la misma duración",
    mapTitle: "Actividad de vehículos (aproximada)",
    legendVehicles: "Vehículos en ruta (aprox.)",
    legendNote: "Mapa ilustrativo",
    legendInfoA11y: "Cómo se calcula la actividad de vehículos",
    infoTitle: "Actividad de vehículos (aproximada)",
    infoBody: (gridKm: string, freshnessMinutes: number) =>
      `Cada marca agrupa los vehículos de una celda de unos ${gridKm} km. Son posiciones aproximadas, sin identidades, y solo cuentan las recibidas hace menos de ${freshnessMinutes} min.`,
    infoTotal: (count: number) => `${pluralize(count, "vehículo")} en ruta ahora (aprox.)`,
    infoInProgress: (count: number) => `${pluralize(count, "viaje")} en curso ahora`,
    infoClose: "Entendido",
    mapA11y: (total: number) => `Mapa de actividad de vehículos. ${pluralize(total, "vehículo")} en ruta, posiciones aproximadas.`,
    mapEmptyTitle: "Sin vehículos en ruta",
    mapEmptyMessage: "Ahora mismo no hay posiciones recientes en esta provincia.",
    mapLoadError: "No hemos podido cargar la actividad de vehículos.",
    mapUpdated: (when: string) => `Actualizado ${when}`,
    loadErrorTitle: "No hemos podido cargar el resumen",
    financeHidden: "Los indicadores económicos son solo para Finanzas y Administración.",
    generatedAt: (when: string) => `Datos de las ${when}`,
    clusterA11y: (count: number) => `${pluralize(count, "vehículo")} en esta zona`,
  },

  /** Inicio del panel (entrada según el rol). */
  home: {
    subtitle: "Administración",
    greeting: (firstName: string) => `Hola, ${firstName}`,
    greetingUnknown: "Hola",
    intro: "Aquí solo ves lo que tu rol permite.",
    rolesLine: (roles: string) => `Tu acceso: ${roles}`,
    loadErrorTitle: "No hemos podido leer tu acceso",
    noAccessTitle: "Sin secciones disponibles",
    noAccessMessage: "Tu cuenta no tiene ningún rol de personal con acceso al panel. Si crees que es un error, avisa a administración.",
    sectionsTitle: "Secciones",
    cards: {
      summary: { title: "Resumen", subtitle: "Viajes, solicitudes, incidencias y actividad" },
      users: { title: "Usuarios y revisión", subtitle: "Identidad, permiso de conducir y fotos" },
      bookings: { title: "Reservas y devoluciones", subtitle: "Cancelaciones y propuestas de devolución" },
      tariffs: { title: "Tarifas y operación", subtitle: "Versiones de tarifa y ajustes operativos" },
      payouts: { title: "Liquidaciones", subtitle: "Pagos a conductores por periodo" },
      alerts: { title: "Alertas", subtitle: "Avisos operativos abiertos" },
      audit: { title: "Auditoría", subtitle: "Quién hizo qué y cuándo" },
      legal: { title: "Documentos legales", subtitle: "Términos, privacidad y cancelación" },
      support: { title: "Atención al cliente", subtitle: "Consultas de personas usuarias" },
    },
    pendingReviews: (count: number) => (count === 0 ? "Nada pendiente" : count === 1 ? "1 pendiente" : `${count} pendientes`),
    openRefunds: (count: number) => (count === 0 ? "Sin devoluciones abiertas" : count === 1 ? "1 abierta" : `${count} abiertas`),
    cardA11y: (title: string, extra: string | null) => (extra !== null ? `${title}. ${extra}` : title),
    yourAccess: "Tu acceso",
    permissionsTitle: "Qué puedes hacer",
  },
} as const;

function joinList(items: readonly string[]): string {
  if (items.length === 0) return "";
  if (items.length === 1) return items[0] ?? "";
  const head = items.slice(0, -1).join(", ");
  return `${head} y ${items[items.length - 1] ?? ""}`;
}

/** Une una lista con comas y «y»: «Identidad, Permiso de conducir y Foto de perfil». */
export function joinItems(items: readonly string[]): string {
  return joinList(items);
}

/** Importe y unidad sin partirse en dos líneas (`5 min`). */
export function withUnit(value: number | string, unit: string): string {
  return `${value}${NBSP}${unit}`;
}
